force-app/main/default/objects/AccountingPiece__c/AccountingPiece__c.object-meta.xml
<CustomObject>
    <label>Pièce comptable</label>
    <nameField>
        <displayFormat>PIC/{YYYY}/{0000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pièces comptables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountingPiece__c/fields/creditMemo__c.field-meta.xml
<CustomField>
    <fullName>creditMemo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Avoir</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CreditMemo__c.creditMemoReference__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>CreditMemo__c.customerOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.order__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CreditMemo__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.invoiceReference__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Invoice__c.customerOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.order__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/refundReason__c.field-meta.xml
<CustomField>
    <fullName>refundReason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motif de remboursement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RefundReason</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Pièces comptables (Motif de remboursement)</relationshipLabel>
    <relationshipName>AccountingPieces_Refund</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/recordTypes/CheckRequest.recordType-meta.xml
<RecordType>
    <fullName>CheckRequest</fullName>
    <active>true</active>
    <label>Demande de chèque spécifique</label>
</RecordType>

force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditMemo__c/CreditMemo__c.object-meta.xml
<CustomObject>
    <description>Gestion des avoirs basée sur la modélisation des avoirs du modules Salesforce Billing</description>
    <label>Avoir</label>
    <nameField>
        <displayFormat>AVR/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de l’avoir</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avoirs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditMemo__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>Avoirs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/refundReason__c.field-meta.xml
<CustomField>
    <fullName>refundReason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motif de remboursement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RefundReason</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Avoirs (Motif de remboursement)</relationshipLabel>
    <relationshipName>CreditMemosRefundReason</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Gestion des factures basée sur la modélisation du module Salesforce Billing</description>
    <label>Facture</label>
    <nameField>
        <displayFormat>FAC/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de la facture</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencial__c/Referencial__c.object-meta.xml
<CustomObject>
    <description>Objet contenant le référentiel de KparK (Documents, MF, CGV, autre etc...)</description>
    <label>Référentiel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencial__c/fields/KparKReference__c.field-meta.xml
<CustomField>
    <fullName>KparKReference__c</fullName>
    <description>Référence interne unique à K par K</description>
    <externalId>true</externalId>
    <label>Référence</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/refundType__c.field-meta.xml
<CustomField>
    <fullName>refundType__c</fullName>
    <label>Type de remboursement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CheckRequest</fullName>
                <label>Demande de chèque</label>
            </value>
            <value>
                <fullName>Refund</fullName>
                <label>Remboursement siège</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Ctrl_RefundRequestPDF.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_Ctrl_RefundRequestPDF
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 16/05/2022
//-- Version     : 1.0
//-- Description : Classe de tests de Ctrl_RefundRequestPDF
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
@isTest
private class Test_Ctrl_RefundRequestPDF {
    private static final Id RT_ACC_PERSO = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PERSO_RT);
    private static final Id RT_REF_ENTITY = DAL.getRecordTypeIdByDevName('Referencial__c',Constants.REFERENCIAL_ENTITY_RT);  
    private static final Id RT_REF_REFUNDREASON = DAL.getRecordTypeIdByDevName('Referencial__c',Constants.REFERENCIAL_REFUNDREASON_RT);  
    private static final Id RT_ACC_ENTITY = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_ENTITY_RT);
    private static final Id RT_CRED_INVOICE = DAL.getRecordTypeIdByDevName('CreditMemo__c',Constants.CREDITMEMO_INVOICECREDITMEMO_RT); 

    @testSetup 
    static void setup() {
        // Création Referencial        
        List<Referencial__c> refToInsert = new List<Referencial__c>();
        refToInsert.add(Utils_Test.createPaymentMethod('VIREMENT','PAY-0012',Date.today(),null,false));
        refToInsert.add(Utils_Test.createPaymentMethod('CHEQUE','PAY-0004',Date.today(),null,false));
        insert refToInsert;
        Referencial__c refMag = Utils_Test.createReferencial('Magasin', 'MAG', Date.today(), null, 
                                                             RT_REF_ENTITY, true, true, true, true, true);   
        Referencial__c refReason = Utils_Test.createReferencial('Remb', 'REMB-01', Date.today(), null, RT_REF_REFUNDREASON, false, false, false, false, false);
        refReason.refundType__c = 'CheckRequest';
        insert refReason;
        // Création d'un compte
        Account a = Utils_Test.createAccount('Dupont','Jean','test@test.fr', RT_ACC_PERSO, 'Email',true);
        Account entite = Utils_Test.createEntity('MAGTESTTEST', 'MAGTESTTEST', Date.today(), '0123456789', refMag.Id, true);
        Chantier__c chant = Utils_Test.createChantier('test',entite.Id,true);
        // Création commande        
        Order newCustomerOrder = Utils_Test.createCustomerOrder(a.Id, chant.Id, entite.Id, entite.Id, true);    
        // Creation facture
        Invoice__c fac = Utils_Test.createInvoice('Facture', a.Id, entite.Id, Date.today(), entite.Id, chant.Id, true);
        // Création avoir
        CreditMemo__c cred = Utils_Test.createCreditMemo(a.Id, entite.Id, fac.Id, chant.Id, null, newCustomerOrder.Id, RT_CRED_INVOICE, false);
        cred.refundReason__c = refReason.Id;
        insert cred;
    }
    
    @isTest
    private static void testPDF(){
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);

        System.runAs(user){
            Test.startTest();

            Account acc = [SELECT Id FROM Account WHERE RecordTypeId = :RT_ACC_PERSO LIMIT 1];
            Referencial__c refReason = [SELECT Id FROM Referencial__c WHERE KparKReference__c = 'REMB-01' LIMIT 1];
            Account ent = [SELECT Id FROM Account WHERE RecordTypeId = :RT_ACC_ENTITY LIMIT 1];
            CreditMemo__c credMemo = [SELECT Id FROM CreditMemo__c LIMIT 1];

            // Create Piece
            Referencial__c ref1 = LWC_RefundRequestWizard.getDefaultPaymentMethod();   
            LWC_RefundRequestWizard.createRefundRequestPiece(credMemo.Id, refReason.Id, ent.Id, ref1.Id, Date.today(), -100);
            AccountingPiece__c accPiece = [SELECT Id FROM AccountingPiece__c LIMIT 1]; 

            // Création de la page et ajout des parametres
            PageReference pagePDF = Page.VF_RefundRequestPDF;
            pagePDF.getParameters().put('accPieceId', accPiece.Id);
            Test.setCurrentPage(pagePDF);
            Ctrl_RefundRequestPDF ctrl = new Ctrl_RefundRequestPDF();
            Double offsetTime = ctrl.offset;

            Test.stopTest();
        }
    }
}