force-app/main/default/objects/AccountingPiece__c/AccountingPiece__c.object-meta.xml
<CustomObject>
    <label>Pièce comptable</label>
    <nameField>
        <displayFormat>PIC/{YYYY}/{0000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pièces comptables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountingPiece__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BusinessAccount</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PersonalAccount</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>FundingOrganization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/creditMemo__c.field-meta.xml
<CustomField>
    <fullName>creditMemo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Avoir</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CreditMemo__c.creditMemoReference__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>CreditMemo__c.customerOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.order__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CreditMemo__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/inputEntity__c.field-meta.xml
<CustomField>
    <fullName>inputEntity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entité de saisie</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pièces comptables (Saisie)</relationshipLabel>
    <relationshipName>AccountingPieces_Input</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/paymentMethod__c.field-meta.xml
<CustomField>
    <fullName>paymentMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mode de règlement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PaymentMethod</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Pièces comptables (Mode de règlement)</relationshipLabel>
    <relationshipName>AccountingPieces_PaymentMethod</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/pieceDate__c.field-meta.xml
<CustomField>
    <fullName>pieceDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date de la pièce</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/refundReason__c.field-meta.xml
<CustomField>
    <fullName>refundReason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motif de remboursement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RefundReason</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Pièces comptables (Motif de remboursement)</relationshipLabel>
    <relationshipName>AccountingPieces_Refund</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/CreditMemo__c.object-meta.xml
<CustomObject>
    <description>Gestion des avoirs basée sur la modélisation des avoirs du modules Salesforce Billing</description>
    <label>Avoir</label>
    <nameField>
        <displayFormat>AVR/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de l’avoir</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avoirs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditMemo__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/creditMemoDate__c.field-meta.xml
<CustomField>
    <fullName>creditMemoDate__c</fullName>
    <label>Date de l&apos;avoir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/creditMemoReference__c.field-meta.xml
<CustomField>
    <fullName>creditMemoReference__c</fullName>
    <externalId>true</externalId>
    <label>Référence de l’avoir</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/refundReason__c.field-meta.xml
<CustomField>
    <fullName>refundReason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motif de remboursement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RefundReason</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Avoirs (Motif de remboursement)</relationshipLabel>
    <relationshipName>CreditMemosRefundReason</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referencial__c/Referencial__c.object-meta.xml
<CustomObject>
    <description>Objet contenant le référentiel de KparK (Documents, MF, CGV, autre etc...)</description>
    <label>Référentiel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Ctrl_RefundRequestPDF.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Ctrl_RefundRequestPDF
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 13/04/2022
//-- Version     : 1.0
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
public without sharing class Ctrl_RefundRequestPDF {
    public AccountingPiece__c refundPiece { get; set; }
    public String adresseChantier { get; set; }
    public String adresseClient { get; set; }
    
    /**
    * @description Constructeur
    * @return Ctrl_RefundRequestPDF
    */
    public Ctrl_RefundRequestPDF() {
        refundPiece = new AccountingPiece__c();

        String param = ApexPages.currentPage().getParameters().get('accPieceId');
        System.debug('## accPieceId: ' + param);      
        String param2 = ApexPages.currentPage().getParameters().get('accPiece');
        System.debug('## accPiece: ' + param2);

        if(String.isNotBlank(param)) {  
            // Récupération infos de la pièces
            List<AccountingPiece__c> accountPieceList = [SELECT Id, Name, order__r.OrderNumber, order__r.amount__c,
                                                                account__r.Name, account__r.rue__c,account__r.codePostal__c, account__r.ville__c, 
                                                                order__r.chantier__r.rue__c, order__r.chantier__r.codePostal__c, order__r.chantier__r.ville__c,
                                                                creditMemo__r.creditMemoReference__c, creditMemo__r.creditMemoDate__c, creditMemo__r.amount__c,
                                                                paymentMethod__c, paymentMethod__r.Name, refundReason__c, refundReason__r.Name,
                                                                inputEntity__c, inputEntity__r.Name, CreatedBy.Name, CreatedDate, pieceDate__c, amount__c
                                                    FROM AccountingPiece__c WHERE Id = :param];
            System.debug('## Taille: ' + accountPieceList.size());
            // Formatage des résultats pour l'export
            if(!accountPieceList.isEmpty()) {
                refundPiece = accountPieceList[0];
            } else if(String.isNotBlank(param2)) {
                refundPiece = (AccountingPiece__c)JSON.deserialize(param2, AccountingPiece__c.class);
            }
            adresseClient = refundPiece.account__r.rue__c+' - '+refundPiece.account__r.codePostal__c+' '+refundPiece.account__r.ville__c;
            adresseChantier = refundPiece.order__r.chantier__r.rue__c+' - '+refundPiece.order__r.chantier__r.codePostal__c+' '+refundPiece.order__r.chantier__r.ville__c;
            System.debug('## refundPiece: ' + refundPiece);
        }
    }
    
    public Double offset{get{
        //Milliseconds to Day
        return UserInfo.getTimeZone().getOffset(DateTime.now()) / (1000 * 3600 * 24.0);
    }}
}