force-app/main/default/objects/AccountingPiece__c/AccountingPiece__c.object-meta.xml
<CustomObject>
    <label>Pièce comptable</label>
    <nameField>
        <displayFormat>PIC/{YYYY}/{0000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pièces comptables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountingPiece__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.invoiceReference__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Invoice__c.customerOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.order__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BankAccountVisibility__c/BankAccountVisibility__c.object-meta.xml
<CustomObject>
    <description>Objet de liaison entre les comptes bancaires et les entités</description>
    <label>Visibilité compte bancaire</label>
    <nameField>
        <displayFormat>BAV/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visibilités compte bancaire</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAccountVisibility__c/fields/bankAccount__c.field-meta.xml
<CustomField>
    <fullName>bankAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte bancaire</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BankAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Visibilités compte bancaire</relationshipLabel>
    <relationshipName>BankAccountVisibilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BankAccountVisibility__c/fields/entity__c.field-meta.xml
<CustomField>
    <fullName>entity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entité</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visibilités compte bancaire</relationshipLabel>
    <relationshipName>BankAccountVisibilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BankAccountVisibility__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>Début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/serviceEntity__c.field-meta.xml
<CustomField>
    <fullName>serviceEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dépôt (Entité service)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entités service (Chantier)</relationshipLabel>
    <relationshipName>ChantierServiceEntities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Gestion des factures basée sur la modélisation du module Salesforce Billing</description>
    <label>Facture</label>
    <nameField>
        <displayFormat>FAC/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de la facture</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/billingAccount__c.field-meta.xml
<CustomField>
    <fullName>billingAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Compte facturé</description>
    <label>Compte de facturation</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PersonalAccount</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BusinessAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>CustomerInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Order.RecordTypeId</field>
            <operation>equals</operation>
            <value>Commande client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/headOfficeLegalForm__c.field-meta.xml
<CustomField>
    <fullName>headOfficeLegalForm__c</fullName>
    <defaultValue>&quot;SAS&quot;</defaultValue>
    <label>Forme juridique du siège social</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LegalForm</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/invoiceDate__c.field-meta.xml
<CustomField>
    <fullName>invoiceDate__c</fullName>
    <label>Date de facture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/invoiceReference__c.field-meta.xml
<CustomField>
    <fullName>invoiceReference__c</fullName>
    <description>Numéro comptable de la facture</description>
    <externalId>true</externalId>
    <label>Référence de la facture</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/perceivedAmount__c.field-meta.xml
<CustomField>
    <fullName>perceivedAmount__c</fullName>
    <description>Dans le cas d&apos;un paiement d&apos;acompte ou d&apos;une attribution de paiement avec un reste du paiement</description>
    <label>Montant perçu</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/priceReduction__c.field-meta.xml
<CustomField>
    <fullName>priceReduction__c</fullName>
    <label>Réduction de prix</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/toPerceiveAmount__c.field-meta.xml
<CustomField>
    <fullName>toPerceiveAmount__c</fullName>
    <description>Le montant que le client doit payer, déduction des avoirs et des paiements effectués</description>
    <label>Montant à percevoir</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Referencial__c/Referencial__c.object-meta.xml
<CustomObject>
    <description>Objet contenant le référentiel de KparK (Documents, MF, CGV, autre etc...)</description>
    <label>Référentiel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencial__c/fields/KparKReference__c.field-meta.xml
<CustomField>
    <fullName>KparKReference__c</fullName>
    <description>Référence interne unique à K par K</description>
    <externalId>true</externalId>
    <label>Référence</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/maxPayableAmount__c.field-meta.xml
<CustomField>
    <fullName>maxPayableAmount__c</fullName>
    <label>Montant max. payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/minPayableAmount__c.field-meta.xml
<CustomField>
    <fullName>minPayableAmount__c</fullName>
    <label>Montant min. payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/requiredExternalBankAccount__c.field-meta.xml
<CustomField>
    <fullName>requiredExternalBankAccount__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Compte bancaire externe requis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date de début de validité</description>
    <label>Début de validité</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referencial__c/recordTypes/BankAccount.recordType-meta.xml
<RecordType>
    <fullName>BankAccount</fullName>
    <active>true</active>
    <description>Informations pour les comptes bancaire des entités KparK</description>
    <label>Compte bancaire</label>
</RecordType>

force-app/main/default/classes/Test_LWC_AdvancePaymentWizard.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_LWC_AdvancePaymentWizard
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 01/03/2022
//-- Version     : 1.0
//-- Description : Classe de tests de LWC_AdvancePaymentWizard
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
@isTest
private class Test_LWC_AdvancePaymentWizard {
    private static final Id accPersoRT = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PERSO_RT);
    private static final Id refEntityRT = DAL.getRecordTypeIdByDevName('Referencial__c',Constants.REFERENCIAL_ENTITY_RT);
    private static final Id invoiceRT = DAL.getRecordTypeIdByDevName('Invoice__c', Constants.INVOICE_INVOICE_RT);
    private static final Id refBank = DAL.getRecordTypeIdByDevName('Referencial__c', 'BankAccount');
    private static final Id customerOrderRTId = DAL.getRecordTypeIdByDevName('Order', Constants.ORDER_RT_CUSTOMER);
    private static final Id accEntityRT = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_ENTITY_RT);

    @testSetup 
    static void setup() {
        // Création Ref
        List<Account> accToInsert = new List<Account>();
        accToInsert.add(new Account(Name = 'ORG',RecordTypeId = DAL.getRecordTypeIdByDevName('Account', 'FundingOrganization'), KparKReference__c = 'ORG-FIN1', startDate__c = Date.today()));
        //insert accToInsert;
        // Création Referencial        
        List<Referencial__c> refToInsert = new List<Referencial__c>();
        refToInsert.add(Utils_Test.createPaymentMethod('CHEQUE','PAY-0004',Date.today(),null,false));
        Referencial__c ref = Utils_Test.createPaymentMethod('VIREMENT','PAY-0012',Date.today(),null,false);
        ref.minPayableAmount__c = 0;
        ref.maxPayableAmount__c = 10000;
        refToInsert.Add(ref);       
        //refToInsert.add(Utils_Test.createPaymentMethod('CHEQUE','PAY-0004',Date.today(),null,false));
        refToInsert.add(Utils_Test.createReferencial('Magasin', 'MAG', Date.today(), null, refEntityRT, true, true, true, true, false));
        insert refToInsert;
        // Création d'un compte
        Account a = Utils_Test.createAccount('Dupont','Jean','test@test.fr', accPersoRT, 'Email',false);
        accToInsert.add(a);
        //Account entite = Utils_Test.createEntity('MAGTESTTEST', 'MAGTESTTEST', Date.today(), '0123456789', refMag.Id, true);
        Account ent = Utils_Test.createEntity('MAGTESTTESTD', 'MAGTESTTESTD', Date.today(), '0123456789', null, false);
        accToInsert.add(ent);
        insert accToInsert;
        Chantier__c chant = Utils_Test.createChantier('test',ent.Id,true);
        // Création banque
        Referencial__c bank = Utils_Test.createBankAccount('BANK','BANK-FIN1',Date.today(),null,true);
        BankAccountVisibility__c bankV = new BankAccountVisibility__c(bankAccount__c=bank.Id, entity__c=ent.Id, startDate__c = Date.today());
        bankV.startDate__c = Date.newInstance(2022, 06, 09);
        insert bankV;
        // Création commande        
        Order newCustomerOrder = Utils_Test.createCustomerOrder(a.Id, false);
        newCustomerOrder.billingCity = 'test';
        newCustomerOrder.billingPostalCode = '12345';
        newCustomerOrder.chantier__c = chant.Id;
        newCustomerOrder.shippingName__c = 'test';
        newCustomerOrder.shippingPostalCode = '12345';
        newCustomerOrder.shippingCity = 'test';
        newCustomerOrder.serviceEntity__c = ent.Id;
        insert newCustomerOrder;
		system.debug('newCustomerOrder.serviceEntity__c '+newCustomerOrder.serviceEntity__c);        
        Product2 productTest1 = Utils_Test.createProduct('Test1', 'TEST1' , true);
        PricebookEntry pbEntry;
        List<PricebookEntry> pbeList = [SELECT Id, Pricebook2Id, Product2Id, UnitPrice, IsActive, UseStandardPrice 
                                  FROM PricebookEntry 
                                  WHERE Product2Id = :productTest1.Id];
        for(PricebookEntry pbeSelected : pbeList) {
            if(pbeSelected.Product2Id == productTest1.Id) pbEntry = pbeSelected;
        }
        OrderItem newOrderItem1 = Utils_Test.createOrderItem(newCustomerOrder.Id, pbEntry.Id, null, productTest1.Id, true);
        // Creation facture
        Invoice__c inv = Utils_Test.createInvoice('Facture', a.Id, ent.Id, Date.today(), ent.Id, chant.Id, false); 
        inv.amount__c = 200;
        inv.autoComputedAmount__c = false;
        inv.perceivedAmount__c = 100;
        inv.billingAccount__c = a.Id;
        //inv.invoiceDate__c = Date.today();
        inv.customerOrder__c = newCustomerOrder.Id;        
        inv.headOfficeLegalForm__c = 'Autre';
        inv.invoiceReference__c = '1';
        inv.toPerceiveAmount__c = 50;
        insert inv;
        system.debug('customerOrder__r.serviceEntity__c'+inv.customerOrder__r.serviceEntity__c);
        System.debug('inv amount:'+inv.amount__c + ', autocalc:'+inv.autoComputedAmount__c);
    }
    
    @isTest
    private static void testAccountB2C(){
        Test.startTest();
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        System.runAs(user){
            

            // Update order
            Account acc = [SELECT Id FROM Account WHERE RecordTypeId = :accPersoRT LIMIT 1];
            Account ent = [SELECT Id FROM Account WHERE RecordTypeId = :accEntityRT LIMIT 1];
            Referencial__c banck = [SELECT Id FROM Referencial__c WHERE RecordTypeId = :refBank LIMIT 1];
            Order newCustomerOrder = [SELECT Id,Order.AccountId FROM Order LIMIT 1];
            newCustomerOrder.advancePaymentAmount1__c = 100;
            newCustomerOrder.advancePaymentAmount2__c = 100;
            newCustomerOrder.amount__c = 200;
            newCustomerOrder.isValid__c = true;
            newCustomerOrder.serviceEntity__c = ent.Id;
            update newCustomerOrder;

            Referencial__c ref1 = LWC_AdvancePaymentWizard.getDefaultPaymentMethod(false);
            List<Invoice__c> newInvoiceList = LWC_AdvancePaymentWizard.getInvoices(acc.Id, false, banck.Id, Date.today());
            Assert.areEqual(1,newInvoiceList.size());
            List<Order> newOrderList = LWC_AdvancePaymentWizard.getCustomerOrders(acc.Id, false, banck.Id, Date.today());
            Assert.areEqual(1,newOrderList.size());

            String result = LWC_AdvancePaymentWizard.createAccountingPieces(acc.Id, ent.Id, false, null, Date.today(), null, 400, ref1.Id, 
                                                            'TEST', 'Test', newOrderList, newInvoiceList);
            Assert.areEqual('OK', result);
            List<AccountingPiece__c> accPieceList = [SELECT Id FROM AccountingPiece__c];
            //3 nouvelles pièce crées (1 composite , 1 pour commande, 1 pour facture)
            Assert.areEqual(3,accPieceList.size());
        }
        Test.stopTest();
    }
    
    @isTest
    private static void testDatatableInvoice(){
        
        Test.startTest();
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);

        
        System.runAs(user){       
            Account acc = [SELECT Id,FirstName,LastName,PersonEmail FROM Account WHERE RecordTypeId = :accPersoRT LIMIT 1];
			Referencial__c banck = [SELECT Id FROM Referencial__c WHERE RecordTypeId = :refBank LIMIT 1];
            List<Invoice__c> invo = [SELECT Id FROM Invoice__c WHERE RecordTypeId = :invoiceRT];
            system.debug('banck '+banck);
            system.debug('invo '+invo);           
            
            

            List<Map<String,String>> newValues = new List<Map<String,String>>();
            Map<String, String> mapParameters = new Map<String, String>();
            mapParameters.put('Id', invo[0].Id);
            mapParameters.put('perceivedAmount__c', '4500');
            mapParameters.put('priceReduction__c','1000');
            newValues.add(mapParameters);
            
            List<Invoice__c> invToUpdateList = LWC_AdvancePaymentWizard.updateDatatableInvoices(newValues, invo);
            update invToUpdateList;

            Invoice__c invUpdated = [SELECT priceReduction__c FROM Invoice__c LIMIT 1]; 
            Assert.areEqual(1000,invUpdated.priceReduction__c);
        }

        Test.stopTest();
    }
    
    @isTest
    private static void testDatatableOrder(){
        Test.startTest();
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);

        System.runAs(user){

            Account acc = [SELECT Id FROM Account WHERE RecordTypeId = :accPersoRT LIMIT 1];
            Account ent = [SELECT Id FROM Account WHERE RecordTypeId = :accEntityRT LIMIT 1];
            Referencial__c banck = [SELECT Id FROM Referencial__c WHERE RecordTypeId = :refBank LIMIT 1];
            Order newCustomerOrder = [SELECT Id FROM Order LIMIT 1];
            newCustomerOrder.advancePaymentAmount1__c = 100;
            newCustomerOrder.advancePaymentAmount2__c = 100;
            newCustomerOrder.amount__c = 200;
            newCustomerOrder.isValid__c = true;
            newCustomerOrder.serviceEntity__c = ent.Id;
            update newCustomerOrder;
            List<Order> newOrderList = LWC_AdvancePaymentWizard.getCustomerOrders(acc.Id, false, banck.Id, Date.today());
            //repasser la valeur du staut en nom api pour évter l'erreur à l'update
            newOrderList[0].Status = 'Validated';

            List<Map<String,String>> newValues = new List<Map<String,String>>();
            Map<String, String> mapParameters = new Map<String, String>();
            mapParameters.put('Id', newOrderList[0].Id);
            mapParameters.put('advPaymentAmountSum__c', '4500');
            mapParameters.put('shippingCost__c','1000');
            newValues.add(mapParameters);
            
            List<Order> orderToUpdate = LWC_AdvancePaymentWizard.updateDatatableOrders(newValues, newOrderList);
            update orderToUpdate;
            Order orderUpdated = [SELECT shippingCost__c FROM Order LIMIT 1];
            Assert.areEqual(1000,orderUpdated.shippingCost__c);
        }
        Test.stopTest();
    }
    
    @isTest
    private static void testUtils(){
        Test.startTest();

        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        System.runAs(user)
        {
            Account ent = [SELECT Id FROM Account WHERE RecordTypeId = :accEntityRT LIMIT 1];
            Referencial__c bank = [SELECT Id,Name FROM Referencial__c WHERE Name = 'BANK' LIMIT 1];

            Referencial__c ref1 = LWC_AdvancePaymentWizard.getDefaultPaymentMethod(false);
            Referencial__c ref2 = LWC_AdvancePaymentWizard.getDefaultPaymentMethod(true);
            Assert.areEqual('CHEQUE',ref1.Name);
            Assert.areEqual('VIREMENT',ref2.Name);
            ref2 = LWC_AdvancePaymentWizard.getPaymentMethodInfos(ref2.Id);
            Assert.areEqual(true,ref2.requiredExternalBankAccount__c);
            Assert.areEqual(0,ref2.minPayableAmount__c);
            Assert.areEqual(10000,ref2.maxPayableAmount__c);
            AuraHandledException ex = LWC_AdvancePaymentWizard.generateAuraException('TEST');
            Assert.areEqual('TEST', ex.getMessage());
            String bkId = LWC_AdvancePaymentWizard.getBankAccount(ent.Id, Date.today());
            Assert.areEqual(bank.Id,bkId);
            String bankAccountName = LWC_AdvancePaymentWizard.getBankAccountName(bkId);
            Assert.areEqual(bank.Name,bankAccountName);
        }
        Test.stopTest();
    }
    
    @isTest
    private static void testgetVisibilityVerification(){
        Test.startTest();
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);

        System.runAs(user){
       		Account ent = [SELECT Id FROM Account WHERE RecordTypeId = :accEntityRT LIMIT 1];
            Referencial__c banck = [SELECT Id FROM Referencial__c WHERE RecordTypeId = :refBank LIMIT 1];
            Boolean result = LWC_AdvancePaymentWizard.getVisibilityVerification(ent.Id, banck.Id, Date.today());
            System.assertEquals(true, result, 'Le résultat de la vérification de visibilité devrait être vrai.');
            }
        Test.stopTest();
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}