force-app/main/default/objects/AccountingPiece__c/AccountingPiece__c.object-meta.xml
<CustomObject>
    <label>Pièce comptable</label>
    <nameField>
        <displayFormat>PIC/{YYYY}/{0000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pièces comptables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountingPiece__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BusinessAccount</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PersonalAccount</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>FundingOrganization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/creditMemo__c.field-meta.xml
<CustomField>
    <fullName>creditMemo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Avoir</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CreditMemo__c.creditMemoReference__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>CreditMemo__c.customerOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.order__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CreditMemo__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/inputEntity__c.field-meta.xml
<CustomField>
    <fullName>inputEntity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entité de saisie</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pièces comptables (Saisie)</relationshipLabel>
    <relationshipName>AccountingPieces_Input</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/orderEntity__c.field-meta.xml
<CustomField>
    <fullName>orderEntity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entité de la commande</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pièces comptables (Commande)</relationshipLabel>
    <relationshipName>AccountingPieces_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/paymentMethod__c.field-meta.xml
<CustomField>
    <fullName>paymentMethod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mode de règlement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PaymentMethod</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Pièces comptables (Mode de règlement)</relationshipLabel>
    <relationshipName>AccountingPieces_PaymentMethod</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/pieceDate__c.field-meta.xml
<CustomField>
    <fullName>pieceDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date de la pièce</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/refundReason__c.field-meta.xml
<CustomField>
    <fullName>refundReason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motif de remboursement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RefundReason</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Pièces comptables (Motif de remboursement)</relationshipLabel>
    <relationshipName>AccountingPieces_Refund</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/CreditMemo__c.object-meta.xml
<CustomObject>
    <description>Gestion des avoirs basée sur la modélisation des avoirs du modules Salesforce Billing</description>
    <label>Avoir</label>
    <nameField>
        <displayFormat>AVR/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de l’avoir</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avoirs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditMemo__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/creditMemoDate__c.field-meta.xml
<CustomField>
    <fullName>creditMemoDate__c</fullName>
    <label>Date de l&apos;avoir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/creditMemoReference__c.field-meta.xml
<CustomField>
    <fullName>creditMemoReference__c</fullName>
    <externalId>true</externalId>
    <label>Référence de l’avoir</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>CreditMemos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/refundReason__c.field-meta.xml
<CustomField>
    <fullName>refundReason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motif de remboursement</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>RefundReason</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Avoirs (Motif de remboursement)</relationshipLabel>
    <relationshipName>CreditMemosRefundReason</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referencial__c/Referencial__c.object-meta.xml
<CustomObject>
    <description>Objet contenant le référentiel de KparK (Documents, MF, CGV, autre etc...)</description>
    <label>Référentiel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencial__c/fields/KparKReference__c.field-meta.xml
<CustomField>
    <fullName>KparKReference__c</fullName>
    <description>Référence interne unique à K par K</description>
    <externalId>true</externalId>
    <label>Référence</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/maxPayableAmount__c.field-meta.xml
<CustomField>
    <fullName>maxPayableAmount__c</fullName>
    <label>Montant max. payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/minPayableAmount__c.field-meta.xml
<CustomField>
    <fullName>minPayableAmount__c</fullName>
    <label>Montant min. payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/refundType__c.field-meta.xml
<CustomField>
    <fullName>refundType__c</fullName>
    <label>Type de remboursement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CheckRequest</fullName>
                <label>Demande de chèque</label>
            </value>
            <value>
                <fullName>Refund</fullName>
                <label>Remboursement siège</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/requiredExternalBankAccount__c.field-meta.xml
<CustomField>
    <fullName>requiredExternalBankAccount__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Compte bancaire externe requis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Referencial__c/recordTypes/PaymentMethod.recordType-meta.xml
<RecordType>
    <fullName>PaymentMethod</fullName>
    <active>true</active>
    <label>Mode de règlement</label>
</RecordType>

force-app/main/default/classes/LWC_RefundRequestWizard.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : LWC_RefundRequestWizard
//-- Modifie par : SOPRA STERIA
//-- Modifie le  : 13/05/2022
//-- Version     : 1.0
//-- * 1.0 - Init
//-- --------------------------------------------------------------------------------- --
public without sharing class LWC_RefundRequestWizard {

    /**
    * @description Récupération du mode de réglement par défaut
    * @return Mode de réglement par défaut
    */
    @AuraEnabled(cacheable = true)
    public static Referencial__c getDefaultPaymentMethod(){
       System.debug('### DEBUT LWC_RefundRequestWizard.getDefaultPaymentMethod'); 
       Referencial__c result = null;

        try {
            String refDefaultValue = PropertiesUtils.getStringValue('ref.paymentMethodBankCheck.code', 'PAY-0004');
            String refRTId = DAL.getRecordTypeIdByDevName('Referencial__c', 'PaymentMethod'); 
            for(Referencial__c ref : [SELECT  Id, Name, requiredExternalBankAccount__c, minPayableAmount__c, maxPayableAmount__c
                                        FROM Referencial__c 
                                        WHERE RecordTypeId = :refRTId AND KparKReference__c = :refDefaultValue LIMIT 1]) {     
                result = ref;
            }  
            System.debug('## result: '+result); 
        } catch(Exception e) {
            System.debug('ERREUR : ' + e.getMessage() + ' ' + e.getTypeName() + ' ' + e.getStackTraceString());
            throw generateAuraException(e.getMessage());
        }
        System.debug('### FIN LWC_RefundRequestWizard.getDefaultPaymentMethod'); 
        return result;
    }

    /**
    * @description Création de la piece comptable de demande de remboursement
    * @param creditMemoId Id de l'avoir
    * @param refundReasonId Id du motif de remboursement
    * @param inputEntityId Id de l'entité
    * @param paymentMethodId Id du mode de réglement
    * @param accountingDate Date comptable
    * @param pieceAmount Montant
    * @return Id du PDF
    */
    @AuraEnabled
    public static String createRefundRequestPiece(String creditMemoId, String refundReasonId, String inputEntityId, 
                                                    String paymentMethodId, Date pieceDate, Decimal pieceAmount) {
        System.debug('### DEBUT LWC_RefundRequestWizard.createRefundRequestPiece'); 
        System.debug('## creditMemoId: '+ creditMemoId);
        System.debug('## refundReasonId: '+ refundReasonId);
        System.debug('## inputEntityId: '+inputEntityId);
        System.debug('## paymentMethodId: '+paymentMethodId);
        System.debug('## pieceDate: '+ pieceDate);
        String result = null; 

        try{
            if(String.isNotBlank(creditMemoId)){
                // Récupération des infos de l'avoir
                CreditMemo__c credMemo = [SELECT Id, customerOrder__c, customerOrder__r.serviceEntity__c, refundReason__c, 
                                            refundReason__r.refundType__c FROM CreditMemo__c WHERE Id = :creditMemoId];
                // Récupération des infos du motif de remboursement
                Referencial__c refundRes = [SELECT Id, refundType__c FROM Referencial__c WHERE Id = :refundReasonId];
                System.debug('## RefundType: '+refundRes.refundType__c);
                // Récuéparation du RT
                String accPieceRTId = DAL.getRecordTypeIdByDevName('AccountingPiece__c', refundRes.refundType__c); 
                System.debug('## accPieceRTId: '+accPieceRTId);

                // Création de la piece
                AccountingPiece__c accPiece = new AccountingPiece__c(
                    RecordTypeId = accPieceRTId,
                    order__c = credMemo.customerOrder__c,
                    orderEntity__c = credMemo.customerOrder__r.serviceEntity__c,
                    inputEntity__c = inputEntityId,
                    creditMemo__c = credMemo.Id,
                    pieceDate__c = pieceDate,
                    refundReason__c = refundReasonId,
                    amount__c = pieceAmount,
                    paymentMethod__c = paymentMethodId
                );
                System.debug('## Accounting Piece: '+ accPiece);
                insert accPiece;

                // Création du PDF
                result = createDocumentPDF(accPiece.Id, credMemo.Id);
            }
        }
        catch(Exception e) {
            System.debug('ERREUR : ' + e.getMessage() + ' ' + e.getTypeName() + ' ' + e.getStackTraceString());
            throw generateAuraException(e.getMessage());
        }
        System.debug('### FIN LWC_RefundRequestWizard.createRefundRequestPiece');
        return result;
         
    }

    /**
    * @description Fonction pour générer le document PDF 
    * @param accPieceId Id de la pièce
    * @param creditMemoId Id de l'avoir
    * @return String Id de la pièce jointe (ContentDocument)
    */
    @AuraEnabled
    public static String createDocumentPDF(String accPieceId, String creditMemoId) {
        System.debug('### DEBUT LWC_RefundRequestWizard.createDocumentPDF');
        System.debug('## accPieceId: '+accPieceId);
        String result;

        try {        
            // DR / <n° avoir> / <yyyy/mm/dd>
            List<CreditMemo__c> credMemo = [SELECT Id, creditMemoReference__c FROM CreditMemo__c WHERE Id = :creditMemoId LIMIT 1]; 
            String dateFormated = DateTime.newInstance(Date.today().year(),Date.today().month(),Date.today().day()).format('yyyy/MM/dd');
            String filename = 'DR / '+credMemo[0].creditMemoReference__c+' / '+dateFormated+'.pdf';
            System.debug('## filename: '+filename);

            AccountingPiece__c refundPiece;
            List<AccountingPiece__c> accountPieceList = [SELECT Id, Name, order__r.OrderNumber, order__r.amount__c,
                                                                account__r.Name, account__r.rue__c,account__r.codePostal__c, account__r.ville__c, 
                                                                order__r.chantier__r.rue__c, order__r.chantier__r.codePostal__c, order__r.chantier__r.ville__c,
                                                                creditMemo__r.creditMemoReference__c, creditMemo__r.creditMemoDate__c, creditMemo__r.amount__c,
                                                                paymentMethod__c, paymentMethod__r.Name, refundReason__c, refundReason__r.Name,
                                                                inputEntity__c, inputEntity__r.Name, CreatedBy.Name, CreatedDate, pieceDate__c, amount__c
                                                    FROM AccountingPiece__c WHERE Id = :accPieceId];

            // Creation PDF
            Blob documentBlob;            
            PageReference pagePDF = Page.VF_RefundRequestPDF;
            pagePDF.getParameters().put('accPieceId', accPieceId);
            if(!accountPieceList.isEmpty()) {
                refundPiece = accountPieceList[0];
                System.debug('## refundPiece: '+refundPiece);
                pagePDF.getParameters().put('accPiece', JSON.serialize(refundPiece));
            }
            if (Test.isRunningTest()) {
                documentBlob = Blob.valueof('test');
            } else {
                documentBlob = pagePDF.getContentAsPDF();
            }
            // Lien du PDF avec l'avoir
            result = Utils_APIMerkure.createContentDocument(creditMemoId, filename, documentBlob, 'Demande de remboursement');  
        } catch(Exception e) {
            System.debug('ERREUR : ' + e.getMessage() + ' ' + e.getTypeName() + ' ' + e.getStackTraceString());
            throw generateAuraException(e.getMessage());
        }
        System.debug('### FIN LWC_RefundRequestWizard.createDocumentPDF');
        return result;
    }

    /**
    * @description Fonction pour construire le message d'exeption correctement (sinon pas de message)
    * https://salesforce.stackexchange.com/questions/122657/testing-aurahandledexceptions
    * @param msg Message d'erreur
    * @return AuraHandledException Exception avec le message d'erreur
    */
    public static AuraHandledException generateAuraException(String msg){
        System.debug('ERREUR : ' + msg);
        AuraHandledException e = new AuraHandledException(msg);
        e.setMessage(msg);
        return e;
    }
}