force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <description>Option pour les lignes de devis Kube2</description>
    <label>Devis Ligne Option</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devis Ligne Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Option__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>ReferentielOptions__c</referenceTo>
    <relationshipName>Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/optionDeletable__c.field-meta.xml
<CustomField>
    <fullName>optionDeletable__c</fullName>
    <formula>( ISPICKVAL(ligneDevis__r.Quote.Status, &quot;A configurer&quot;) || ISPICKVAL(ligneDevis__r.Quote.Status, &quot;Non transmis&quot;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>[#] Ligne option supprimable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TR020_Option.cls
//-- -------------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR020_Option
//-- Modifié par : SOPRA STERIA 
//-- Modifié le  : 27/01/2023
//-- Version     : 1.0
//-- * 1.0 : Init
//-- -------------------------------------------------------------------------------------- --
public with sharing class TR020_Option {
    
    /**
    * @description Méthode exécutant les différentes règles de validation pour les options de lignes de devis
    * @param userContext Objet contexte de l'utilisateur courant
    */
    public static void applyValidationRules(UserContext userContext) {
        System.debug('### DEBUT TR020_Option.applyValidationRules');        
        List<Option__c> oldOpts = (List<Option__c>)Trigger.old;
                
        for(Option__c oldOpt : oldOpts){
            if(oldOpt.optionDeletable__c == false && Trigger.isDelete && Trigger.isBefore) {
                System.debug('## Cannot delete Option: ' + oldOpt.Id);
                oldOpt.addError(Label.quote_error_cantDeleteQuoteLine);
            }  
        }
        
        System.debug('### FIN TR020_Option.applyValidationRules');
    }
}