force-app/main/default/objects/NRV10Calendar__c/NRV10Calendar__c.object-meta.xml
<CustomObject>
    <label>Calendrier de rémunération</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendriers de rémunération</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NRV10Calendar__c/fields/commDate__c.field-meta.xml
<CustomField>
    <fullName>commDate__c</fullName>
    <description>Date de déclenchement du cliché. Utilisé par la tâche programmée pour passer les commissions en cliché et aboutir à leur versement.</description>
    <label>Date de commissionnement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Schedulable_SalesCommissionInstant.cls
/**
 * @description Classe planifiée pour vérifier si un cliché sur commission doit être réalisé.
 * Dans le cas ou un cliché à date du jour est prévu, déclenche le batch de cliché et de génération du csv.
 *
 * Created by Gregory Quinet on 05/10/2020.
 */

global class Schedulable_SalesCommissionInstant implements Schedulable {

    global void execute(SchedulableContext sc) {
        NRV10Calendar__c[] cal = [SELECT Id, commDate__c FROM NRV10Calendar__c WHERE commDate__c = TODAY LIMIT 1];

        if (cal != null && cal.size() > 0) {
            BA_SalesCommissionInstant instant = new BA_SalesCommissionInstant();
            Database.executeBatch(instant);
        }
    }
}