force-app/main/default/objects/NRV10Calendar__c/NRV10Calendar__c.object-meta.xml
<CustomObject>
    <label>Calendrier de rémunération</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendriers de rémunération</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NRV10Calendar__c/fields/commDate__c.field-meta.xml
<CustomField>
    <fullName>commDate__c</fullName>
    <description>Date de déclenchement du cliché. Utilisé par la tâche programmée pour passer les commissions en cliché et aboutir à leur versement.</description>
    <label>Date de commissionnement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_Schedulable_SalesCommissionInstant.cls
/**
 * Created by 4C on 07/10/2020.
 */

@IsTest
public with sharing class Test_Schedulable_SalesCommissionInstant {

    @IsTest
    static void testNotTheGoodDay() {
        NRV10Calendar__c cal3 = new NRV10Calendar__c(commDate__c = Date.today().addDays(2));
        insert cal3;
        String cron = '0 0 0 * * ?';

        Test.startTest();

        Schedulable_SalesCommissionInstant schedul = new Schedulable_SalesCommissionInstant();
        String schId = System.schedule('snapshotSched', cron, schedul);

        Test.stopTest();

        List<AsyncApexJob> jobs = [SELECT Id, ApexClass.Name, Status FROM AsyncApexJob WHERE JobType = 'ScheduledApex'];
        System.assertEquals(1, jobs.size(), 'Schedulable not in asyncApex list');
        System.assertEquals('Schedulable_SalesCommissionInstant', jobs.get(0).ApexClass.Name, 'Expected Schedulable_SalesCommissionInstant but got something else');

        List<AsyncApexJob> batchs = [SELECT Id, ApexClass.Name, Status FROM AsyncApexJob WHERE JobType = 'BatchApex'];
        System.assert(batchs.isEmpty(), 'Batchs should not be queued');
    }

    @IsTest
    static void testTheGoodDay(){
        NRV10Calendar__c cal3 = new NRV10Calendar__c(commDate__c = Date.today());
        insert cal3;

        String cron = '0 0 0 * * ?';

        Test.startTest();

        Schedulable_SalesCommissionInstant schedul = new Schedulable_SalesCommissionInstant();
        String schId = System.schedule('snapshotSched', cron, schedul);

        Test.stopTest();

        List<AsyncApexJob> scheds = [SELECT Id, ApexClass.Name, Status FROM AsyncApexJob WHERE JobType = 'ScheduledApex'];
        System.assertEquals(1, scheds.size(), 'Schedulable not in asyncApex list');
        System.assertEquals('Schedulable_SalesCommissionInstant', scheds.get(0).ApexClass.Name, 'Expected Schedulable_SalesCommissionInstant but got something else');

        List<AsyncApexJob> batchs = [SELECT Id, ApexClass.Name, Status FROM AsyncApexJob WHERE JobType = 'BatchApex'];
        System.assertEquals(1, batchs.size(), 'Wrong number of batch in queue');
        System.assertEquals('BA_SalesCommissionInstant', batchs.get(0).ApexClass.Name, 'Not the expected batch');
    }

}