force-app/main/default/objects/ConnexionClient__c/ConnexionClient__c.object-meta.xml
<CustomObject>
    <label>Connexion client</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connexions client</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConnexionClient__c/fields/details__c.field-meta.xml
<CustomField>
    <fullName>details__c</fullName>
    <label>Détails</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnexionClient__c/fields/etat__c.field-meta.xml
<CustomField>
    <fullName>etat__c</fullName>
    <label>État</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>Erreur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConnexionClient__c/fields/eventDateTime__c.field-meta.xml
<CustomField>
    <fullName>eventDateTime__c</fullName>
    <label>Date et heure de l’événement</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ConnexionClient__c/fields/eventType__c.field-meta.xml
<CustomField>
    <fullName>eventType__c</fullName>
    <label>Type d’évènement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Connexion</fullName>
            </value>
            <value>
                <fullName>Changement MDP</fullName>
            </value>
            <value>
                <fullName>Génération MDP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConnexionClient__c/fields/identifiant__c.field-meta.xml
<CustomField>
    <fullName>identifiant__c</fullName>
    <externalId>true</externalId>
    <label>Identifiant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnexionClient__c/fields/mdpHashEncrypted__c.field-meta.xml
<CustomField>
    <fullName>mdpHashEncrypted__c</fullName>
    <label>Mot de passe (hashé)</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/Utils_Logger.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Utils_Logger
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 30/08/2017
//-- Version     : 1.0
//-- * Classe utilitaire pour l'affichage des messages dans les pages VF
//-- --------------------------------------------------------------------------------- --
public without sharing class Utils_Logger {

    public Utils_Logger() {
        clear();
    }

    public void clear() {
        StaticMessages = new List<PageMessage>();
    }

    public enum Severity {CONFIRM,INFO,WARN,FATAL,ERROR}
    public class PageMessage {
        private Map<Severity,String> SeverityStrMap = new Map<Severity,String>{
            Severity.CONFIRM => 'confirm',
            Severity.INFO => 'info',
            Severity.WARN => 'warning',
            Severity.FATAL => 'danger',
            Severity.ERROR => 'danger'
        };

        public Severity SeverityLevel { get; set; }
        public String SeverityStr { get; set; }
        public String Message { get; set; }

        public PageMessage (Severity theSeverity, String theMessage) {
            this.SeverityLevel = theSeverity;
            this.Message = theMessage;
            this.SeverityStr = SeverityStrMap.get(theSeverity);
        }
    }
    public  List<PageMessage> StaticMessages { get; set; }
    
    public  void addMessage(PageMessage thePageMessage) {
        StaticMessages.add(thePageMessage);
    }
    public  List<PageMessage> getPageMessages(){
        return StaticMessages;
    }

    public  void addErrorMessage(String theMessage) {
        addMessage(new PageMessage(Severity.ERROR, '<strong>ERREUR :</strong> ' + theMessage));
    }

    public  void addConfirmMessage(String theMessage) {
        addMessage(new PageMessage(Severity.CONFIRM, theMessage));
    }

    public  void addWarnMessage(String theMessage) {
        addMessage(new PageMessage(Severity.WARN, theMessage));
    }

    public static void insertNewConnexionClient(String identifiant, String typeEvenement, String etat, String details, String mdp) {
        ConnexionClient__c newConnexion = new ConnexionClient__c(
            identifiant__c = identifiant,
            eventDateTime__c = System.now(),
            eventType__c = typeEvenement,
            etat__c = etat,
            details__c = details,
            mdpHashEncrypted__c = mdp
        );
        insert newConnexion;
    }
}