force-app/main/default/objects/AfterSalesService__c/AfterSalesService__c.object-meta.xml
<CustomObject>
    <description>Objet permettant de gérer plusieurs non-conformité produit</description>
    <label>Dossier SAV</label>
    <nameField>
        <displayFormat>SAV/{YYYY}/{0000000}</displayFormat>
        <label>Numéro SAV</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dossiers SAV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AfterSalesService__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>Description</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AfterSalesService__c/fields/workSite__c.field-meta.xml
<CustomField>
    <fullName>workSite__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Chantier</label>
    <referenceTo>Chantier__c</referenceTo>
    <relationshipName>AfterSalesServices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/classes/Test_IV_CalculateSAVStatusGC.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_IV_CalculateSAVStatusGC
//-- Modifié par : SOPRA STERIA 
//-- Modifié le  : 19/10/2024
//-- Version     : 1.0
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
@isTest
public class Test_IV_CalculateSAVStatusGC {
    private static final Id ACC_PERSO_RTID = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PERSO_RT);
    private static final String RT_AST_CARPENTRY = DAL.getRecordTypeIdByDevName('Asset',Constants.ASSET_CARPENTRY_RT);
    private static final String RT_PNC_INTERNALID = DAL.getRecordTypeIdByDevName('Case', Constants.REQUETE_PNC_INTERNAL_RT);

    @testSetup 
    static void testSetup() {
        Account accountTest = Utils_Test.createAccount('name', 'name', 'test@test.fr', ACC_PERSO_RTID, null, 'Email', true);
        
        Chantier__c chantier = Utils_Test.createChantier('Chantier 1', accountTest.Id,true);

        Product2 prod = Utils_Test.createProduct('Produit Test', 'TEST1', 'Fenetre', 'PVC', 50, 50, false);
        prod.SousMatiere__c = 'Ekilibre';
        prod.isConvertibleAsset__c=true;
        insert prod;

        //PricebookEntry pbe = Utils_Test.createPricebookEntry(prod.Id,true);

        Asset newAsset = Utils_Test.createAsset(RT_AST_CARPENTRY, 'Test1', null, prod.Id, null, chantier.Id, accountTest.Id,false);
        newAsset.controlDate__c = System.today() - 60;
        newAsset.installDate = System.today() - 10;

        insert newAsset;

        AfterSalesService__c dossierSav = new AfterSalesService__c(workSite__c = chantier.Id, description__c = 'TEST');
        insert dossierSav;

        Case caseTest = Utils_Test.createCase(RT_PNC_INTERNALID, accountTest, chantier.Id, Constants.REQUETE_RECLAMATION_METRAGE, '', '', false);
        caseTest.chantier__c = chantier.Id;
        caseTest.AssetId = newAsset.Id;
        caseTest.afterSalesService__c = dossierSav.Id;
        insert caseTest;
    }

    @isTest 
    static void testCalculate() {
        AfterSalesService__c dossierSav = [SELECT Id FROM AfterSalesService__c LIMIT 1];

        Test.startTest();
        

        IV_CalculateAfterSalesServiceStatusGC.FlowInputParameters[] inputList = new IV_CalculateAfterSalesServiceStatusGC.FlowInputParameters[]{};
        IV_CalculateAfterSalesServiceStatusGC.FlowInputParameters input = new IV_CalculateAfterSalesServiceStatusGC.FlowInputParameters();
        input.recordId = dossierSav.Id;
        inputList.add(input);
        IV_CalculateAfterSalesServiceStatusGC.calculateAfterSalesServiceStatusGC(inputList);
        
        Test.stopTest();
    }

    @isTest 
    static void testInvalid() {
        AfterSalesService__c dossierSav = [SELECT Id FROM AfterSalesService__c LIMIT 1];

        Test.startTest();

        IV_CalculateAfterSalesServiceStatusGC.FlowInputParameters[] inputList = new IV_CalculateAfterSalesServiceStatusGC.FlowInputParameters[]{};
        IV_CalculateAfterSalesServiceStatusGC.FlowInputParameters input = new IV_CalculateAfterSalesServiceStatusGC.FlowInputParameters();
        input.recordId = '';
        inputList.add(input);

        try {
            IV_CalculateAfterSalesServiceStatusGC.calculateAfterSalesServiceStatusGC(inputList);
        } catch (Exception e) {
            Assert.areEqual(true, e.getMessage().contains('Le paramètre recordId est vide'));
        }
        
        Test.stopTest();
    }
}