force-app/main/default/objects/AfterSalesService__c/AfterSalesService__c.object-meta.xml
<CustomObject>
    <description>Objet permettant de gérer plusieurs non-conformité produit</description>
    <label>Dossier SAV</label>
    <nameField>
        <displayFormat>SAV/{YYYY}/{0000000}</displayFormat>
        <label>Numéro SAV</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dossiers SAV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AfterSalesService__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>AfterSalesServices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AfterSalesService__c/fields/closedStatusCaseCount__c.field-meta.xml
<CustomField>
    <fullName>closedStatusCaseCount__c</fullName>
    <label>[#] Nombre de requête clôturée</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AfterSalesService__c/fields/diagnosticStatusCaseCount__c.field-meta.xml
<CustomField>
    <fullName>diagnosticStatusCaseCount__c</fullName>
    <label>[#] Nombre de requête diagnostiquée</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AfterSalesService__c/fields/inProgressStatusCaseCount__c.field-meta.xml
<CustomField>
    <fullName>inProgressStatusCaseCount__c</fullName>
    <label>[#] Nombre de requête en cours</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AfterSalesService__c/fields/newStatusCaseCount__c.field-meta.xml
<CustomField>
    <fullName>newStatusCaseCount__c</fullName>
    <label>[#] Nombre de requête nouvelle</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AfterSalesService__c/fields/stageName__c.field-meta.xml
<CustomField>
    <fullName>stageName__c</fullName>
    <defaultValue>&quot;Enregistrement&quot;</defaultValue>
    <label>Etape</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enregistrement</fullName>
            </value>
            <value>
                <fullName>Diagnostic</fullName>
            </value>
            <value>
                <fullName>Résolution</fullName>
            </value>
            <value>
                <fullName>Clôture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AfterSalesService__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <defaultValue>&quot;Nouveau&quot;</defaultValue>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nouveau</fullName>
                <default>true</default>
                <label>Nouveau</label>
            </value>
            <value>
                <fullName>Diagnostiqué</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>A clôturer</fullName>
            </value>
            <value>
                <fullName>Clôturé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AfterSalesService__c/fields/workSite__c.field-meta.xml
<CustomField>
    <fullName>workSite__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Chantier</label>
    <referenceTo>Chantier__c</referenceTo>
    <relationshipName>AfterSalesServices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/proprietaire__c.field-meta.xml
<CustomField>
    <fullName>proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire)</relationshipLabel>
    <relationshipName>proprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TR020_AfterSalesService.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR020_AfterSalesService
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 14/10/2020
//-- Version     : 1.0
//-- * 1.0 : Initialisation
//-- --------------------------------------------------------------------------------- --
public without sharing class TR020_AfterSalesService {
    
    /**
    * @description Méthode exécutant les différentes méthode de MAJ pour les dossiers SAV
    * @param userContext Objet contexte de l'utilisateur courant
    */
    public static void applyUpdateRules(UserContext userContext) {
        if (!Trigger.isExecuting) {
            return;
        }
        
        applyDataUpdateRules(userContext);
        applyStatusUpdateRules(userContext);
    }

    /**
    * @description Méthode exécutant les différentes méthode de MAJ pour les dossiers SAV
    * @param userContext Objet contexte de l'utilisateur courant
    */
    public static void applyDataUpdateRules(UserContext userContext) {
        System.debug('### DEBUT TR020_AfterSalesService.applyDataUpdateRules');
        List<AfterSalesService__c> savsList = (List<AfterSalesService__c>)Trigger.new;
        List<String> chantierIds = new List<String>();
        List<chantier__c> chantiersList = new List<chantier__c>();
        Map<Id, Chantier__c> chantiers = new Map<Id, Chantier__c>();
        
        /** A - Initialisation des données intermédiaires **/
        for(AfterSalesService__c newSAV : savsList) {
            if(newSAV.workSite__c != null) {
                chantierIds.add(newSAV.workSite__c);
            }
        }
        
        if(!chantierIds.isEmpty()) {
            chantiers = new Map<Id, Chantier__c>([SELECT Id, proprietaire__c FROM Chantier__c WHERE Id IN :chantierIds]);
        }
        
        /** B - Application des règles de mise à jour **/
        for(AfterSalesService__c newSAV : savsList) {
            newSAV.OwnerId = Label.system_id_user_kpark;
            
            if(newSAV.account__c == null && chantiers != null && chantiers.get(newSAV.workSite__c) != null) {
                newSAV.account__c = chantiers.get(newSAV.workSite__c).proprietaire__c;
            }
        }
        
        System.debug('### FIN TR020_AfterSalesService.applyDataUpdateRules');
    }

    /**
    * @description Méthode exécutant les règles de mise à jour du statut pour les dossiers SAV
    * @param userContext Objet contexte de l'utilisateur courant
    */
    public static void applyStatusUpdateRules(UserContext userContext) {
        System.debug('### DEBUT TR020_AfterSalesService.applyStatusUpdateRules');
        
        /** B - Application des règles de mise à jour **/
        for(AfterSalesService__c newSAV : (List<AfterSalesService__c>)Trigger.new) {
            // Recalcul de statut en fonction des cases rattachés
            if(newSAV.newStatusCaseCount__c > 0) {
				System.debug('## SAV status 1');
                newSAV.status__c = Constants.REQUETE_STATUS_NEW;
                newSAV.stageName__c = Constants.REQUETE_STEP_REGISTERED;
            } else if(newSAV.diagnosticStatusCaseCount__c > 0) {
				System.debug('## SAV status 2');
                newSAV.status__c = Constants.REQUETE_STATUS_DIAGNOSTIC;
                newSAV.stageName__c = Constants.REQUETE_STEP_DIAGNOSTIC;
            } else if(newSAV.inProgressStatusCaseCount__c > 0) {
				System.debug('## SAV status 3');
                newSAV.status__c = Constants.REQUETE_STATUS_INPROGRESS;
                newSAV.stageName__c = Constants.REQUETE_STEP_RESOLUTION;
            } else if(newSAV.closedStatusCaseCount__c > 0) {
				System.debug('## SAV status 4');
                newSAV.status__c = Constants.REQUETE_STATUS_CLOSED;
                newSAV.stageName__c = Constants.REQUETE_STEP_CLOSED;
            } else {
				System.debug('## SAV status 5');
                newSAV.status__c = Constants.REQUETE_STATUS_NEW;
                newSAV.stageName__c = Constants.REQUETE_STEP_REGISTERED;
            }
			System.debug('## SAV Status: '+newSAV.status__c);
        }
        
        System.debug('### FIN TR020_AfterSalesService.applyStatusUpdateRules');
    }
}