force-app/main/default/objects/Sectorisation__c/Sectorisation__c.object-meta.xml
<CustomObject>
    <label>Sectorisation</label>
    <nameField>
        <label>Nom de Sectorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sectorisation__c/fields/codeDepot__c.field-meta.xml
<CustomField>
    <fullName>codeDepot__c</fullName>
    <label>Code dépôt</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/codeDS__c.field-meta.xml
<CustomField>
    <fullName>codeDS__c</fullName>
    <label>Code DS</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/codeDV__c.field-meta.xml
<CustomField>
    <fullName>codeDV__c</fullName>
    <label>Code DV</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/codeMagasin__c.field-meta.xml
<CustomField>
    <fullName>codeMagasin__c</fullName>
    <label>Code magasin</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/codeRegion__c.field-meta.xml
<CustomField>
    <fullName>codeRegion__c</fullName>
    <label>Code région</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/IRIS__c.field-meta.xml
<CustomField>
    <fullName>IRIS__c</fullName>
    <externalId>true</externalId>
    <label>IRIS</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleDepot__c.field-meta.xml
<CustomField>
    <fullName>libelleDepot__c</fullName>
    <label>Dépôt</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleDS__c.field-meta.xml
<CustomField>
    <fullName>libelleDS__c</fullName>
    <label>DS</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleDV__c.field-meta.xml
<CustomField>
    <fullName>libelleDV__c</fullName>
    <label>DV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleMagasin__c.field-meta.xml
<CustomField>
    <fullName>libelleMagasin__c</fullName>
    <externalId>true</externalId>
    <label>Magasin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleRegion__c.field-meta.xml
<CustomField>
    <fullName>libelleRegion__c</fullName>
    <label>Région</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_SectorisationUtils.cls
@isTest
private class Test_SectorisationUtils {

   static testMethod void test() {
     List<Sectorisation__c> insertedSectorisations = new List<Sectorisation__c>();
     for (Integer i = 0; i < 100; i++)
       insertedSectorisations.add(new Sectorisation__c(iris__c               = 'Iris' + i,
                                                       codeMagasin__c        = 'MAG' + i,
                                                       libelleMagasin__c     = 'Magasin ' + i,
                                                       codeDV__c             = 'DV' + i,
                                                       libelleDV__c          = 'Direction des ventes ' + i,
                                                       codeRegion__c         = 'DR' + i,
                                                       libelleRegion__c      = 'Région ' + i,
                                                       codeDepot__c          = 'DEP' + i,
                                                       libelleDepot__c       = 'Dépôt ' + i,
                                                       codeDS__c             = 'DS' + i,
                                                       libelleDS__c          = 'Direction service ' + i));
     insert insertedSectorisations;

     Test.startTest();

     Integer count0 = [SELECT count() FROM Sectorisation__c];
     SectorisationUtils.OrganisationKpark org0 = SectorisationUtils.getOrganisation();
     System.debug('count0 : ' + count0);
     System.debug('org0.magasins.size() : ' + org0.magasins.size());
     System.assertEquals(count0, org0.magasins.size());

     Test.stopTest();
   }
}