force-app/main/default/objects/CreditMemo__c/CreditMemo__c.object-meta.xml
<CustomObject>
    <description>Gestion des avoirs basée sur la modélisation des avoirs du modules Salesforce Billing</description>
    <label>Avoir</label>
    <nameField>
        <displayFormat>AVR/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de l’avoir</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avoirs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditMemo__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/billingAccount__c.field-meta.xml
<CustomField>
    <fullName>billingAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Compte facturé</description>
    <label>Compte de facturation</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PersonalAccount</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BusinessAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>CustomerCreditMemos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/creditMemoDate__c.field-meta.xml
<CustomField>
    <fullName>creditMemoDate__c</fullName>
    <label>Date de l&apos;avoir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/creditMemoReference__c.field-meta.xml
<CustomField>
    <fullName>creditMemoReference__c</fullName>
    <externalId>true</externalId>
    <label>Référence de l’avoir</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>CreditMemos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/pretaxAmount__c.field-meta.xml
<CustomField>
    <fullName>pretaxAmount__c</fullName>
    <label>Montant (HT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <defaultValue>&apos;Brouillon&apos;</defaultValue>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Publié</fullName>
            </value>
            <value>
                <fullName>Acquitté</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TR022_CreditMemo.cls
//-- -------------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR022_CreditMemo
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 18/11/2022
//-- Version     : 1.0
//-- 
//-- -------------------------------------------------------------------------------------- --
public class TR022_CreditMemo {
        
    /**
    * @description Méthode pour mettre à jour le montant sur les commandes lorsqu'un avoir est validé (comptabilisé)
    * @param userContext contexte utilisateur
    */
    public static void updateOrderAfterValidation(UserContext userContext) {
        System.debug('### DEBUT TR022_CreditMemo.updateOrderAfterValidation');
        
        List<CreditMemo__c> newCreditMemos = (List<CreditMemo__c>)Trigger.new;
        Map<Id, CreditMemo__c> oldCreditMemos = (Map<Id, CreditMemo__c>)Trigger.oldMap; 
        List<String> customerOrderIds = new List<String>();
        List<Order> customerOrdertoUp = new List<Order>();

        for(CreditMemo__c newCreditMemo : newCreditMemos) {
            CreditMemo__c oldCreditMemo = oldCreditMemos == null ? null : oldCreditMemos.get(newCreditMemo.id);
            // Récupération avoirs comptabilisées
            if(Trigger.isUpdate && oldCreditMemo != null && String.isNotBlank(newCreditMemo.creditMemoReference__c) 
                && String.isNotBlank(newCreditMemo.customerOrder__c)
                && (oldCreditMemo.creditMemoReference__c != newCreditMemo.creditMemoReference__c || oldCreditMemo.status__c != newCreditMemo.status__c)
            ) {
                System.debug('## CreditMemo Id: '+newCreditMemo.Id);
                customerOrderIds.add(newCreditMemo.customerOrder__c);
            }
        }

        // Somme du montant des avoirs des commandes
        if(!customerOrderIds.isEmpty()) {
            for (AggregateResult result : [SELECT customerOrder__c, SUM(amount__c) totalAmount FROM CreditMemo__c 
                                                WHERE customerOrder__c IN :customerOrderIds AND creditMemoReference__c != null 
                                                AND status__c != :Constants.CREDITMEMO_ANNULE
                                                GROUP BY customerOrder__c]) {
                System.debug('## MAJ Order Id: '+result.get('customerOrder__c'));
                System.debug('## Total Amount: '+result.get('totalAmount'));
                // Mise à jour de la commande
                customerOrdertoUp.add(new Order(
                    Id = (String)result.get('customerOrder__c'),
                    creditMemosAmount__c = (Decimal)result.get('totalAmount') 
                ));
            }

            for(String customerOrderId : customerOrderIds){
                Boolean amountCorrectlyCalculated = false;
                for(Order o : customerOrdertoUp){
                    if(o.Id == customerOrderId){
                        amountCorrectlyCalculated = true;
                    }
                }
                if(!amountCorrectlyCalculated){
                    customerOrdertoUp.add(new Order(
                        Id = customerOrderId,
                        creditMemosAmount__c = 0
                    ));
                }
            }

            if(!customerOrdertoUp.isEmpty()) {
                update customerOrdertoUp;
            }
        }
        System.debug('### FIN TR022_CreditMemo.updateOrderAfterValidation');
    }
        
    /**
    * @description Méthode pour mettre à jour le montant sur les comptes lorsqu'un avoir est validé (comptabilisé)
    * @param userContext contexte utilisateur
    */
    public static void updateAccountAfterValidation(UserContext userContext) {
        System.debug('### DEBUT TR022_CreditMemo.updateAccountAfterValidation');
        
        List<CreditMemo__c> newCreditMemos = (List<CreditMemo__c>)Trigger.new;
        Map<Id, CreditMemo__c> oldCreditMemos = (Map<Id, CreditMemo__c>)Trigger.oldMap; 
        List<String> accountIds = new List<String>();
        List<Account> accountToUp = new List<Account>();

        for(CreditMemo__c newCreditMemo : newCreditMemos) {
            CreditMemo__c oldCreditMemo = oldCreditMemos == null ? null : oldCreditMemos.get(newCreditMemo.id);
            // Récupération avoirs comptabilisées
            if(Trigger.isUpdate && oldCreditMemo != null && String.isNotBlank(newCreditMemo.creditMemoReference__c) 
                && String.isNotBlank(newCreditMemo.billingaccount__c)
                && (oldCreditMemo.creditMemoReference__c != newCreditMemo.creditMemoReference__c || oldCreditMemo.status__c != newCreditMemo.status__c)
            ) {
                System.debug('## CreditMemo Id: '+newCreditMemo.Id);
                accountIds.add(newCreditMemo.billingaccount__c);
            }
        }

        // Somme du montant des avoirs des comptes
        if(!accountIds.isEmpty()) {
            for (AggregateResult result : [SELECT billingaccount__c, SUM(amount__c) totalAmount FROM CreditMemo__c 
                                                WHERE billingaccount__c IN :accountIds AND creditMemoReference__c != null 
                                                AND status__c != :Constants.CREDITMEMO_ANNULE
                                                GROUP BY billingaccount__c]) {
                System.debug('## MAJ Account Id: '+result.get('billingaccount__c'));
                System.debug('## Total Amount: '+result.get('totalAmount'));
                // Mise à jour du compte
                accountToUp.add(new Account(
                    Id = (String)result.get('billingaccount__c'),
                    creditMemosAmount__c = (Decimal)result.get('totalAmount') 
                ));
            }

            for(String accountId : accountIds){
                Boolean amountCorrectlyCalculated = false;
                for(Account a : accountToUp){
                    if(a.Id == accountId){
                        amountCorrectlyCalculated = true;
                    }
                }
                if(!amountCorrectlyCalculated){
                    accountToUp.add(new Account(
                        Id = accountId,
                        creditMemosAmount__c = 0
                    ));
                }
            }

            if(!accountToUp.isEmpty()) {
                update accountToUp;
            }
        }
        System.debug('### FIN TR022_CreditMemo.updateAccountAfterValidation');
    }
 
    /**
    * @description Méthode pour exécuter la classe QA_KMDCEinstein
    * @param userContext contexte utilisateur
    */
    public static void scheduleKMDCEinstein(UserContext userContext) {
        System.debug('### DEBUT TR022_CreditMemo.scheduleKMDCEinstein');
        
        List<CreditMemo__c> newCreditMemos = (List<CreditMemo__c>)Trigger.new;
        Map<Id, CreditMemo__c> oldCreditMemos = (Map<Id, CreditMemo__c>)Trigger.oldMap; 
        List<CreditMemo__c> credMemoToUpdate = new List<CreditMemo__c>();

        for(CreditMemo__c newCreditMemo : newCreditMemos) {
            CreditMemo__c oldCreditMemo = oldCreditMemos == null ? null : oldCreditMemos.get(newCreditMemo.id);
            // Récupération avoirs comptabilisées
            if(Trigger.isUpdate && oldCreditMemo != null && String.isNotBlank(newCreditMemo.creditMemoReference__c) && 
                (oldCreditMemo.creditMemoDate__c != newCreditMemo.creditMemoDate__c 
                    || oldCreditMemo.pretaxAmount__c != newCreditMemo.pretaxAmount__c 
                    || oldCreditMemo.amount__c != newCreditMemo.amount__c 
                )
            ) {
                System.debug('## CreditMemo Id: '+newCreditMemo.Id);
                credMemoToUpdate.add(newCreditMemo);
            }
        }

        if(!credMemoToUpdate.isEmpty()) {
            System.enqueueJob(new QA_KMDCEinstein('CreditMemo', credMemoToUpdate, null, null)); // Alimentation KMDC pour einstein
        }
        System.debug('### FIN TR022_CreditMemo.scheduleKMDCEinstein');
    }
}