force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/anneeConstruction__c.field-meta.xml
<CustomField>
    <fullName>anneeConstruction__c</fullName>
    <label>Année de construction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NSP</fullName>
            </value>
            <value>
                <fullName>Avant 1940</fullName>
            </value>
            <value>
                <fullName>1950</fullName>
            </value>
            <value>
                <fullName>1960</fullName>
            </value>
            <value>
                <fullName>1970</fullName>
            </value>
            <value>
                <fullName>1980</fullName>
            </value>
            <value>
                <fullName>1990</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2010+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreLocataire__c.field-meta.xml
<CustomField>
    <fullName>autreLocataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre locataire)</relationshipLabel>
    <relationshipName>autreLocataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreOccupant__c.field-meta.xml
<CustomField>
    <fullName>autreOccupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre occupant)</relationshipLabel>
    <relationshipName>autreOccupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreProprietaire__c.field-meta.xml
<CustomField>
    <fullName>autreProprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre propriétaire)</relationshipLabel>
    <relationshipName>autreProprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/codePostal__c.field-meta.xml
<CustomField>
    <fullName>codePostal__c</fullName>
    <label>Code postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/iris__c.field-meta.xml
<CustomField>
    <fullName>iris__c</fullName>
    <label>Iris</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/locataire__c.field-meta.xml
<CustomField>
    <fullName>locataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du propriétaire</inlineHelpText>
    <label>Locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Locataire)</relationshipLabel>
    <relationshipName>locataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/occupant__c.field-meta.xml
<CustomField>
    <fullName>occupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du locataire</inlineHelpText>
    <label>Occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Occupant)</relationshipLabel>
    <relationshipName>occupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/pays__c.field-meta.xml
<CustomField>
    <fullName>pays__c</fullName>
    <label>Pays</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/proprietaire__c.field-meta.xml
<CustomField>
    <fullName>proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire)</relationshipLabel>
    <relationshipName>proprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/sectorisation__c.field-meta.xml
<CustomField>
    <fullName>sectorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sectorisation</label>
    <referenceTo>Sectorisation__c</referenceTo>
    <relationshipLabel>Chantiers</relationshipLabel>
    <relationshipName>sectorisationChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/typeHabitation__c.field-meta.xml
<CustomField>
    <fullName>typeHabitation__c</fullName>
    <label>Type d&apos;habitation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pavillon</fullName>
            </value>
            <value>
                <fullName>Appartement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/typeResidence__c.field-meta.xml
<CustomField>
    <fullName>typeResidence__c</fullName>
    <label>Type de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Secondaire</fullName>
            </value>
            <value>
                <fullName>Locative</fullName>
            </value>
            <value>
                <fullName>Professionnelle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/ville__c.field-meta.xml
<CustomField>
    <fullName>ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/KContrat__c/KContrat__c.object-meta.xml
<CustomObject>
    <label>Contrat (K)</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats (K)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KContrat__c/fields/chantier__c.field-meta.xml
<CustomField>
    <fullName>chantier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Client chantier du contrat</description>
    <label>Chantier</label>
    <referenceTo>Chantier__c</referenceTo>
    <relationshipLabel>Contrats (K)</relationshipLabel>
    <relationshipName>chantierContrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/DateEnvoiAvisTrustpilot__c.field-meta.xml
<CustomField>
    <fullName>DateEnvoiAvisTrustpilot__c</fullName>
    <description>Date à laquelle une demande d&apos;avis sur le contrat (questionnaire Trustpilot) a été envoyée au client</description>
    <label>Date d&apos;envoi de l&apos;avis Trustpilot</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/dateReponseQuestionnaire__c.field-meta.xml
<CustomField>
    <fullName>dateReponseQuestionnaire__c</fullName>
    <description>Date de saisie du questionnaire de satisfaction par le client</description>
    <label>Date réponse questionnaire</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/debutDernierSAV__c.field-meta.xml
<CustomField>
    <fullName>debutDernierSAV__c</fullName>
    <description>Date de déclaration du dernier dossier SAV</description>
    <label>Création du dernier dossier SAV</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/libelleStatutContrat__c.field-meta.xml
<CustomField>
    <fullName>libelleStatutContrat__c</fullName>
    <description>Statut du contrat</description>
    <externalId>true</externalId>
    <label>Statut du contrat</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/NPSSatisfaction__c.field-meta.xml
<CustomField>
    <fullName>NPSSatisfaction__c</fullName>
    <label>NPS Satisfaction</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/numeroContrat__c.field-meta.xml
<CustomField>
    <fullName>numeroContrat__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Numéro de contrat</description>
    <externalId>true</externalId>
    <label>N° contrat</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sectorisation__c/Sectorisation__c.object-meta.xml
<CustomObject>
    <label>Sectorisation</label>
    <nameField>
        <label>Nom de Sectorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sectorisation__c/fields/codeDV__c.field-meta.xml
<CustomField>
    <fullName>codeDV__c</fullName>
    <label>Code DV</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/codeMagasin__c.field-meta.xml
<CustomField>
    <fullName>codeMagasin__c</fullName>
    <label>Code magasin</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/IRIS__c.field-meta.xml
<CustomField>
    <fullName>IRIS__c</fullName>
    <externalId>true</externalId>
    <label>IRIS</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleDV__c.field-meta.xml
<CustomField>
    <fullName>libelleDV__c</fullName>
    <label>DV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleMagasin__c.field-meta.xml
<CustomField>
    <fullName>libelleMagasin__c</fullName>
    <externalId>true</externalId>
    <label>Magasin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_Schedule_Trustpilot.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_Schedule_Trustpilot
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 20/09/2021
//-- Version     : 1.0
//-- * Init
//-- --------------------------------------------------------------------------------- --
@isTest
private class Test_Schedule_Trustpilot {
    private static final Id rtB2C = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PERSO_RT);
    private static final Id rtActiviteCommerciale = DAL.getRecordTypeIdByDevName('Event', Constants.ACTIVITE_COMMERCIALE_RT);

    @isTest static void testKContrat() {
         
        User user = getUser();
        update user;

        System.runAs(user) {
            Utils_Test.createGlobalProperties(true, 17, true, true, true, 30, 10, true);
            Utils_Test.createSectorisation();

            PropertiesUtils.setStringValue('trustpilot.api.apikey', '2PPGjGhXllss8niG0AGYsJhGaC4mPGCo');
            PropertiesUtils.setStringValue('trustpilot.api.businessUnitId', '59c8fb8c0000ff0005abfef7');
            PropertiesUtils.setIntegerValue('trustpilot.api.nbReviewPerPage', 20);
            PropertiesUtils.setStringValue('trustpilot.api.password', 'test');
            PropertiesUtils.setStringValue('trustpilot.api.username', 'test');
                    
            // Récupération des types d'enregistrement
            Id accRecordType = DAL.getRecordTypeIdByDevName(Constants.ACCOUNT_PERSO_RT);
            
            // Création d'un compte
            Account account = Utils_Test.createAccount('Test', 'test', 'testespaceclient@salesforce.com', accRecordType, 'Client', 'FAX', true);
            
            // Création d'un chantier        
            Chantier__c chantier = Utils_Test.createChantier('Chantier 1', account.Id, true);

            // Création d'un projet
            Opportunity opp = Utils_Test.createOpportunity(account, chantier, true);
            
            // Création d'un contrat
            KContrat__c contratMetrage = Utils_Test.createContrat('Contrat Metrage', chantier.Id, account.Id, '0002', true);

            contratMetrage.DateEnvoiAvisTrustpilot__c = null;
            contratMetrage.dateReponseQuestionnaire__c = System.today().addDays(-7);
            contratMetrage.NPSSatisfaction__c = 9;
            contratMetrage.libelleStatutContrat__c = 'Solde';
            contratMetrage.numeroContrat__c = 'CNT/22222221';
            contratMetrage.debutDernierSAV__c = null;
    
            update contratMetrage;

            System.debug('contratMetrage.DateEnvoiAvisTrustpilot__c : '+contratMetrage.DateEnvoiAvisTrustpilot__c);
            System.debug('contratMetrage.dateReponseQuestionnaire__c : '+contratMetrage.dateReponseQuestionnaire__c);
            System.debug('contratMetrage.NPSSatisfaction__c : '+contratMetrage.NPSSatisfaction__c);
            System.debug('contratMetrage.libelleStatutContrat__c : '+contratMetrage.libelleStatutContrat__c);
            System.debug('contratMetrage.numeroContrat__c : '+contratMetrage.numeroContrat__c);
            System.debug('contratMetrage.debutDernierSAV__c : '+contratMetrage.debutDernierSAV__c);

            Test.startTest();
            Database.executeBatch(new BA_TrustPilot_SendNewSoldContrats());
            

            contratMetrage.DateEnvoiAvisTrustpilot__c = Date.today();

            Database.executeBatch(new BA_TrustPilot_GetReactionsCreateCases());

            Schedule_TrustPilot_SendNewSoldContrats schedule = new Schedule_TrustPilot_SendNewSoldContrats();
            String jobId = system.schedule('Test Test_Schedule_TrustPilot_SendContrats', '0 0 23 * * ?', schedule);

            Schedule_TrustPilot_GetReactions schedule2 = new Schedule_TrustPilot_GetReactions();
            String jobId2 = system.schedule('Test Test_Schedule_TrustPilot_GetReactions', '0 0 23 * * ?', schedule2);

            Test.stopTest();

            List<Case> caseResultList = new List<Case>();
            caseResultList = [SELECT Id, AccountId, ContactId, Chantier__c, numeroContrat__c, trustpilotReviewID__c,
                                    Subject, Origin, source__c, Status, Description
                                FROM Case];
            System.debug('caseResultList : '+caseResultList);

            if(!caseResultList.isEmpty()){
                CaseComment newCaseComment = new CaseComment(
                                                                CommentBody = 'Test',
                                                                ParentId = caseResultList[0].Id
                                                            );
                insert newCaseComment;
            }
        }
    }

    private static Chantier__c createChantier(Account proprietaire, Account autreProprietaire, Account locataire, Account autreLocataire, 
                                             Account occupant, Account autreOccupant, Sectorisation__c defaultSectorisation) {
       Chantier__c chantier = new Chantier__c();

       chantier.name = 'CHA - Test';

       chantier.codePostal__c = '76320';
       chantier.ville__c = 'Saint-Pierre les Elbeuf';
       chantier.pays__c = 'F';
       chantier.anneeConstruction__c = '2000';
       chantier.typeHabitation__c = 'Pavillon';
       chantier.typeResidence__c = 'Principale';

       if (proprietaire != null)
         chantier.proprietaire__c = proprietaire.id;
       if (autreProprietaire != null)
         chantier.autreProprietaire__c = autreProprietaire.id;
       if (locataire != null)
         chantier.locataire__c = locataire.id;
       if (autreLocataire != null)
         chantier.autreLocataire__c = autreLocataire.id;
       if (occupant != null)
         chantier.occupant__c = occupant.id;
       if (autreOccupant != null)
         chantier.autreOccupant__c = autreOccupant.id;

       chantier.Localisation__Latitude__s = 0;
       chantier.Localisation__Longitude__s = 0;
       chantier.iris__c = defaultSectorisation.iris__c;

      System.assertNotEquals(null, chantier.iris__c);

      return chantier;
    }
   

    private static User getUser() {
      UserContext context = UserContext.getContext();
      User user = context.getUser();
      if (StringUtils.isEmpty(user.codeMagasin__c))
        user.codeMagasin__c = 'MAG0000';
      if (StringUtils.isEmpty(user.libelleMagasin__c))
        user.codeMagasin__c = 'Magasin 0000';
      if (StringUtils.isEmpty(user.codeDV__c))
        user.codeMagasin__c = 'DV0000';
      if (StringUtils.isEmpty(user.libelleDV__c))
        user.codeMagasin__c = 'DV 0000';
      if (StringUtils.isEmpty(user.codeDR__c))
        user.codeMagasin__c = 'DV0000';
      if (StringUtils.isEmpty(user.libelleDR__c))
        user.codeMagasin__c = 'DV 0000';
      return user;
    }
}