force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/autreProprietaire__c.field-meta.xml
<CustomField>
    <fullName>autreProprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre propriétaire)</relationshipLabel>
    <relationshipName>autreProprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/codePostal__c.field-meta.xml
<CustomField>
    <fullName>codePostal__c</fullName>
    <label>Code postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/complementAdresse__c.field-meta.xml
<CustomField>
    <fullName>complementAdresse__c</fullName>
    <inlineHelpText>Informations affichées comme 2nd ligne sur l’adresse postale.
Résidence, bâtiment, zone, etc.</inlineHelpText>
    <label>Complément d&apos;adresse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/etage__c.field-meta.xml
<CustomField>
    <fullName>etage__c</fullName>
    <label>Etage</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/proprietaire__c.field-meta.xml
<CustomField>
    <fullName>proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire)</relationshipLabel>
    <relationshipName>proprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/rue__c.field-meta.xml
<CustomField>
    <fullName>rue__c</fullName>
    <label>Rue</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/ville__c.field-meta.xml
<CustomField>
    <fullName>ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/classes/TR001_Dedoublonnage.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR001_Dedoublonnage
//-- Modifié par : SOPRA STERIA - Julien Morineau
//-- Modifié le  : 19/07/2018
//-- Version     : 1.2
//-- * 1.2 : KPKCRM_RQM-13 : Optimisation et historique des batchs
//-- * 1.1 : Gestion de la synchronisation des comptes via batch (CRM-954)
//-- --------------------------------------------------------------------------------- --
public without sharing class TR001_Dedoublonnage {
    private static final Boolean DQE_SYNCHRO = PropertiesUtils.getBooleanValue('dqe.dedup.sync.enabled', true);

    /**
    * @description Passerelle entre les déclencheurs des objets et l'appel Webservice DQE
    * @param userContext Context utilisateur
    * @param objecttype Type de l'objet (Account ou Chantier__c)
    * @param actionType Type de l'action (Add, Update, Delete)
    */
    public static void enqueueDedoublonnageJob(UserContext userContext, String objectType, String actionType) {  
        system.debug('### DEBUT TR001_Dedoublonnage.enqueueDedoublonnageJob');      
        if (!Trigger.isExecuting)
            return;     

        List<SObject> objectToUpdate = new List<SObject>();
        List<SObject> newObjects = new List<SObject>();
        
        // Traitement selon le type de déclencheur
        if (Trigger.isAfter && Trigger.isDelete)
            objectToUpdate=(List<SObject>)Trigger.old;
        // JMU 23/09/2016 - Correction du bug impliquant Signea
        else if(Trigger.isUpdate){
            if(objectType.equalsIgnoreCase('Account')){
                for (Account newTrig : (List<Account>)Trigger.new){
                    Map<Id, Account> oldAccounts = (Map<Id, Account>)Trigger.oldMap;
                    Account oldTrig = oldAccounts == null ? null : oldAccounts.get(newTrig.id);
                    if(oldTrig.codePostal__c != newTrig.codePostal__c || oldTrig.LastName != newTrig.LastName || oldTrig.FirstName != newTrig.FirstName 
                                || oldTrig.rue__c != newTrig.rue__c || oldTrig.ville__c != newTrig.ville__c || oldTrig.PersonEmail != newTrig.PersonEmail
                                || oldTrig.PersonHomePhone != newTrig.PersonHomePhone || oldTrig.PersonMobilePhone != newTrig.PersonMobilePhone
                                || oldTrig.Name != newTrig.Name || oldTrig.Phone != newTrig.Phone || oldTrig.Fax != newTrig.Fax){
                    
                        objectToUpdate.add(newTrig);
                    }
                }
            } else if(objectType.equalsIgnoreCase('Chantier')){
                for (Chantier__c newTrig : (List<Chantier__c>)Trigger.new){
                    Map<Id, Chantier__c> oldChantiers = (Map<Id, Chantier__c>)Trigger.oldMap;
                    Chantier__c oldTrig = oldChantiers == null ? null : oldChantiers.get(newTrig.id);
                    if(oldTrig.proprietaire__c != newTrig.proprietaire__c || oldTrig.autreProprietaire__c != newTrig.autreProprietaire__c
                                || oldTrig.codePostal__c != newTrig.codePostal__c || oldTrig.rue__c != newTrig.rue__c || oldTrig.ville__c != newTrig.ville__c 
                                || oldTrig.complementAdresse__c != newTrig.complementAdresse__c || oldTrig.etage__c != newTrig.etage__c){
                    
                        objectToUpdate.add(newTrig);
                    }
                }
            }
        }
        else
            objectToUpdate=(List<SObject>)Trigger.new;

        if(objectToUpdate.isEmpty())
            return;
        
        // Evite les appels multiples pour le même objet
        for (SObject obj : objectToUpdate) {
            if (!AlreadyUsed.isUsed('TR001_Dedoublonnage.enqueueJob', obj.Id)) {
                newObjects.add(obj);
            }
        }
        if (newObjects.isEmpty())
            return;

        // Appel à la classe Queueable correspondant à l'objet et à l'action envoyés en paramètres
        if(DQE_SYNCHRO && (Limits.getQueueableJobs() < Limits.getLimitQueueableJobs())){
            system.debug('## MAJ DQE Dedup: '+ newObjects);
            system.debug('## Type d\'action: '+actionType+' - Type d\'objet: '+objectType);
            // Account
            if(objectType.equalsIgnoreCase('Account')){
                System.enqueueJob(new QA_DQEAccount(newObjects,actionType,false,null));
            // Chantier
            } else if(objectType.equalsIgnoreCase('Chantier')){
                System.enqueueJob(new QA_DQEChantier(newObjects, actionType,false,null));
            }
        }
        system.debug('### FIN TR001_Dedoublonnage.enqueueDedoublonnageJob');      
    }
}