force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/heatingMode__c.field-meta.xml
<CustomField>
    <fullName>heatingMode__c</fullName>
    <label>Mode de chauffe principal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>heatingModes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/sectorisation__c.field-meta.xml
<CustomField>
    <fullName>sectorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sectorisation</label>
    <referenceTo>Sectorisation__c</referenceTo>
    <relationshipLabel>Chantiers</relationshipLabel>
    <relationshipName>sectorisationChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/CustomProductPictogram__c/CustomProductPictogram__c.object-meta.xml
<CustomObject>
    <description>Objet permettant de stocker les URL pour les pictogrammes personnalisés des produits</description>
    <label>Pictogramme personnalisé</label>
    <nameField>
        <displayFormat>CPP/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pictogrammes personnalisés</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomProductPictogram__c/fields/leaf__c.field-meta.xml
<CustomField>
    <fullName>leaf__c</fullName>
    <label>Nombre de vantaux</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>NbVantaux</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomProductPictogram__c/fields/pictogramFileLink__c.field-meta.xml
<CustomField>
    <fullName>pictogramFileLink__c</fullName>
    <label>Lien vers le fichier picto</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CustomProductPictogram__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pictogrammes personnalisés</relationshipLabel>
    <relationshipName>Pictogrammes_personnalises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomProductPictogram__c/fields/productOptionLevel1__c.field-meta.xml
<CustomField>
    <fullName>productOptionLevel1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code option niveau 1</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pictogrammes personnalisés (Code option niveau 1)</relationshipLabel>
    <relationshipName>Pictogrammes_personnalis_s</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomProductPictogram__c/fields/productOptionLevel2__c.field-meta.xml
<CustomField>
    <fullName>productOptionLevel2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code option niveau 2</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pictogrammes personnalisés (Code option niveau 2)</relationshipLabel>
    <relationshipName>Pictogrammes_personnalis_s1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomProductPictogram__c/fields/productOptionLevel3__c.field-meta.xml
<CustomField>
    <fullName>productOptionLevel3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code option niveau 3</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pictogrammes personnalisés (Code option niveau 3)</relationshipLabel>
    <relationshipName>Pictogrammes_personnalis_s2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomProductPictogram__c/fields/productOptionLevel4__c.field-meta.xml
<CustomField>
    <fullName>productOptionLevel4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code option niveau 4</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pictogrammes personnalisés (Code option niveau 4)</relationshipLabel>
    <relationshipName>Pictogrammes_personnalis_s3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GlobalProperties__c/GlobalProperties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Propriétés globales</label>
</CustomObject>

force-app/main/default/objects/GlobalProperties__c/fields/actif__c.field-meta.xml
<CustomField>
    <fullName>actif__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Actif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GlobalProperties__c/fields/stringValue__c.field-meta.xml
<CustomField>
    <fullName>stringValue__c</fullName>
    <label>Texte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencial__c/Referencial__c.object-meta.xml
<CustomObject>
    <description>Objet contenant le référentiel de KparK (Documents, MF, CGV, autre etc...)</description>
    <label>Référentiel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencial__c/fields/category__c.field-meta.xml
<CustomField>
    <fullName>category__c</fullName>
    <label>Catégorie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SourceCategory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/image__c.field-meta.xml
<CustomField>
    <fullName>image__c</fullName>
    <label>Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/KparKReference__c.field-meta.xml
<CustomField>
    <fullName>KparKReference__c</fullName>
    <description>Référence interne unique à K par K</description>
    <externalId>true</externalId>
    <label>Référence</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Champ pour stocké les produits</description>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Caractéristiques produits</relationshipLabel>
    <relationshipName>ReferencialProductsFeatures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referencial__c/recordTypes/CustomerCancellationReason.recordType-meta.xml
<RecordType>
    <fullName>CustomerCancellationReason</fullName>
    <active>true</active>
    <label>Motif d&apos;annulation client</label>
</RecordType>

force-app/main/default/objects/Sectorisation__c/Sectorisation__c.object-meta.xml
<CustomObject>
    <label>Sectorisation</label>
    <nameField>
        <label>Nom de Sectorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_LWC_QuoteCPQGeneratePDF.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_LWC_QuoteCPQGeneratePDF
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 16/08/2021
//-- Version     : 1.0
//-- Description : Classe de tests de LWC_QuoteCPQGeneratePDF
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
@isTest
private with sharing class Test_LWC_QuoteCPQGeneratePDF {
     //omar
     // Mock class to simulate callout response
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            // Add desired mock response body as required
            res.setBody('mock_response_body');
            return res;
        }
    }

	@testSetup 
    static void setup() {
        Id accPersoRT = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PERSO_RT);
        Id RTDevNameReferencial = DAL.getRecordTypeIdByDevName('Referencial__c', 'CustomerCancellationReason');
       
        Account accountTest = Utils_Test.createAccount('name', 'name', 'test@test.fr', accPersoRT, null, 'Email', true);
        
        Sectorisation__c secto = Utils_Test.createSectorisation('123456', '12345', 'nomMag', '12345', 'nomDepot', '12345', 'nomCom', true);

        Chantier__c chantier = Utils_Test.createChantier('Chantier 1', accountTest.Id,false);
        chantier.sectorisation__c=secto.Id;
        chantier.heatingMode__c='Collectif';
        insert chantier;

        Opportunity opp = Utils_Test.createOpportunity('name', accountTest, null, chantier, true);
        
        PropertiesUtils.setStringValue('ref.motifAnnulationKparK.code','RSL-0016');

        Referencial__c ref = Utils_Test.createReferencial('ref','ref', Date.today(), Date.today(), RTDevNameReferencial, false, false, false, false, false);
        ref.KparKReference__c= PropertiesUtils.getStringValue('ref.motifAnnulationKparK.code', 'RSL-0016');
        insert ref;

        SBQQ__Quote__c cpqQuote = Utils_Test.createCPQQuote(opp,Date.today(),1, true);
        SBQQ__QuoteLine__c cpqQuoteLine = Utils_Test.createCPQQuoteLineItem(cpqQuote.Id ,100, 100, 1,true);
        
        ContentDocumentLink cdl = Utils_Test.createFile('test', cpqQuoteLine.Id, Blob.valueOf('content'), true);
        Id contentVer = [SELECT ContentDocumentId FROM ContentVersion LIMIT 1].Id;
        ContentDistribution cdistrib = Utils_Test.createContentDistribution('test', contentVer, true);
    }

    @isTest
    static void testRenderQuoteDocumentPDF() {
        // Fetch the quote record ID
    	SBQQ__Quote__c cpqQuoteTest = [SELECT Id FROM SBQQ__Quote__c LIMIT 1];

    	// Setting the mock callout
    	Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    

        // Setting the mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        // Start Test
        Test.startTest();
        
        // Call your method
        Id quoteId = cpqQuoteTest.Id;
        String result = LWC_QuoteCPQGeneratePDF.renderQuoteDocumentPDF(quoteId, 'testFilename.pdf', 'DIP');
        
        Test.stopTest();
        
        // Now, write assertions to check the expected behavior
        System.assertNotEquals(null, result, 'The result should not be null');
    }
    
    
    
    
    
    
    //omar
    
    
    
    
    

    @isTest
    private static void testRenderDIP(){
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        User userSales = Utils_Test.createUser(false,'Sales1', 'sales1@test.remvrp.com', 'sal','es', null, null);
        System.runAs(user){
            String idUser = userSales.Id;
            GlobalProperties__c properties = new GlobalProperties__c(name = 'signea.package.ownerId', actif__c = true, stringValue__c = idUser);
            insert properties;
            Test.startTest();
            LWC_QuoteCPQGeneratePDF.QuoteObject qo = new LWC_QuoteCPQGeneratePDF.QuoteObject();
            LWC_QuoteCPQGeneratePDF.QuoteLineObject glo = new LWC_QuoteCPQGeneratePDF.QuoteLineObject();
            SBQQ__Quote__c cpqQuote = [SELECT ID FROM SBQQ__Quote__c LIMIT 1];
            
            LWC_QuoteCPQGeneratePDF.renderQuoteDocumentPDF(cpqQuote.Id, 'test', 'DIP');
            Blob blobDIPC = LWC_QuoteCPQGeneratePDF.renderQuoteDocumentPDFBlob(cpqQuote.Id, 'test', 'DIP');
            LWC_QuoteCPQGeneratePDF.linkDocumentToRecordForSignea(cpqQuote.Id, 'test', blobDIPC, 'DIP');

            Test.stopTest();
        }
    }

    @isTest
    private static void testRenderContrat(){
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        User userSales = Utils_Test.createUser(false,'Sales1', 'sales1@test.remvrp.com', 'sal','es', null, null);
        System.runAs(user){
            String idUser = userSales.Id;
            GlobalProperties__c properties = new GlobalProperties__c(name = 'signea.package.ownerId', actif__c = true, stringValue__c = idUser);
            insert properties;
            Test.startTest();
            LWC_QuoteCPQGeneratePDF.QuoteObject qo = new LWC_QuoteCPQGeneratePDF.QuoteObject();
            LWC_QuoteCPQGeneratePDF.QuoteLineObject glo = new LWC_QuoteCPQGeneratePDF.QuoteLineObject();
            SBQQ__Quote__c cpqQuote = [SELECT ID FROM SBQQ__Quote__c LIMIT 1];

            LWC_QuoteCPQGeneratePDF.renderQuoteDocumentPDF(cpqQuote.Id, 'test', 'Contrat');
            Blob blobDIPC = LWC_QuoteCPQGeneratePDF.renderQuoteDocumentPDFBlob(cpqQuote.Id, 'test', 'Contrat');
            LWC_QuoteCPQGeneratePDF.linkDocumentToRecordForSignea(cpqQuote.Id, 'test', blobDIPC, 'Contrat');

            Test.stopTest();
        }
    }

    @isTest
    private static void testAlreadyDocument(){
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        User userSales = Utils_Test.createUser(false,'Sales1', 'sales1@test.remvrp.com', 'sal','es', null, null);
        System.runAs(user){
            String idUser = userSales.Id;
            GlobalProperties__c properties = new GlobalProperties__c(name = 'signea.package.ownerId', actif__c = true, stringValue__c = idUser);
            insert properties;
            Test.startTest();
            LWC_QuoteCPQGeneratePDF.QuoteObject qo = new LWC_QuoteCPQGeneratePDF.QuoteObject();
            LWC_QuoteCPQGeneratePDF.QuoteLineObject glo = new LWC_QuoteCPQGeneratePDF.QuoteLineObject();
            SBQQ__Quote__c cpqQuote = [SELECT ID FROM SBQQ__Quote__c LIMIT 1];
            
            ContentDocumentLink cdl = Utils_Test.createFile('test', cpqQuote.Id, Blob.valueOf('content'), true);
            ContentVersion contentVer = [SELECT Id, category__c FROM ContentVersion LIMIT 1];
            contentVer.category__c = 'Contrat';
            update contentVer;

            LWC_QuoteCPQGeneratePDF.renderQuoteDocumentPDF(cpqQuote.Id, 'test', 'Contrat');

            Test.stopTest();
        }
    }

    @isTest
    private static void testConstructWarrantiesMap(){
        Test.startTest();
        //(String categorie, String libelle, Decimal duration, Map<String, List<WarrantyObject>> warrantiesMap)
        LWC_QuoteCPQGeneratePDF.constructWarrantiesMap('cat','lib',0.5, new Map<String, List<LWC_QuoteCPQGeneratePDF.WarrantyObject>>());
        Test.stopTest();
    }

    @isTest
    private static void testCustomPictograms(){
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        User userSales = Utils_Test.createUser(false,'Sales1', 'sales1@test.remvrp.com', 'sal','es', null, null);
        System.runAs(user){
            String idUser = userSales.Id;
            GlobalProperties__c properties = new GlobalProperties__c(name = 'signea.package.ownerId', actif__c = true, stringValue__c = idUser);
            insert properties;
            Test.startTest();
            LWC_QuoteCPQGeneratePDF.QuoteObject qo = new LWC_QuoteCPQGeneratePDF.QuoteObject();
            LWC_QuoteCPQGeneratePDF.QuoteLineObject glo = new LWC_QuoteCPQGeneratePDF.QuoteLineObject();
            SBQQ__Quote__c cpqQuote = [SELECT ID FROM SBQQ__Quote__c LIMIT 1];
            Product2 product = [SELECT Id FROM Product2 LIMIT 1];


            Product2 product2 = Utils_Test.createProduct('Produit Test 2', 'FFFETT2');
            product2.image__c = 'https://image-test-default';
            update product2;


            List<SBQQ__QuoteLine__c> cpqQuoteLineList = new List<SBQQ__QuoteLine__c>();
            SBQQ__QuoteLine__c newCpqQuoteLine = Utils_Test.createCPQQuoteLineItem(cpqQuote.Id ,100, 100, 1, product2, false);
            newCpqQuoteLine.NombreVantaux__c = '2';
            cpqQuoteLineList.Add(newCpqQuoteLine);
            SBQQ__QuoteLine__c newCpqQuoteLine2 = Utils_Test.createCPQQuoteLineItem(cpqQuote.Id ,100, 100, 1, product2, false);
            newCpqQuoteLine2.NombreVantaux__c = '1';
            cpqQuoteLineList.Add(newCpqQuoteLine2);
            SBQQ__QuoteLine__c newCpqQuoteLine3 = Utils_Test.createCPQQuoteLineItem(cpqQuote.Id ,100, 100, 1, product, false);
            newCpqQuoteLine3.NombreVantaux__c = '2';
            cpqQuoteLineList.Add(newCpqQuoteLine3);
            insert cpqQuoteLineList;

            List<Product2> productOptionList = new List<Product2>();
            Product2 productOption1 = Utils_Test.createProduct('Produit Option 1', 'OPTION1',false);
            Product2 productOption2 = Utils_Test.createProduct('Produit Option 2', 'OPTION2',false);
            Product2 productOption3 = Utils_Test.createProduct('Produit Option 3', 'OPTION3',false);
            Product2 productOption4 = Utils_Test.createProduct('Produit Option 4', 'OPTION4',false);

            productOptionList.Add(productOption1);
            productOptionList.Add(productOption2);
            productOptionList.Add(productOption3);
            productOptionList.Add(productOption4);

            insert productOptionList;

            List<SBQQ__QuoteLine__c> cpqOptionList = new List<SBQQ__QuoteLine__c>();
            SBQQ__QuoteLine__c option1 = Utils_Test.createCPQOption(newCpqQuoteLine.Id, cpqQuote.Id, 100, 100, 1, productOption1, false);
            SBQQ__QuoteLine__c option2 = Utils_Test.createCPQOption(newCpqQuoteLine.Id, cpqQuote.Id, 100, 100, 1, productOption2, false);
            SBQQ__QuoteLine__c option3 = Utils_Test.createCPQOption(newCpqQuoteLine.Id, cpqQuote.Id, 100, 100, 1, productOption3, false);
            SBQQ__QuoteLine__c option4 = Utils_Test.createCPQOption(newCpqQuoteLine.Id, cpqQuote.Id, 100, 100, 1, productOption4, false);

            cpqOptionList.Add(option1);
            cpqOptionList.Add(option2);
            cpqOptionList.Add(option3);
            cpqOptionList.Add(option4);
            insert cpqOptionList;

            //System.debug('## insert newCpqQuoteLine :'+newCpqQuoteLine);
            List<CustomProductPictogram__c> customPictogramList = new List<CustomProductPictogram__c>();
            CustomProductPictogram__c customPictogram = new CustomProductPictogram__c(product__c = product2.Id,
                                                                                        leaf__c = '2',
                                                                                        pictogramFileLink__c = 'https://image-test',
                                                                                        productOptionLevel1__c = productOption1.Id);
            CustomProductPictogram__c customPictogram2 = new CustomProductPictogram__c(product__c = product2.Id,
                                                                                        leaf__c = '2',
                                                                                        pictogramFileLink__c = 'https://image-test',
                                                                                        productOptionLevel1__c = productOption1.Id,
                                                                                        productOptionLevel2__c = productOption2.Id);
            CustomProductPictogram__c customPictogram3 = new CustomProductPictogram__c(product__c = product2.Id,
                                                                                        leaf__c = '2',
                                                                                        pictogramFileLink__c = 'https://image-test',
                                                                                        productOptionLevel1__c = productOption1.Id,
                                                                                        productOptionLevel2__c = productOption2.Id,
                                                                                        productOptionLevel3__c = productOption3.Id);
            CustomProductPictogram__c customPictogram4 = new CustomProductPictogram__c(product__c = product2.Id,
                                                                                        leaf__c = '2',
                                                                                        pictogramFileLink__c = 'https://image-test',
                                                                                        productOptionLevel1__c = productOption1.Id,
                                                                                        productOptionLevel2__c = productOption2.Id,
                                                                                        productOptionLevel3__c = productOption3.Id,
                                                                                        productOptionLevel4__c = productOption4.Id);
            CustomProductPictogram__c customPictogram5 = new CustomProductPictogram__c(product__c = product.Id,
                                                                                        leaf__c = '2',
                                                                                        pictogramFileLink__c = 'https://image-test');
            CustomProductPictogram__c customPictogram6 = new CustomProductPictogram__c(product__c = product2.Id, pictogramFileLink__c = 'https://image-test');


            customPictogramList.Add(customPictogram);
            customPictogramList.Add(customPictogram2);
            customPictogramList.Add(customPictogram3);
            customPictogramList.Add(customPictogram4);
            customPictogramList.Add(customPictogram5);
            customPictogramList.Add(customPictogram6);                                                                        
            insert customPictogramList;
            System.debug('## insert customPictogram :'+customPictogram);
            try{
                LWC_QuoteCPQGeneratePDF.renderQuoteDocumentPDF(cpqQuote.Id, 'test', 'DIP');
            	Blob blobDIPC = LWC_QuoteCPQGeneratePDF.renderQuoteDocumentPDFBlob(cpqQuote.Id, 'test', 'DIP');
            	LWC_QuoteCPQGeneratePDF.linkDocumentToRecordForSignea(cpqQuote.Id, 'test', blobDIPC, 'DIP');
            } catch(Exception e) {
            	
        	} 
           

            Test.stopTest();
        }
    }
    
    @isTest
    private static void testUtils() {
        Test.startTest();
        LWC_QuoteCPQGeneratePDF.generateAuraException('TEST');
        Test.stopTest();
    }
     
}