force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fsl_tech_generateurRessource__c.object-meta.xml
<CustomObject>
    <description>CGI - FSL : Objet technique utilisé pour la création automatique des users et ressources rattachées</description>
    <label>FSL Générateur de ressource</label>
    <nameField>
        <label>FSL Générateur de ressource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FSL Générateur de ressources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_alias__c.field-meta.xml
<CustomField>
    <fullName>fsl_alias__c</fullName>
    <label>Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_communityNickname__c.field-meta.xml
<CustomField>
    <fullName>fsl_communityNickname__c</fullName>
    <label>Community Nick name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_contentEmailAsAndWhen__c.field-meta.xml
<CustomField>
    <fullName>fsl_contentEmailAsAndWhen__c</fullName>
    <label>Content Email As And When</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_contentNoEmail__c.field-meta.xml
<CustomField>
    <fullName>fsl_contentNoEmail__c</fullName>
    <label>Content No Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_dateEntree__c.field-meta.xml
<CustomField>
    <fullName>fsl_dateEntree__c</fullName>
    <label>Date d&apos;entrée</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_dateEntreeDepot__c.field-meta.xml
<CustomField>
    <fullName>fsl_dateEntreeDepot__c</fullName>
    <label>Date de d&apos;entrée au dépôt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_defaultGroupNotificationFrequency__c.field-meta.xml
<CustomField>
    <fullName>fsl_defaultGroupNotificationFrequency__c</fullName>
    <label>Default Notification Frequency when Join</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_depotCodeGC__c.field-meta.xml
<CustomField>
    <fullName>fsl_depotCodeGC__c</fullName>
    <label>Code GC du dépôt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_digestFrequency__c.field-meta.xml
<CustomField>
    <fullName>fsl_digestFrequency__c</fullName>
    <label>Chatter Email Highlights Frequency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_email__c.field-meta.xml
<CustomField>
    <fullName>fsl_email__c</fullName>
    <description>CGI - FSL : Email de l&apos;utilisateur</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_emailEncodingKey__c.field-meta.xml
<CustomField>
    <fullName>fsl_emailEncodingKey__c</fullName>
    <label>Email Encoding</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_firstName__c.field-meta.xml
<CustomField>
    <fullName>fsl_firstName__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_insertGroupMemberID__c.field-meta.xml
<CustomField>
    <fullName>fsl_insertGroupMemberID__c</fullName>
    <label>fsl_insertGroupMemberID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_insertUserTerritoryID__c.field-meta.xml
<CustomField>
    <fullName>fsl_insertUserTerritoryID__c</fullName>
    <label>fsl_insertUserTerritoryID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_languageLocaleKey__c.field-meta.xml
<CustomField>
    <fullName>fsl_languageLocaleKey__c</fullName>
    <label>Language</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_lastName__c.field-meta.xml
<CustomField>
    <fullName>fsl_lastName__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_localeSidKey__c.field-meta.xml
<CustomField>
    <fullName>fsl_localeSidKey__c</fullName>
    <label>Locale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_matriculeGC__c.field-meta.xml
<CustomField>
    <fullName>fsl_matriculeGC__c</fullName>
    <externalId>true</externalId>
    <label>Matricule GC</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_metier__c.field-meta.xml
<CustomField>
    <fullName>fsl_metier__c</fullName>
    <label>Métier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_name__c.field-meta.xml
<CustomField>
    <fullName>fsl_name__c</fullName>
    <label>Full Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_SGID__c.field-meta.xml
<CustomField>
    <fullName>fsl_SGID__c</fullName>
    <label>SGID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_timeZoneSidKey__c.field-meta.xml
<CustomField>
    <fullName>fsl_timeZoneSidKey__c</fullName>
    <label>Time Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_typePlanification__c.field-meta.xml
<CustomField>
    <fullName>fsl_typePlanification__c</fullName>
    <label>Type de planification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_upsertServiceResourceID__c.field-meta.xml
<CustomField>
    <fullName>fsl_upsertServiceResourceID__c</fullName>
    <label>fsl_upsertServiceResourceID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_username__c.field-meta.xml
<CustomField>
    <fullName>fsl_username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GlobalProperties__c/GlobalProperties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Propriétés globales</label>
</CustomObject>

force-app/main/default/objects/KContrat__c/KContrat__c.object-meta.xml
<CustomObject>
    <label>Contrat (K)</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats (K)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KContrat__c/fields/chantier__c.field-meta.xml
<CustomField>
    <fullName>chantier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Client chantier du contrat</description>
    <label>Chantier</label>
    <referenceTo>Chantier__c</referenceTo>
    <relationshipLabel>Contrats (K)</relationshipLabel>
    <relationshipName>chantierContrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/SGID__c.field-meta.xml
<CustomField>
    <fullName>SGID__c</fullName>
    <label>SGID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/mapping__c/mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Mapping</label>
</CustomObject>

force-app/main/default/classes/Test_fsl_GenerateurRessource.cls
//-- --------------------------------------------------------------------------------- --
//-- * 
//-- Fichier     : Test_fsl_GenerateurRessource
//-- Modifié par : CGI
//-- Modifié le  : 26/03/2018
//-- Version     : 1.0
//-- Description : Classe de test pour calcul les chiffres d'affaires des ressources
//-- --------------------------------------------------------------------------------- --
@isTest
public class Test_fsl_GenerateurRessource {
    
    @testSetup public static void setup() {
        //préparer les données pour le test
        List<GlobalProperties__c> listeGP =TestData_fsl_Setup.createGlobalProperties();
        List<mapping__c> listeGP1 =TestData_fsl_Setup.createGlobalProperties1();
        User [] u = TestData_fsl_Setup.createUser();
        Account a = TestData_fsl_Setup.createAccount();
        WorkType wt = TestData_fsl_Setup.createWorkType();
        SkillRequirement sr = TestData_fsl_Setup.createSkillRequirement(wt);
        OperatingHours oh = TestData_fsl_Setup.createOperatingHours();
        ServiceTerritory parentST = TestData_fsl_Setup.createDS(oh);
        ServiceTerritory st = TestData_fsl_Setup.createDepot(parentST,oh);
        Chantier__c chantier= TestData_fsl_Setup.createChantier(a);
        KContrat__c c = TestData_fsl_Setup.createContrat(a,chantier);
        WorkOrder wo= TestData_fsl_Setup.createTestCAWorkOrder(a,wt,st,c,oh);      
        List<ServiceResource> listeSR= TestData_fsl_Setup.createServiceResource(u);       
        List<ServiceTerritoryMember> listeSTM = TestData_fsl_Setup.createServiceTerritoryMember(listeSR,st,oh);
        
    }
    
    @istest public static void testGenerationUser() {
        test.startTest();
        TR002_fsl_GenerateurRessource.doChainJob = false;
        List<fsl_tech_generateurRessource__c> userRessourceList  = new List<fsl_tech_generateurRessource__c>();
        fsl_tech_generateurRessource__c generateur = new fsl_tech_generateurRessource__c();
        generateur.fsl_defaultGroupNotificationFrequency__c= 'N';  
        generateur.fsl_alias__c= 'kwu';
        generateur.fsl_communityNickname__c= 'kemanwu';
        generateur.fsl_contentEmailAsAndWhen__c= 'TRUE';
        generateur.fsl_contentNoEmail__c= 'TRUE';
        generateur.fsl_dateEntree__c= '01/10/2017';
        generateur.fsl_dateEntreeDepot__c= '01/10/2017'; 
        generateur.fsl_depotCodeGC__c= 'DEP';
        generateur.fsl_digestFrequency__c= 'D';
        generateur.fsl_email__c= 'keman.wu@reprisekpark.fr';
        generateur.fsl_emailEncodingKey__c= 'iso-8859-1';
        generateur.fsl_firstName__c= 'KEMAN';    
        generateur.fsl_metier__c= 'SVC0010';    
        generateur.fsl_matriculeGC__c= '123456';
        generateur.fsl_localeSidKey__c= 'fr_FR_EURO';
        generateur.fsl_lastName__c= 'WU';
        generateur.fsl_languageLocaleKey__c= 'fr';   
        generateur.fsl_name__c= 'WU KEMAN';  
        generateur.fsl_SGID__c= 'T1234567';
        generateur.fsl_timeZoneSidKey__c= 'Europe/Paris';
        generateur.fsl_typePlanification__c= 'Ressource planifiable interne';   
        generateur.fsl_username__c= 'keman.wu@reprisekpark.fr.generateur.fslreprise'; 
        
        
        insert generateur;
        userRessourceList.add(generateur);
        TR001_fsl_GenerateurRessource.createUser(userRessourceList);
        
        /*User u =[select id,Email from User where matriculeGC__c = '123456'];        
        system.assertEquals('keman.wu@reprisekpark.fr',u.Email,'Problème de génération de user');
        
        
        Integer nbPermissionSet = [select count() from PermissionSetAssignment where AssigneeId =:u.id ]; 
        system.assertEquals(4,nbPermissionSet,'Problème de génération de PermissionSet');
        
        Integer nbPermissionSetLicense = [select count() from PermissionSetLicenseAssign where AssigneeId =:u.id ]; 
        system.assertEquals(2,nbPermissionSetLicense,'Problème de génération de PermissionSetLicense');*/
        test.stopTest();
        
    }
    
    
    @istest public static void testGenerationRessource() {  
        test.startTest();             
        TR002_fsl_GenerateurRessource.doChainJob = false;
        TR003_fsl_GenerateurRessource.doChainJob = false;
        
        Map<String, fsl_tech_generateurRessource__c> generatorMap = new  Map<String, fsl_tech_generateurRessource__c>();
        List<fsl_tech_generateurRessource__c> userRessourceList  = new List<fsl_tech_generateurRessource__c>();
        fsl_tech_generateurRessource__c generateur = new fsl_tech_generateurRessource__c();
        generateur.fsl_defaultGroupNotificationFrequency__c= 'N';  
        generateur.fsl_alias__c= 'kwu';
        generateur.fsl_communityNickname__c= 'kemanwu';
        generateur.fsl_contentEmailAsAndWhen__c= 'TRUE';
        generateur.fsl_contentNoEmail__c= 'TRUE';
        generateur.fsl_dateEntree__c= '01/10/2017';
        generateur.fsl_dateEntreeDepot__c= '01/10/2017'; 
        generateur.fsl_depotCodeGC__c= 'DEP';
        generateur.fsl_digestFrequency__c= 'D';
        generateur.fsl_email__c= 'keman.wu@reprisekpark.fr';
        generateur.fsl_emailEncodingKey__c= 'iso-8859-1';
        generateur.fsl_firstName__c= 'KEMAN';    
        generateur.fsl_metier__c= 'SVC0010';    
        generateur.fsl_matriculeGC__c= '123456';
        generateur.fsl_localeSidKey__c= 'fr_FR_EURO';
        generateur.fsl_lastName__c= 'WU';
        generateur.fsl_languageLocaleKey__c= 'fr';   
        generateur.fsl_name__c= 'WU KEMAN';  
        generateur.fsl_SGID__c= 'T1234567';
        generateur.fsl_timeZoneSidKey__c= 'Europe/Paris';
        generateur.fsl_typePlanification__c= 'Ressource planifiable interne';   
        generateur.fsl_username__c= 'keman.wu@reprisekpark.fr.generateur.fslreprise'; 
        generatorMap.put(generateur.fsl_matriculeGC__c, generateur);
        
        insert generateur;  
        userRessourceList.add(generateur);
        TR001_fsl_GenerateurRessource.createUser(userRessourceList);
        
        List<User> u =[select id,codeDepot__c,matriculeGC__c,typePlanification__c,FirstName,LastName,metier__c,sgid__c,isActive from User /*where matriculeGC__c = '123456'*/];        
        List<PermissionSetLicenseAssign>  permission = [select PermissionSetLicense.MasterLabel from PermissionSetLicenseAssign where AssigneeId =:u[0].id ];      
        
        TR003_fsl_GenerateurRessource third = new TR003_fsl_GenerateurRessource(u, generatorMap, new FieldServiceError());
        third.execute(null);
        
        
        //ServiceResource sr = [select fsl_SGID__c from ServiceResource where fsl_matriculeGC__c = '123456'];
        //system.assertEquals('T1234567',sr.fsl_SGID__c,'Problème de génération de ressource');
        test.stopTest();
        
    }
    
    @istest public static void testGenerationGroupMember() {
        test.startTest();       
        
        TR002_fsl_GenerateurRessource.doChainJob = false;
        TR003_fsl_GenerateurRessource.doChainJob = false;
        TR004_fsl_GenerateurRessource.doChainJob = false;
        
        Map<String, fsl_tech_generateurRessource__c> generatorMap = new  Map<String, fsl_tech_generateurRessource__c>(); 
        List<fsl_tech_generateurRessource__c> userRessourceList  = new List<fsl_tech_generateurRessource__c>();
        fsl_tech_generateurRessource__c generateur = new fsl_tech_generateurRessource__c();
        generateur.fsl_defaultGroupNotificationFrequency__c= 'N';  
        generateur.fsl_alias__c= 'kwu';
        generateur.fsl_communityNickname__c= 'kemanwu';
        generateur.fsl_contentEmailAsAndWhen__c= 'TRUE';
        generateur.fsl_contentNoEmail__c= 'TRUE';
        generateur.fsl_dateEntree__c= '01/10/2017';
        generateur.fsl_dateEntreeDepot__c= '01/10/2017'; 
        generateur.fsl_depotCodeGC__c= 'DEP';
        generateur.fsl_digestFrequency__c= 'D';
        generateur.fsl_email__c= 'keman.wu@reprisekpark.fr';
        generateur.fsl_emailEncodingKey__c= 'iso-8859-1';
        generateur.fsl_firstName__c= 'KEMAN';    
        generateur.fsl_metier__c= 'SVC0010';    
        generateur.fsl_matriculeGC__c= '123456';
        generateur.fsl_localeSidKey__c= 'fr_FR_EURO';
        generateur.fsl_lastName__c= 'WU';
        generateur.fsl_languageLocaleKey__c= 'fr';   
        generateur.fsl_name__c= 'WU KEMAN';  
        generateur.fsl_SGID__c= 'T1234567';
        generateur.fsl_timeZoneSidKey__c= 'Europe/Paris';
        generateur.fsl_typePlanification__c= 'Ressource planifiable interne';   
        generateur.fsl_username__c= 'keman.wu@reprisekpark.fr.generateur.fslreprise'; 
        generatorMap.put(generateur.fsl_matriculeGC__c, generateur);
        
        Map<String, ServiceTerritory> territoryMap = new Map <String,ServiceTerritory>();
        for (ServiceTerritory str : [select id, KparKReference__c from serviceTerritory Limit 1000]) {
            territoryMap.put(str.KparKReference__c, str );            
        }
        Map<String, ID> territoryGroupIdMap = new Map <String,ID>();
        for (ServiceTerritoryShare strSh : [select UserOrGroupId, Parent.KparKReference__c from ServiceTerritoryShare where RowCause = 'Manual' and Parent.KparKReference__c IN :territoryMap.keySet()  Limit 1000]) {
            territoryGroupIdMap.put(strSh.Parent.KparKReference__c, strSh.UserOrGroupId );            
        }
        
        insert generateur; 
        userRessourceList.add(generateur);
        TR001_fsl_GenerateurRessource.createUser(userRessourceList);
        
        List<User> u =[select id,codeDepot__c,matriculeGC__c,typePlanification__c,FirstName,LastName,metier__c,sgid__c,isActive from User/* where matriculeGC__c = '123456'*/];        
        List<GroupMember > grpMemberToCreateList = new  List<GroupMember >(); 
        
        if(territoryGroupIdMap.containsKey(u[0].codeDepot__c)){
            GroupMember grpMemberToCreate = new  GroupMember();
            grpMemberToCreate.groupId = territoryGroupIdMap.get(u[0].codeDepot__c);
            grpMemberToCreate.UserOrGroupId = u[0].id;
            grpMemberToCreateList.add(grpMemberToCreate);
        }
        
        List<FSL__User_Territory__c> userTerritoryToCreateList = new  List<FSL__User_Territory__c>(); 
        FSL__User_Territory__c  userTerritoryToCreate = new FSL__User_Territory__c ();  
        if (territoryMap.containsKey(u[0].codeDepot__c)){
            userTerritoryToCreate = new FSL__User_Territory__c();
            userTerritoryToCreate.FSL__ServiceTerritory__c = territoryMap.get(u[0].codeDepot__c).id;
            userTerritoryToCreate.FSL__User__c = u[0].ID;
            userTerritoryToCreateList.add(userTerritoryToCreate);
        }
        
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        System.runAs ( thisUser ) {
            TR004_fsl_GenerateurRessource fourth =  new TR004_fsl_GenerateurRessource(u, generatorMap,grpMemberToCreateList,new FieldServiceError(),userTerritoryToCreateList );
            fourth.execute(null);
        }  
        
        
        /*GroupMember gm = [select groupId from GroupMember where UserOrGroupId = :u[0].id];
        system.assertEquals(territoryGroupIdMap.get(u[0].codeDepot__c),gm.groupId,'Problème de génération de grope member');*/
        
        test.stopTest();
    }
    
    @istest public static void testGenerationUserTerritory() {
        test.startTest();       
        
        TR002_fsl_GenerateurRessource.doChainJob = false;
        TR003_fsl_GenerateurRessource.doChainJob = false;
        TR004_fsl_GenerateurRessource.doChainJob = false;
        
        Map<String, fsl_tech_generateurRessource__c> generatorMap = new  Map<String, fsl_tech_generateurRessource__c>(); 
        List<fsl_tech_generateurRessource__c> userRessourceList  = new List<fsl_tech_generateurRessource__c>();
        fsl_tech_generateurRessource__c generateur = new fsl_tech_generateurRessource__c();
        generateur.fsl_defaultGroupNotificationFrequency__c= 'N';  
        generateur.fsl_alias__c= 'kwu';
        generateur.fsl_communityNickname__c= 'kemanwu';
        generateur.fsl_contentEmailAsAndWhen__c= 'TRUE';
        generateur.fsl_contentNoEmail__c= 'TRUE';
        generateur.fsl_dateEntree__c= '01/10/2017';
        generateur.fsl_dateEntreeDepot__c= '01/10/2017'; 
        generateur.fsl_depotCodeGC__c= 'DEP';
        generateur.fsl_digestFrequency__c= 'D';
        generateur.fsl_email__c= 'keman.wu@reprisekpark.fr';
        generateur.fsl_emailEncodingKey__c= 'iso-8859-1';
        generateur.fsl_firstName__c= 'KEMAN';    
        generateur.fsl_metier__c= 'SVC0010';    
        generateur.fsl_matriculeGC__c= '123456';
        generateur.fsl_localeSidKey__c= 'fr_FR_EURO';
        generateur.fsl_lastName__c= 'WU';
        generateur.fsl_languageLocaleKey__c= 'fr';   
        generateur.fsl_name__c= 'WU KEMAN';  
        generateur.fsl_SGID__c= 'T1234567';
        generateur.fsl_timeZoneSidKey__c= 'Europe/Paris';
        generateur.fsl_typePlanification__c= 'Ressource planifiable interne';   
        generateur.fsl_username__c= 'keman.wu@reprisekpark.fr.generateur.fslreprise'; 
        generatorMap.put(generateur.fsl_matriculeGC__c, generateur);
        
        Map<String, ServiceTerritory> territoryMap = new Map <String,ServiceTerritory>();
        for (ServiceTerritory str : [select id, KparKReference__c  from serviceTerritory Limit 1000]) {
            territoryMap.put(str.KparKReference__c, str );            
        }
        Map<String, ID> territoryGroupIdMap = new Map <String,ID>();
        for (ServiceTerritoryShare strSh : [select UserOrGroupId, Parent.KparKReference__c from ServiceTerritoryShare where RowCause = 'Manual' and Parent.KparKReference__c IN :territoryMap.keySet()  Limit 1000]) {
            territoryGroupIdMap.put(strSh.Parent.KparKReference__c, strSh.UserOrGroupId );            
        }
        
        insert generateur; 
        userRessourceList.add(generateur);
        TR001_fsl_GenerateurRessource.createUser(userRessourceList);
        
        List<User> u =[select id,codeDepot__c,matriculeGC__c,typePlanification__c,FirstName,LastName,metier__c,sgid__c,isActive from User/* where matriculeGC__c = '123456'*/];        
        
        List<FSL__User_Territory__c> userTerritoryToCreateList = new  List<FSL__User_Territory__c>(); 
        FSL__User_Territory__c  userTerritoryToCreate = new FSL__User_Territory__c ();  
        if (territoryMap.containsKey(u[0].codeDepot__c)){
            userTerritoryToCreate = new FSL__User_Territory__c();
            userTerritoryToCreate.FSL__ServiceTerritory__c = territoryMap.get(u[0].codeDepot__c).id;
            userTerritoryToCreate.FSL__User__c = u[0].ID;
            userTerritoryToCreateList.add(userTerritoryToCreate);
        }
        
        TR005_fsl_GenerateurRessource fifth = new TR005_fsl_GenerateurRessource(u, generatorMap, new FieldServiceError(),userTerritoryToCreateList);
        fifth.execute(null);
        
        /*FSL__User_Territory__c ut = [select FSL__ServiceTerritory__c from FSL__User_Territory__c where FSL__User__c = :u[0].id];
        system.assertEquals(territoryMap.get(u[0].codeDepot__c).id,ut.FSL__ServiceTerritory__c,'Problème de génération user territory');
        
        fsl_tech_generateurRessource__c gr = [select fsl_insertUserTerritoryID__c,fsl_insertGroupMemberID__c,fsl_upsertServiceResourceID__c from fsl_tech_generateurRessource__c where fsl_matriculeGC__c= '123456'];
        system.assertNotEquals(null,gr.fsl_insertUserTerritoryID__c,'Problème de mise à jour générateur');  */ 
        test.stopTest();    
        
    }
}