force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/anneeAchat__c.field-meta.xml
<CustomField>
    <fullName>anneeAchat__c</fullName>
    <label>Année d&apos;achat</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/anneeConstruction__c.field-meta.xml
<CustomField>
    <fullName>anneeConstruction__c</fullName>
    <label>Année de construction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NSP</fullName>
            </value>
            <value>
                <fullName>Avant 1940</fullName>
            </value>
            <value>
                <fullName>1950</fullName>
            </value>
            <value>
                <fullName>1960</fullName>
            </value>
            <value>
                <fullName>1970</fullName>
            </value>
            <value>
                <fullName>1980</fullName>
            </value>
            <value>
                <fullName>1990</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2010+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreLocataire__c.field-meta.xml
<CustomField>
    <fullName>autreLocataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre locataire)</relationshipLabel>
    <relationshipName>autreLocataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreOccupant__c.field-meta.xml
<CustomField>
    <fullName>autreOccupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre occupant)</relationshipLabel>
    <relationshipName>autreOccupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreProprietaire__c.field-meta.xml
<CustomField>
    <fullName>autreProprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre propriétaire)</relationshipLabel>
    <relationshipName>autreProprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/bilanEnergetique__c.field-meta.xml
<CustomField>
    <fullName>bilanEnergetique__c</fullName>
    <label>Bilan énergétique</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/caracteristiquesUrbanisme__c.field-meta.xml
<CustomField>
    <fullName>caracteristiquesUrbanisme__c</fullName>
    <label>Caractéristique(s) urbanisme</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accord mairie</fullName>
            </value>
            <value>
                <fullName>Accord syndic</fullName>
            </value>
            <value>
                <fullName>Aéroport</fullName>
            </value>
            <value>
                <fullName>Bâtiment de France</fullName>
            </value>
            <value>
                <fullName>Littoral</fullName>
            </value>
            <value>
                <fullName>Monument historique</fullName>
            </value>
            <value>
                <fullName>Respect façade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/chauffages__c.field-meta.xml
<CustomField>
    <fullName>chauffages__c</fullName>
    <label>Mode(s) de chauffe</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individuel Electrique</fullName>
            </value>
            <value>
                <fullName>Individuel Fuel</fullName>
            </value>
            <value>
                <fullName>Individuel Gaz</fullName>
            </value>
            <value>
                <fullName>Individuel Autre</fullName>
            </value>
            <value>
                <fullName>Collectif</fullName>
            </value>
            <value>
                <fullName>Energie renouvelable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/codeAcces__c.field-meta.xml
<CustomField>
    <fullName>codeAcces__c</fullName>
    <label>Code d&apos;accès</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/codePostal__c.field-meta.xml
<CustomField>
    <fullName>codePostal__c</fullName>
    <label>Code postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/complementAdresse__c.field-meta.xml
<CustomField>
    <fullName>complementAdresse__c</fullName>
    <inlineHelpText>Informations affichées comme 2nd ligne sur l’adresse postale.
Résidence, bâtiment, zone, etc.</inlineHelpText>
    <label>Complément d&apos;adresse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/departement__c.field-meta.xml
<CustomField>
    <fullName>departement__c</fullName>
    <label>Département/Région</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/etage__c.field-meta.xml
<CustomField>
    <fullName>etage__c</fullName>
    <label>Etage</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/interphone__c.field-meta.xml
<CustomField>
    <fullName>interphone__c</fullName>
    <label>Interphone</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/isolationHabitation__c.field-meta.xml
<CustomField>
    <fullName>isolationHabitation__c</fullName>
    <label>Isolation de l&apos;habitation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/locataire__c.field-meta.xml
<CustomField>
    <fullName>locataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du propriétaire</inlineHelpText>
    <label>Locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Locataire)</relationshipLabel>
    <relationshipName>locataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/montantDepensesChauffage__c.field-meta.xml
<CustomField>
    <fullName>montantDepensesChauffage__c</fullName>
    <label>Montant des dépenses de chauffage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/nbPortesEtFenetres__c.field-meta.xml
<CustomField>
    <fullName>nbPortesEtFenetres__c</fullName>
    <label>Nombre de portes et fenêtres présentes</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/occupant__c.field-meta.xml
<CustomField>
    <fullName>occupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du locataire</inlineHelpText>
    <label>Occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Occupant)</relationshipLabel>
    <relationshipName>occupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/pays__c.field-meta.xml
<CustomField>
    <fullName>pays__c</fullName>
    <label>Pays</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/presenceGarage__c.field-meta.xml
<CustomField>
    <fullName>presenceGarage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Présence d&apos;un garage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/presencePortail__c.field-meta.xml
<CustomField>
    <fullName>presencePortail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Présence d&apos;un portail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/presenceTerrasse__c.field-meta.xml
<CustomField>
    <fullName>presenceTerrasse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Présence d&apos;une terrasse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/proprietaire__c.field-meta.xml
<CustomField>
    <fullName>proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire)</relationshipLabel>
    <relationshipName>proprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/rue__c.field-meta.xml
<CustomField>
    <fullName>rue__c</fullName>
    <label>Rue</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/sectorisation__c.field-meta.xml
<CustomField>
    <fullName>sectorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sectorisation</label>
    <referenceTo>Sectorisation__c</referenceTo>
    <relationshipLabel>Chantiers</relationshipLabel>
    <relationshipName>sectorisationChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/typeHabitation__c.field-meta.xml
<CustomField>
    <fullName>typeHabitation__c</fullName>
    <label>Type d&apos;habitation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pavillon</fullName>
            </value>
            <value>
                <fullName>Appartement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/typeResidence__c.field-meta.xml
<CustomField>
    <fullName>typeResidence__c</fullName>
    <label>Type de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Secondaire</fullName>
            </value>
            <value>
                <fullName>Locative</fullName>
            </value>
            <value>
                <fullName>Professionnelle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/ville__c.field-meta.xml
<CustomField>
    <fullName>ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/GlobalProperties__c/GlobalProperties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Propriétés globales</label>
</CustomObject>

force-app/main/default/objects/GlobalProperties__c/fields/booleanValue__c.field-meta.xml
<CustomField>
    <fullName>booleanValue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Booléen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GlobalProperties__c/fields/stringValue__c.field-meta.xml
<CustomField>
    <fullName>stringValue__c</fullName>
    <label>Texte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/Sectorisation__c.object-meta.xml
<CustomObject>
    <label>Sectorisation</label>
    <nameField>
        <label>Nom de Sectorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_Ctrl_ChantierMerge.cls
//-- *
//-- Fichier     : Test_Ctrl_ChantierMerge
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 11/04/2017
//-- Version     : 1.0
//-- * Init
//-- --------------------------------------------------------------------------------- --
@isTest
private class Test_Ctrl_ChantierMerge { 

	@testSetup 
    static void setup() {
		Utils_Test.createGlobalProperties(true, 17, true, true, true, 30, 10, true);
        Sectorisation__c defaultSectorisation = Utils_Test.createSectorisation();
	}

	@isTest 
    static void test_ManualFusion() {
        // Création d'un utilisateur
        User user = Utils_Test.createUser(true,'Test', 'puser'+system.now().format('hhmmss')+'@testemail.com', 'Test LastName','Test FirstName', null, null);

        // Test compte personnel sans géolocalisation avec association de conjoint
        System.RunAs(user) {
            Utils_Test.createGlobalProperties(true, 17, true, true, true, 30, 10, true);
			RecordType accountRecordType = [Select id, Name from RecordType where sobjectType = 'Account' and isPersonType = true limit 1];
			RecordType chantierRecordType = [Select id, Name from RecordType where sobjectType = 'Chantier__c' and isActive = true limit 1];
			Account compte = Utils_Test.createAccount('Test', 'test', 'test@test.com', accountRecordType.Id, 'Email', true);
			Chantier__c chantier = Utils_Test.createChantier('a', compte.Id, true);
			Chantier__c chantier2 = Utils_Test.createChantier('b', compte.Id, true);
            List<Chantier__c> chaList = [SELECT Id FROM Chantier__c LIMIT 2];
			String doublonId=chaList[0].Id;
			String maitreId=chaList[1].Id;

            GlobalProperties__c dqe = new GlobalProperties__c(name='dqe.dedup.compte.enabled',booleanValue__c = true, stringValue__c='MAG');
            insert dqe;

            // TEST
            Test.startTest();

            PageReference pageRef = Page.VF_ChantierMerge;
			// Parametre doublon
			pageRef.getParameters().put('doublonKeyId', maitreId);
			pageRef.getParameters().put('detail', 'edit');
			pageRef.getParameters().put('doublonsId', doublonId);
			pageRef.getParameters().put('chantierObject', JSON.serialize(chantier2));
			pageRef.getParameters().put('cha1', maitreId);

			List<String> fieldList = new List<String>{ 'Name','rue__c','complementAdresse__c','codePostal__c','ville__c','departement__c','pays__c','etage__c','codeAcces__c','interphone__c','proprietaire__c',
                            'autreProprietaire__c','anneeAchat__c','locataire__c','autreLocataire__c','occupant__c','autreOccupant__c','anneeConstruction__c','caracteristiquesUrbanisme__c',
                            'typeHabitation__c','typeResidence__c','chauffages__c','montantDepensesChauffage__c','bilanEnergetique__c','isolationHabitation__c','nbPortesEtFenetres__c',
                            'presenceGarage__c','presencePortail__c','presenceTerrasse__c','description__c' };

            // Fusion manuel
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController stdController = new ApexPages.standardController(chantier);
            Ctrl_ChantierMerge ctrl = new Ctrl_ChantierMerge(stdController);

            List<SelectOption> optionListTest = new List<SelectOption>();
            optionListTest = ctrl.getcaracteristiquesUrbanisme();
            optionListTest = ctrl.getmodesDeChauffe();
            optionListTest = ctrl.gettypeHabitationList();
            optionListTest = ctrl.gettypeResidenceList();
            Ctrl_ChantierMerge.manualMerge(new Map<String,String>{'Name'=>'test'}, JSON.serialize(chantier2), doublonId, maitreId, fieldList);

			// Cancel
			ctrl.typeURL='edit';
			ctrl.doublonsId=doublonId;
            ctrl.cancelMerge();
			
            Test.stopTest();
        }
    }	
}