force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/codePostal__c.field-meta.xml
<CustomField>
    <fullName>codePostal__c</fullName>
    <label>Code postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/departement__c.field-meta.xml
<CustomField>
    <fullName>departement__c</fullName>
    <label>Département/Région</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/pays__c.field-meta.xml
<CustomField>
    <fullName>pays__c</fullName>
    <label>Pays</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/proprietaire__c.field-meta.xml
<CustomField>
    <fullName>proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire)</relationshipLabel>
    <relationshipName>proprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/rue__c.field-meta.xml
<CustomField>
    <fullName>rue__c</fullName>
    <label>Rue</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/ville__c.field-meta.xml
<CustomField>
    <fullName>ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/GlobalProperties__c/GlobalProperties__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Propriétés globales</label>
</CustomObject>

force-app/main/default/objects/GlobalProperties__c/fields/actif__c.field-meta.xml
<CustomField>
    <fullName>actif__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Actif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GlobalProperties__c/fields/dateTimeValue__c.field-meta.xml
<CustomField>
    <fullName>dateTimeValue__c</fullName>
    <label>Date/Heure</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/GlobalProperties__c/fields/dateValue__c.field-meta.xml
<CustomField>
    <fullName>dateValue__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/GlobalProperties__c/fields/stringValue__c.field-meta.xml
<CustomField>
    <fullName>stringValue__c</fullName>
    <label>Texte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KContrat__c/KContrat__c.object-meta.xml
<CustomObject>
    <label>Contrat (K)</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats (K)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KContrat__c/fields/chantier__c.field-meta.xml
<CustomField>
    <fullName>chantier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Client chantier du contrat</description>
    <label>Chantier</label>
    <referenceTo>Chantier__c</referenceTo>
    <relationshipLabel>Contrats (K)</relationshipLabel>
    <relationshipName>chantierContrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/compte__c.field-meta.xml
<CustomField>
    <fullName>compte__c</fullName>
    <description>Client signataire du contrat</description>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats (K)</relationshipLabel>
    <relationshipName>compteContrats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/numeroContrat__c.field-meta.xml
<CustomField>
    <fullName>numeroContrat__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Numéro de contrat</description>
    <externalId>true</externalId>
    <label>N° contrat</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Test_BA_TimeSheetCreation.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_BA_TimeSheetCreation
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 29/07/2020
//-- Version     : 1.0
//-- * Initialisation
//-- --------------------------------------------------------------------------------- --
@isTest (SeeAllData=false)
private class Test_BA_TimeSheetCreation {
    private static final Id RT_WORK_ORDER_FSL = DAL.getRecordTypeIdByDevName('WorkOrder', 'FSL_workOrder');
    private static final Id SA_KUBE2_RT = DAL.getRecordTypeIdByDevName('ServiceAppointment', 'FSL_rendezVousPlanification');
    
    //Data Setup
    @testSetup
    public static void testSetup(){
        
        //Création d'un compte 
        Account a = new Account(
            Name='TestAccount',
            BillingCity='Paris',
            BillingPostalCode='75116',
            BillingStreet='34 rue de la faisanderie',
            AccountSource='WEB',
            Phone='0627105593'); 
        insert a;

        //Création horaires
        OperatingHours oh = new OperatingHours(
            //fsl_dateOuverture__c = Date.newInstance(2017, 1, 1),
            Name='K/K Semaine type standard' ,
            TimeZone='Europe/Paris' );
        insert oh;  
        
        //Création du dépot
        ServiceTerritory parentST = new ServiceTerritory(
            Name='DS',
            OperatingHoursId=oh.Id,
            IsActive=true,
            KparKReference__c = '12324');           
        insert parentST; 
        
        
        //Création d'un chantier
        Chantier__c chantier = new Chantier__c(
            name='testChantier',
            rue__c='34 de la faisanderie',
            codePostal__c='75116',
            ville__c='Paris',
            departement__c='Ile de France',
            pays__c='France',
            proprietaire__c=a.id);
        insert chantier;

        
        //Création d'un contrat 
        /*KContrat__c c = new KContrat__c(
            Name='TestContrat' ,
            numeroContrat__c='CTR', 
            compte__c=a.id, 
            chantier__c=chantier.id);
        insert c;*/
        
        
        //Création d'un territoire 
        ServiceTerritory st = new ServiceTerritory(
            ParentTerritoryId=parentST.id,
            Name='Depot',
            OperatingHoursId=oh.Id,
            IsActive=true,
            KparKReference__c = '12314');     
        insert st;
        
        
        //Création d'un work type 
        WorkType wt = new WorkType(
            Name=Constants.ACTIVITY_TYPE_INTERVENTION,
            EstimatedDuration=1.0,
            fsl_dateOuverture__c = Date.newInstance(2017, 1, 1));
        insert wt;
        
        
        //Création d'un work order 
        DateTime now=system.now();
        WorkOrder wo= new WorkOrder(
            FSL_EXTERNALID__C='ParentWorkOrder',
            AccountId=a.Id, 
            //ContratK__c=c.id, 
            WorkTypeId=wt.id,
            City = 'toto',
            Street = '1 rue test',
            PostalCode = '12345',
            Country = 'France',
            ServiceTerritoryId=st.Id,
            STARTDATE=now.addDays(-31),
            ENDDATE=now.addDays(120),
            DURATIONTYPE='Minutes',
            DURATION=40,
            fsl_techFlagSynchro__c=Datetime.newInstance(2018, 2, 7, 10, 0, 0),
            FSL__VisitingHours__c = oh.id, 
            RecordTypeId = RT_WORK_ORDER_FSL,
            fsl_chiffreAffaire__c = 300);
        insert wo;
        
        
        //Creation des utilisateurs 
        Profile[] pf= [Select Id from profile where Name LIKE '%Ressource%']; 
        
        List<User> listeUser=new List<User>();
        User u1=new User(firstname = 'Test', 
                         lastName = 'Resource1', 
                         email = 'test.resource1@example.com', 
                         Username = 'test.resource1@kpark.fr.fsl', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = 'res1',  
                         TimeZoneSidKey = 'Europe/Paris', 
                         LocaleSidKey = 'fr_FR_EURO', 
                         LanguageLocaleKey = 'fr', 
                         matriculeGC__c = 'testResource1',
                         IsActive = true,
                         ProfileId = pf[0].Id,
                         dateEntree__c = Date.newInstance(2017, 1, 1)
                        );        
        listeUser.add(u1);
        
        User u2=new User(firstname = 'Test', 
                         lastName = 'Resource2', 
                         email = 'test.resource2@example.com', 
                         Username = 'test.resource2@kpark.fr.fsl', 
                         EmailEncodingKey = 'ISO-8859-1', 
                         Alias = 'res2', 
                         TimeZoneSidKey = 'Europe/Paris', 
                         LocaleSidKey = 'fr_FR_EURO', 
                         LanguageLocaleKey = 'fr', 
                         matriculeGC__c = 'testResource2',
                         IsActive = true,
                         ProfileId = pf[0].Id,
                         dateEntree__c = Date.newInstance(2017, 1, 1)                                                 
                        );       
        listeUser.add(u2);
        insert listeUser;
        
        //List<User> u = [SELECT Id FROM User];
        
        //Creation des ressources
        List<ServiceResource> listeSR =new List<ServiceResource> ();
        ServiceResource sr1= new ServiceResource(
            fsl_matriculeGC__c='RES01',
            fsl_SGID__c='SGID01',
            name='MetreurTest',
            ResourceType='T',
            RelatedRecordId=u1.id,
            IsActive=true,
            IsCapacityBased=true);           
        listeSR.add(sr1);
        
        ServiceResource sr2= new ServiceResource(
            fsl_matriculeGC__c='RES02',
            fsl_SGID__c='SGID02',
            name='PoseurTest',
            ResourceType='T',
            RelatedRecordId=u2.id,
            IsActive=true);           
        listeSR.add(sr2);
        insert listeSR;
        
        //List<ServiceResource> sr = [SELECT Id FROM ServiceResource];
        
        //Creation de membre de territoires
        List<ServiceTerritoryMember> listeSTM=new List<ServiceTerritoryMember> ();
        ServiceTerritoryMember stm1= new ServiceTerritoryMember(
            EffectiveStartDate=Date.newInstance(2017, 1, 1),
            ServiceResourceId=sr1.id,
            ServiceTerritoryId=st.id,
            TerritoryType='P',
            OperatingHoursId=oh.Id);           
        listeSTM.add(stm1);
        
        ServiceTerritoryMember stm2= new ServiceTerritoryMember(
            EffectiveStartDate=Date.newInstance(2017, 1, 1),
            ServiceResourceId=sr2.id,
            ServiceTerritoryId=st.id,
            TerritoryType='P',
            OperatingHoursId=oh.Id);           
        listeSTM.add(stm2); 
        insert listeSTM;
        
        //Propriétés globales
        /*GlobalProperties__c gpwo = new GlobalProperties__c(
            Name = 'fsl.platformEvent.sync.sa',
            actif__c = true,
            dateTimeValue__c = DateTime.newInstanceGmt(2019, 02, 20, 14, 50, 00)
        );
        insert gpwo;
        
        GlobalProperties__c gpwo2 = new GlobalProperties__c(
            Name = 'fsl.platformEvent.exception.email',
            actif__c = true,
            stringValue__c = 'test@gmail.com'
        );
        insert gpwo2;
        
        GlobalProperties__c gpwo3 = new GlobalProperties__c(
            Name = 'fsl.platformEvent.check.email',
            actif__c = true,
            stringValue__c = 'test@gmail.com'
        );
        insert gpwo3;    
        
        GlobalProperties__c gpwo4 = new GlobalProperties__c(
            Name = 'fsl.calculCA.calendrierService.debut',
            actif__c = true,
            dateTimeValue__c = Date.newInstance(2019, 07, 01)
        );
        insert gpwo4;
        
        GlobalProperties__c gpwo5 = new GlobalProperties__c(
            Name = 'fsl.calculCA.calendrierService.fin1',
            actif__c = true,
            dateTimeValue__c = Date.newInstance(2019, 07, 28)
        );
        insert gpwo5;
        
        GlobalProperties__c gpwo6 = new GlobalProperties__c(
            Name = 'fsl.calculCA.calendrierService.fin3',
            actif__c = true,
            dateTimeValue__c = Date.newInstance(2019, 09, 29)
        );
        insert gpwo6;
        
        GlobalProperties__c gpwo7 = new GlobalProperties__c(
            Name = 'fsl.calculCA.calendrierService.debut',
            actif__c = true,
            dateValue__c = Date.newInstance(2019, 08, 26)
        );
        insert gpwo7;
        
        GlobalProperties__c gpwo8 = new GlobalProperties__c(
            Name = 'fsl.calculCA.calendrierService.fin1',
            actif__c = true,
            dateValue__c = Date.newInstance(2019, 09, 29)
        );
        insert gpwo8;*/
               
        FSL.GlobalAPIS.addStatusTransition('Demandé', 'Planifié');
        FSL.GlobalAPIS.addStatusTransition('Demandé', 'Confirmé');
        FSL.GlobalAPIS.addStatusTransition('Planifié', 'Confirmé');
    }    
    
    @isTest 
    static void testScheduleTimeSheetCreation() {                
        Test.startTest();

        Schedule_TimeSheetCreation sh1 = new Schedule_TimeSheetCreation();
        String sch = '0 0 23 * * ?'; system.schedule('Test TimeSheetCreation', sch, sh1);
        
        Test.stopTest();
    }    
}