force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <description>Option pour les lignes de devis Kube2</description>
    <label>Devis Ligne Option</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devis Ligne Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Option__c/fields/ligneDevis__c.field-meta.xml
<CustomField>
    <fullName>ligneDevis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Champ reliant l&apos;option à la ligne de devis correspondante. 
Ancien champ Lignedevis_del__c renommé</description>
    <label>Ligne devis</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Devis Ligne Options (Ligne devis)</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>ReferentielOptions__c</referenceTo>
    <relationshipName>Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Valorisation__c.field-meta.xml
<CustomField>
    <fullName>Valorisation__c</fullName>
    <description>Alimenté par configurateur</description>
    <label>Valorisation</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_TR001_Options.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_TR001_Options
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 23/10/2022
//-- Version     : 1.01
//-- *
//-- --------------------------------------------------------------------------------- --
@isTest
private class Test_TR001_Options {
    private static final Id rtB2C = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PERSO_RT);

    @isTest 
    static void test_TR001_Options() {
        User user = Utils_Test.createUser(true,'Test', 'MyTestUserName@test.sfd.test', 'MyTestLastName','MyTestFirstName', null, null);
        
        System.runAs(user){

            Utils_Test.createGlobalProperties(true, 17, true, true, true, 30, 10, true);
            Account acc = Utils_Test.createAccount('Account UN', 'test', 'test@test.fr', rtB2C, 'Email',true);
            Chantier__c chantier = Utils_Test.createChantier('Chantier 1', acc.Id,true);
            Opportunity opp = Utils_Test.createOpportunity(acc, chantier,true);
            // Creation devis
            Quote quote = Utils_Test.createQuote('Devis 1', null, opp, Constants.StatutDevisAConfigurer, Date.today(), 1000, 100, false);
            quote.source__c = 'BAL VENDEUR';
            insert quote;
            // Ligne de devis et produit
            Product2 product = Utils_Test.createProduct('test', '1234');
            QuoteLineItem line = Utils_Test.createQuoteLineItem(quote.id, '2', 90, 150, 1, 1.0, 1.0, product, false);

            Test.startTest();

            list <Option__c> optionList = new list<Option__c>();
            Option__c op = new Option__c();
            op.Option__c = TestUtils.getNewReferentielOptions(2).Id;
            op.ligneDevis__c = line.Id;
            op.Valorisation__c = 100;
            optionList.add(op);
            System.debug('\n\n\n optionList'+optionList+'\n\n\n\n');
            TR001_Options.calculatePrice(optionList);
            op.Option__c = TestUtils.getNewReferentielOptions(3).Id;
            TR001_Options.calculatePrice(optionList);
            op.Option__c = TestUtils.getNewReferentielOptions(4).Id;
            TR001_Options.calculatePrice(optionList);
            op.Option__c = TestUtils.getNewReferentielOptions(5).Id;
            TR001_Options.calculatePrice(optionList);
            op.Option__c = TestUtils.getNewReferentielOptions(6).Id;
            TR001_Options.calculatePrice(optionList);
            op.Option__c = TestUtils.getNewReferentielOptions(7).Id;
            TR001_Options.calculatePrice(optionList);
            op.Option__c = TestUtils.getNewReferentielOptions(8).Id;
            TR001_Options.calculatePrice(optionList);

            Test.stopTest();

        }
    }
}