force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/anneeConstruction__c.field-meta.xml
<CustomField>
    <fullName>anneeConstruction__c</fullName>
    <label>Année de construction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NSP</fullName>
            </value>
            <value>
                <fullName>Avant 1940</fullName>
            </value>
            <value>
                <fullName>1950</fullName>
            </value>
            <value>
                <fullName>1960</fullName>
            </value>
            <value>
                <fullName>1970</fullName>
            </value>
            <value>
                <fullName>1980</fullName>
            </value>
            <value>
                <fullName>1990</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2010+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreLocataire__c.field-meta.xml
<CustomField>
    <fullName>autreLocataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre locataire)</relationshipLabel>
    <relationshipName>autreLocataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreOccupant__c.field-meta.xml
<CustomField>
    <fullName>autreOccupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre occupant)</relationshipLabel>
    <relationshipName>autreOccupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreProprietaire__c.field-meta.xml
<CustomField>
    <fullName>autreProprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre propriétaire)</relationshipLabel>
    <relationshipName>autreProprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/codePostal__c.field-meta.xml
<CustomField>
    <fullName>codePostal__c</fullName>
    <label>Code postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/iris__c.field-meta.xml
<CustomField>
    <fullName>iris__c</fullName>
    <label>Iris</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/locataire__c.field-meta.xml
<CustomField>
    <fullName>locataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du propriétaire</inlineHelpText>
    <label>Locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Locataire)</relationshipLabel>
    <relationshipName>locataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/occupant__c.field-meta.xml
<CustomField>
    <fullName>occupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du locataire</inlineHelpText>
    <label>Occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Occupant)</relationshipLabel>
    <relationshipName>occupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/pays__c.field-meta.xml
<CustomField>
    <fullName>pays__c</fullName>
    <label>Pays</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/proprietaire__c.field-meta.xml
<CustomField>
    <fullName>proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire)</relationshipLabel>
    <relationshipName>proprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/sectorisation__c.field-meta.xml
<CustomField>
    <fullName>sectorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sectorisation</label>
    <referenceTo>Sectorisation__c</referenceTo>
    <relationshipLabel>Chantiers</relationshipLabel>
    <relationshipName>sectorisationChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/typeHabitation__c.field-meta.xml
<CustomField>
    <fullName>typeHabitation__c</fullName>
    <label>Type d&apos;habitation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pavillon</fullName>
            </value>
            <value>
                <fullName>Appartement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/typeResidence__c.field-meta.xml
<CustomField>
    <fullName>typeResidence__c</fullName>
    <label>Type de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Secondaire</fullName>
            </value>
            <value>
                <fullName>Locative</fullName>
            </value>
            <value>
                <fullName>Professionnelle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/ville__c.field-meta.xml
<CustomField>
    <fullName>ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/KContrat__c/KContrat__c.object-meta.xml
<CustomObject>
    <label>Contrat (K)</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats (K)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KContrat__c/fields/chantier__c.field-meta.xml
<CustomField>
    <fullName>chantier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Client chantier du contrat</description>
    <label>Chantier</label>
    <referenceTo>Chantier__c</referenceTo>
    <relationshipLabel>Contrats (K)</relationshipLabel>
    <relationshipName>chantierContrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/dateResiliation__c.field-meta.xml
<CustomField>
    <fullName>dateResiliation__c</fullName>
    <description>Date de résiliation du contrat</description>
    <label>Date de résiliation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/dateSignature__c.field-meta.xml
<CustomField>
    <fullName>dateSignature__c</fullName>
    <description>Date de signature du contrat</description>
    <label>Date de signature</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ReferentielOptions__c/ReferentielOptions__c.object-meta.xml
<CustomObject>
    <label>Référenciel Options</label>
    <nameField>
        <label>Nom de Référentiel Options</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référenciel Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sectorisation__c/Sectorisation__c.object-meta.xml
<CustomObject>
    <label>Sectorisation</label>
    <nameField>
        <label>Nom de Sectorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sectorisation__c/fields/codeDV__c.field-meta.xml
<CustomField>
    <fullName>codeDV__c</fullName>
    <label>Code DV</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/codeMagasin__c.field-meta.xml
<CustomField>
    <fullName>codeMagasin__c</fullName>
    <label>Code magasin</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/IRIS__c.field-meta.xml
<CustomField>
    <fullName>IRIS__c</fullName>
    <externalId>true</externalId>
    <label>IRIS</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleDV__c.field-meta.xml
<CustomField>
    <fullName>libelleDV__c</fullName>
    <label>DV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleMagasin__c.field-meta.xml
<CustomField>
    <fullName>libelleMagasin__c</fullName>
    <externalId>true</externalId>
    <label>Magasin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_TR02x_KContrat.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_TR02x_KContrat
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 02/07/2018
//-- Version     : 1.2
//-- * Optimisation
//-- --------------------------------------------------------------------------------- --
@isTest
private class Test_TR02x_KContrat {
    private static final Id rtB2C = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PERSO_RT);
    private static final Id rtActiviteCommerciale = DAL.getRecordTypeIdByDevName('Event', Constants.ACTIVITE_COMMERCIALE_RT);

    @isTest static void testKContrat() {
     
      User user = getUser();
      update user;

      System.runAs(user) {
        Utils_Test.createGlobalProperties(true, 17, true, true, true, 30, 10, true);
        // Création Sectorisation
        Sectorisation__c sect = Utils_Test.createSectorisation('M123', 'Magasin 123', 'D123', 'Depot 123', true);            
        // Création enregistrements utile
        Account B2C1 = Utils_Test.createAccount('Nom', 'Prénom', 'test@kpark.fr', rtB2C,'Email',false);
        B2C1.personHomePhone = '010203ADGJ';
        B2C1.personMobilePhone = '060203ADGJ';
        B2C1.personOtherPhone = '010204TEST';
        B2C1.phone = '010204MPTW';
        B2C1.fax = '010204MPTW';
        B2C1.Localisation__Latitude__s = 0;
        B2C1.Localisation__Longitude__s = 0;
        B2C1.iris__c = sect.iris__c;
        System.assertNotEquals(null, B2C1.iris__c);

        Account B2C2 = Utils_Test.createAccount('Nom Deux', 'Prénom Deux', 'test2@kpark.fr', rtB2C,'Email',false);
        B2C2.personHomePhone = '010203ADGJ';
        B2C2.personMobilePhone = '060203ADGJ';
        B2C2.personOtherPhone = '010204TEST';
        B2C2.phone = '010204MPTW';
        B2C2.fax = '010204MPTW';
        B2C2.Localisation__Latitude__s = 0;
        B2C2.Localisation__Longitude__s = 0;
        B2C2.iris__c = sect.iris__c;
        System.assertNotEquals(null, B2C2.iris__c);

        List<Account> accounts = new List<Account>();
        accounts.add(B2C1);
        accounts.add(B2C2);
        insert accounts;

        Chantier__c chantier = createChantier(B2C1, null, null, null, null, null, sect);
        insert chantier;

        chantier = ((List<Chantier__c>) SchemaUtils.executeQuery('Chantier__c', chantier.id))[0];

        Opportunity projet = Utils_Test.createOpportunity(B2C1, B2C2, chantier, true);
        projet = ((List<Opportunity>) SchemaUtils.executeQuery('Opportunity', projet.id))[0];
        Opportunity prj = [SELECT Id, Account.contactParDefaut__c FROM Opportunity LIMIT 1];

        // Creation produits / Options référence
        Product2 prod = Utils_Test.createProduct('Produit Test','FFFETT','Fenetre','PVC',50,50,true);
        ReferentielOptions__c refOpt = Utils_Test.createRefOption('RefOption','RefOption','RefOption2',1,true);

        Test.startTest();
        Event event = Utils_Test.createEvent('R1', rtActiviteCommerciale, projet.Id, prj.Account.contactParDefaut__c, user.Id, false);
        event.resultatDuRDV__c = null;
        insert event;

        // Creation devis / qli
        Quote quote = Utils_Test.createQuote('Devis 1', null, projet, Constants.StatutDevisAConfigurer, Date.today(), 1000, 100, true);
        QuoteLineItem qli = Utils_Test.createQuoteLineItem(quote.Id, '1', 30, 100, 2, 56.0, 56.0, prod,false);
        qli.dureeGarantie1__c = 1;
        qli.dureeGarantie2__c = 2;
        qli.dureeGarantie3__c = 3;
        qli.dureeGarantie4__c = 4;
        qli.dureeGarantie5__c = 5;
        qli.dureeGarantie6__c = 6;
        qli.dureeGarantie7__c = 7;
        qli.dureeGarantie8__c = 8;
        qli.dureeGarantie9__c = 9;
        qli.dureeGarantie10__c = 10;
        insert qli;

        Test.stopTest();
        quote = ((List<Quote>) SchemaUtils.executeQuery('Quote', quote.id))[0];

        // Options des produits
        Utils_Test.createOption(qli.Id,'1','Libellé Option 1',refOpt.Id,1,true);

        quote.dateAcceptationClient__c = System.today();
        update quote;

        KContrat__c contrat = Utils_Test.createContrat(quote, true);

        contrat.dateSignature__c = System.today().addYears(-100);
        contrat.dateResiliation__c = System.today();
        update contrat;

        delete contrat;
      }
    }
    
    @isTest static void testKContrat2() {
        Utils_Test.createGlobalProperties(true, 17, true, true, true, 30, 10, true);
        // Création Sectorisation
        Sectorisation__c sect = Utils_Test.createSectorisation('M123', 'Magasin 123', 'D123', 'Depot 123', true);            
        // Création enregistrements utile
        Account B2C1 = Utils_Test.createAccount('Nom', 'Prénom', 'test@kpark.fr', rtB2C,'Email',false);
        B2C1.personHomePhone = '010203ADGJ';
        B2C1.personMobilePhone = '060203ADGJ';
        B2C1.personOtherPhone = '010204TEST';
        B2C1.phone = '010204MPTW';
        B2C1.fax = '010204MPTW';
        B2C1.Localisation__Latitude__s = 0;
        B2C1.Localisation__Longitude__s = 0;
        B2C1.iris__c = sect.iris__c;
        System.assertNotEquals(null, B2C1.iris__c);

        List<Account> accounts = new List<Account>();
        accounts.add(B2C1);
        insert accounts;

        Chantier__c chantier = createChantier(B2C1, null, null, null, null, null, sect);
        insert chantier;

        chantier = ((List<Chantier__c>) SchemaUtils.executeQuery('Chantier__c', chantier.id))[0];

        Opportunity projet = Utils_Test.createOpportunity(B2C1, null, chantier, true);
        projet = ((List<Opportunity>) SchemaUtils.executeQuery('Opportunity', projet.id))[0];
        Opportunity prj = [SELECT Id, Account.contactParDefaut__c FROM Opportunity LIMIT 1];
        Event event = Utils_Test.createEvent('R1', rtActiviteCommerciale, projet.Id, prj.Account.contactParDefaut__c, UserInfo.getUserId(), false);
        event.resultatDuRDV__c = null;
        insert event;

        // Creation devis / qli
        Quote quote = Utils_Test.createQuote('Devis 1', null, projet, Constants.StatutDevisAConfigurer, Date.today(), 1000, 100, true);
        quote = ((List<Quote>) SchemaUtils.executeQuery('Quote', quote.id))[0];

        Test.startTest();

        KContrat__c contrat = Utils_Test.createContrat(quote, true);
        contrat.dateResiliation__c = System.today();
        update contrat;
        
        Test.stopTest();
    }

    private static Chantier__c createChantier(Account proprietaire, Account autreProprietaire, Account locataire, Account autreLocataire, 
                                             Account occupant, Account autreOccupant, Sectorisation__c defaultSectorisation) {
       Chantier__c chantier = new Chantier__c();

       chantier.name = 'CHA - Test';

       chantier.codePostal__c = '76320';
       chantier.ville__c = 'Saint-Pierre les Elbeuf';
       chantier.pays__c = 'F';
       chantier.anneeConstruction__c = '2000';
       chantier.typeHabitation__c = 'Pavillon';
       chantier.typeResidence__c = 'Principale';

       if (proprietaire != null)
         chantier.proprietaire__c = proprietaire.id;
       if (autreProprietaire != null)
         chantier.autreProprietaire__c = autreProprietaire.id;
       if (locataire != null)
         chantier.locataire__c = locataire.id;
       if (autreLocataire != null)
         chantier.autreLocataire__c = autreLocataire.id;
       if (occupant != null)
         chantier.occupant__c = occupant.id;
       if (autreOccupant != null)
         chantier.autreOccupant__c = autreOccupant.id;

       chantier.Localisation__Latitude__s = 0;
       chantier.Localisation__Longitude__s = 0;
       chantier.iris__c = defaultSectorisation.iris__c;

      System.assertNotEquals(null, chantier.iris__c);

      return chantier;
    }
   

    private static User getUser() {
      UserContext context = UserContext.getContext();
      User user = context.getUser();
      if (StringUtils.isEmpty(user.codeMagasin__c))
        user.codeMagasin__c = 'MAG0000';
      if (StringUtils.isEmpty(user.libelleMagasin__c))
        user.codeMagasin__c = 'Magasin 0000';
      if (StringUtils.isEmpty(user.codeDV__c))
        user.codeMagasin__c = 'DV0000';
      if (StringUtils.isEmpty(user.libelleDV__c))
        user.codeMagasin__c = 'DV 0000';
      if (StringUtils.isEmpty(user.codeDR__c))
        user.codeMagasin__c = 'DV0000';
      if (StringUtils.isEmpty(user.libelleDR__c))
        user.codeMagasin__c = 'DV 0000';
      return user;
    }
}