force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/autreLocataire__c.field-meta.xml
<CustomField>
    <fullName>autreLocataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre locataire)</relationshipLabel>
    <relationshipName>autreLocataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreOccupant__c.field-meta.xml
<CustomField>
    <fullName>autreOccupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre occupant)</relationshipLabel>
    <relationshipName>autreOccupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreProprietaire__c.field-meta.xml
<CustomField>
    <fullName>autreProprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre propriétaire)</relationshipLabel>
    <relationshipName>autreProprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/civiliteLocataires__c.field-meta.xml
<CustomField>
    <fullName>civiliteLocataires__c</fullName>
    <label>Civilité (Locataires)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/civiliteOccupants__c.field-meta.xml
<CustomField>
    <fullName>civiliteOccupants__c</fullName>
    <label>Civilité (Occupants)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/civiliteProprietaires__c.field-meta.xml
<CustomField>
    <fullName>civiliteProprietaires__c</fullName>
    <label>Civilité (Propriétaires)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/codePostalLocataires__c.field-meta.xml
<CustomField>
    <fullName>codePostalLocataires__c</fullName>
    <label>Code postal (Locataires)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/codePostalOccupants__c.field-meta.xml
<CustomField>
    <fullName>codePostalOccupants__c</fullName>
    <label>Code postal (Occupants)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/codePostalProprietaires__c.field-meta.xml
<CustomField>
    <fullName>codePostalProprietaires__c</fullName>
    <label>Code postal (Propriétaires)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/departementLocataires__c.field-meta.xml
<CustomField>
    <fullName>departementLocataires__c</fullName>
    <label>Département/Région (Locataires)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/departementOccupants__c.field-meta.xml
<CustomField>
    <fullName>departementOccupants__c</fullName>
    <label>Département/Région (Occupants)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/departementProprietaires__c.field-meta.xml
<CustomField>
    <fullName>departementProprietaires__c</fullName>
    <label>Département/Région (Propriétaires)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/emailLocataires__c.field-meta.xml
<CustomField>
    <fullName>emailLocataires__c</fullName>
    <label>Email (Locataires)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/emailOccupants__c.field-meta.xml
<CustomField>
    <fullName>emailOccupants__c</fullName>
    <label>Email (Occupants)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/emailProprietaires__c.field-meta.xml
<CustomField>
    <fullName>emailProprietaires__c</fullName>
    <label>Email (Propriétaires)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/locataire__c.field-meta.xml
<CustomField>
    <fullName>locataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du propriétaire</inlineHelpText>
    <label>Locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Locataire)</relationshipLabel>
    <relationshipName>locataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/nomLocataires__c.field-meta.xml
<CustomField>
    <fullName>nomLocataires__c</fullName>
    <label>Nom (Locataires)</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/nomOccupants__c.field-meta.xml
<CustomField>
    <fullName>nomOccupants__c</fullName>
    <label>Nom (Occupants)</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/nomProprietaires__c.field-meta.xml
<CustomField>
    <fullName>nomProprietaires__c</fullName>
    <label>Nom (Propriétaires)</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/occupant__c.field-meta.xml
<CustomField>
    <fullName>occupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du locataire</inlineHelpText>
    <label>Occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Occupant)</relationshipLabel>
    <relationshipName>occupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/paysLocataires__c.field-meta.xml
<CustomField>
    <fullName>paysLocataires__c</fullName>
    <label>Pays (Locataires)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/paysOccupants__c.field-meta.xml
<CustomField>
    <fullName>paysOccupants__c</fullName>
    <label>Pays (Occupants)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/paysProprietaires__c.field-meta.xml
<CustomField>
    <fullName>paysProprietaires__c</fullName>
    <label>Pays (Propriétaires)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/prenomLocataires__c.field-meta.xml
<CustomField>
    <fullName>prenomLocataires__c</fullName>
    <label>Prénom (Locataires)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/prenomOccupants__c.field-meta.xml
<CustomField>
    <fullName>prenomOccupants__c</fullName>
    <label>Prénom (Occupants)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/prenomProprietaires__c.field-meta.xml
<CustomField>
    <fullName>prenomProprietaires__c</fullName>
    <label>Prénom (Propriétaires)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/proprietaire__c.field-meta.xml
<CustomField>
    <fullName>proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire)</relationshipLabel>
    <relationshipName>proprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/rueLocataires__c.field-meta.xml
<CustomField>
    <fullName>rueLocataires__c</fullName>
    <label>Rue (Locataires)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/rueOccupants__c.field-meta.xml
<CustomField>
    <fullName>rueOccupants__c</fullName>
    <label>Rue (Occupants)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/rueProprietaires__c.field-meta.xml
<CustomField>
    <fullName>rueProprietaires__c</fullName>
    <label>Rue (Propriétaires)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/telephoneDomicileLocataires__c.field-meta.xml
<CustomField>
    <fullName>telephoneDomicileLocataires__c</fullName>
    <label>Téléphone domicile (Locataires)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/telephoneDomicileOccupants__c.field-meta.xml
<CustomField>
    <fullName>telephoneDomicileOccupants__c</fullName>
    <label>Téléphone domicile (Occupants)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/telephoneDomicileProprietaires__c.field-meta.xml
<CustomField>
    <fullName>telephoneDomicileProprietaires__c</fullName>
    <label>Téléphone domicile (Propriétaires)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/telephoneLocataires__c.field-meta.xml
<CustomField>
    <fullName>telephoneLocataires__c</fullName>
    <label>Téléphone (Locataires)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/telephoneMobileLocataires__c.field-meta.xml
<CustomField>
    <fullName>telephoneMobileLocataires__c</fullName>
    <label>Téléphone mobile (Locataires)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/telephoneMobileOccupants__c.field-meta.xml
<CustomField>
    <fullName>telephoneMobileOccupants__c</fullName>
    <label>Téléphone mobile (Occupants)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/telephoneMobileProprietaires__c.field-meta.xml
<CustomField>
    <fullName>telephoneMobileProprietaires__c</fullName>
    <label>Téléphone mobile (Propriétaires)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/telephoneOccupants__c.field-meta.xml
<CustomField>
    <fullName>telephoneOccupants__c</fullName>
    <label>Téléphone (Occupants)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/telephoneProprietaires__c.field-meta.xml
<CustomField>
    <fullName>telephoneProprietaires__c</fullName>
    <label>Téléphone (Propriétaires)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/villeLocataires__c.field-meta.xml
<CustomField>
    <fullName>villeLocataires__c</fullName>
    <label>Ville (Locataires)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/villeOccupants__c.field-meta.xml
<CustomField>
    <fullName>villeOccupants__c</fullName>
    <label>Ville (Occupants)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/villeProprietaires__c.field-meta.xml
<CustomField>
    <fullName>villeProprietaires__c</fullName>
    <label>Ville (Propriétaires)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TR021_Account.cls
/* ************************************************************************* *
 * Compte personnel & professionnel : Mise à jour des propriétaires,         *
 *                                    locataires et occupants des chantiers  *
 * ************************************************************************* *
 * Version : 1.00                                                            *
 * Date    : 24/04/2013                                                      *
 * ************************************************************************* */

public class TR021_Account {
  private static Boolean enabledForceIndicators = PropertiesUtils.getBooleanValue('function.enabled.forceIndicators', False);
  private static final String ENTITY_RTID = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_ENTITY_RT);
  private static final String PROVIDER_RTID = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PROVIDER_RT);


  public static void UR001_K2_Chantier_setProprietairesLocatairesOccupants(UserContext userContext) {
    if (!Trigger.isExecuting)
      return;

    /** A - Initialisation des données intermédiaires **/


    /** B - Application des règles de mise à jour **/
    Set<ID> accountIds = new Set<ID>();
    if (Trigger.isUpdate) {
      List<Account> newAccounts = new List<Account>();      
      Map<Id, Account> oldAccounts = (Map<Id, Account>)Trigger.oldMap;

      // Récupération seulement des comptes PRO ou PERSO
      for(Account acc : (List<Account>)Trigger.new) {
          if(acc.RecordTypeId != ENTITY_RTID && acc.RecordTypeId != PROVIDER_RTID) {
              newAccounts.add(acc);
          }
      }
                
      for (Account newAccount : newAccounts) {
        Account oldAccount = oldAccounts == null ? null : oldAccounts.get(newAccount.id);
        /**
        if (newAccount.ownerid == oldAccount.ownerid) {   
        **/         
            if (newAccount.isPersonAccount) {
              if ((enabledForceIndicators ||
                   newAccount.salutation != oldAccount.salutation ||
                   newAccount.firstName != oldAccount.firstName ||
                   newAccount.lastName != oldAccount.lastName ||
                   newAccount.personMailingStreet != oldAccount.personMailingStreet ||
                   newAccount.personMailingPostalCode != oldAccount.personMailingPostalCode ||
                   newAccount.personMailingState != oldAccount.personMailingState ||
                   newAccount.personMailingCountry != oldAccount.personMailingCountry ||
                   newAccount.personEmail != oldAccount.personEmail ||
                   newAccount.personHomePhone != oldAccount.personHomePhone ||
                   newAccount.personMobilePhone != oldAccount.personMobilePhone ||
                   newAccount.phone != oldAccount.phone ||
                   newAccount.fichiersOpposition__c != oldAccount.fichiersOpposition__c)
                  &&
                  (!AlreadyUsed.isUsed('TR021_Account', newAccount.id))
                 )
                accountIds.add(oldAccount.id);
            }
            else {
              if ((enabledForceIndicators ||
                   newAccount.name != oldAccount.name ||
                   newAccount.billingStreet != oldAccount.billingStreet ||
                   newAccount.billingPostalCode != oldAccount.billingPostalCode ||
                   newAccount.billingState != oldAccount.billingState ||
                   newAccount.billingCountry != oldAccount.billingCountry ||
                   newAccount.phone != oldAccount.phone ||
                   newAccount.fichiersOpposition__c != oldAccount.fichiersOpposition__c)
                  &&
                  (!AlreadyUsed.isUsed('TR021_Account', newAccount.id))
                 )
                accountIds.add(oldAccount.id);
            }
          /**
          }
          **/          
      }
    }
    else if (Trigger.isDelete) {
      List<Account> oldAccounts = (List<Account>)Trigger.old;
      for (Account oldAccount : oldAccounts) {
        if(oldAccount.RecordTypeId != ENTITY_RTID && oldAccount.RecordTypeId != PROVIDER_RTID) {
          accountIds.add(oldAccount.id);
        }
      }
    }

    if (accountIds.isEmpty())
      return;
    List<Chantier__c> chantiersToUpdate = [SELECT proprietaire__c, autreProprietaire__c, locataire__c, autreLocataire__c, occupant__c, autreOccupant__c,
                                                    civiliteProprietaires__c, nomProprietaires__c, prenomProprietaires__c, rueProprietaires__c, codePostalProprietaires__c, villeProprietaires__c, departementProprietaires__c, paysProprietaires__c, telephoneDomicileProprietaires__c, telephoneMobileProprietaires__c, telephoneProprietaires__c, emailProprietaires__c,
                                                    civiliteLocataires__c, nomLocataires__c, prenomLocataires__c, rueLocataires__c, codePostalLocataires__c, villeLocataires__c, departementLocataires__c, paysLocataires__c, telephoneDomicileLocataires__c, telephoneMobileLocataires__c, telephoneLocataires__c, emailLocataires__c,
                                                    civiliteOccupants__c, nomOccupants__c, prenomOccupants__c, rueOccupants__c, codePostalOccupants__c, villeOccupants__c, departementOccupants__c, paysOccupants__c, telephoneDomicileOccupants__c, telephoneMobileOccupants__c, telephoneOccupants__c, emailOccupants__c
                                           FROM Chantier__c
                                           WHERE proprietaire__c      IN :accountIds
                                              OR autreProprietaire__c IN :accountIds
                                              OR locataire__c         IN :accountIds
                                              OR autreLocataire__c    IN :accountIds
                                              OR occupant__c          IN :accountIds
                                              OR autreOccupant__c     IN :accountIds];
    if (chantiersToUpdate != null && !chantiersToUpdate.isEmpty()) {
      TR020_Chantier.setProprietairesLocatairesOccupants(chantiersToUpdate);
      update chantiersToUpdate;
    }
  }
}