force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/legacyReference__c.field-meta.xml
<CustomField>
    <fullName>legacyReference__c</fullName>
    <description>REPRISE HISTO : Champ stockant le numéro issu de la GC</description>
    <externalId>true</externalId>
    <label>[#] Reprise d&apos;historique (Référence)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/serviceEntity__c.field-meta.xml
<CustomField>
    <fullName>serviceEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dépôt (Entité service)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entités service (Chantier)</relationshipLabel>
    <relationshipName>ChantierServiceEntities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/CreditMemo__c.object-meta.xml
<CustomObject>
    <description>Gestion des avoirs basée sur la modélisation des avoirs du modules Salesforce Billing</description>
    <label>Avoir</label>
    <nameField>
        <displayFormat>AVR/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de l’avoir</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avoirs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditMemo__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/autoComputedAmount__c.field-meta.xml
<CustomField>
    <fullName>autoComputedAmount__c</fullName>
    <defaultValue>true</defaultValue>
    <label>[#] Montant auto calculé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/creditMemoDate__c.field-meta.xml
<CustomField>
    <fullName>creditMemoDate__c</fullName>
    <label>Date de l&apos;avoir</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/creditMemoReference__c.field-meta.xml
<CustomField>
    <fullName>creditMemoReference__c</fullName>
    <externalId>true</externalId>
    <label>Référence de l’avoir</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>CreditMemos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>Avoirs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/pretaxAmount__c.field-meta.xml
<CustomField>
    <fullName>pretaxAmount__c</fullName>
    <label>Montant (HT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <defaultValue>&apos;Brouillon&apos;</defaultValue>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
            </value>
            <value>
                <fullName>Validé</fullName>
            </value>
            <value>
                <fullName>Publié</fullName>
            </value>
            <value>
                <fullName>Acquitté</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/CreditMemoLine__c.object-meta.xml
<CustomObject>
    <description>Ligne d&apos;avoir basée sur la modélisation des factures du module Salesforce Billing</description>
    <label>Ligne d&apos;avoir</label>
    <nameField>
        <displayFormat>LAVR/{YYYY}/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;avoir</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditMemoLine__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant total (TTC)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/creditMemo__c.field-meta.xml
<CustomField>
    <fullName>creditMemo__c</fullName>
    <label>Avoir</label>
    <referenceTo>CreditMemo__c</referenceTo>
    <relationshipLabel>Lignes d&apos;avoir</relationshipLabel>
    <relationshipName>CreditMemoLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Lignes d&apos;avoir</relationshipLabel>
    <relationshipName>CreditMemoLines_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <label>Libellé de la ligne</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/legacyReference__c.field-meta.xml
<CustomField>
    <fullName>legacyReference__c</fullName>
    <externalId>true</externalId>
    <label>[#] Reprise d&apos;historique (Référence)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/pretaxAmount__c.field-meta.xml
<CustomField>
    <fullName>pretaxAmount__c</fullName>
    <label>Montant total (HT)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/quantity__c.field-meta.xml
<CustomField>
    <fullName>quantity__c</fullName>
    <label>Quantité</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/reason__c.field-meta.xml
<CustomField>
    <fullName>reason__c</fullName>
    <label>Motif d&apos;avoir</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annulation facture</fullName>
            </value>
            <value>
                <fullName>Avoir commercial</fullName>
            </value>
            <value>
                <fullName>Avoir technique</fullName>
            </value>
            <value>
                <fullName>Défaut KparK</fullName>
            </value>
            <value>
                <fullName>Défaut usine</fullName>
            </value>
            <value>
                <fullName>Erreur Métrage</fullName>
            </value>
            <value>
                <fullName>Modification contrat</fullName>
            </value>
            <value>
                <fullName>Motif Administratif</fullName>
            </value>
            <value>
                <fullName>Prestation non-conforme</fullName>
            </value>
            <value>
                <fullName>Protocole avec avoir</fullName>
            </value>
            <value>
                <fullName>Retard livraison</fullName>
            </value>
            <value>
                <fullName>Retard installation KparK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/unitPrice__c.field-meta.xml
<CustomField>
    <fullName>unitPrice__c</fullName>
    <label>Prix unitaire (HT)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/VATAmount__c.field-meta.xml
<CustomField>
    <fullName>VATAmount__c</fullName>
    <label>Montant TVA</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/VATRate__c.field-meta.xml
<CustomField>
    <fullName>VATRate__c</fullName>
    <label>Taux TVA</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Gestion des factures basée sur la modélisation du module Salesforce Billing</description>
    <label>Facture</label>
    <nameField>
        <displayFormat>FAC/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de la facture</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Order.RecordTypeId</field>
            <operation>equals</operation>
            <value>Commande client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/pretaxAmount__c.field-meta.xml
<CustomField>
    <fullName>pretaxAmount__c</fullName>
    <label>Montant (HT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <defaultValue>&apos;Brouillon&apos;</defaultValue>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brouillon</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>Acquittée</fullName>
            </value>
            <value>
                <fullName>Retard de paiement</fullName>
            </value>
            <value>
                <fullName>Annulée</fullName>
            </value>
            <value>
                <fullName>Publiée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VATAmount__c.field-meta.xml
<CustomField>
    <fullName>VATAmount__c</fullName>
    <formula>VATAmount1__c + VATAmount2__c + VATAmount3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant TVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/IV_InsertCommercialCreditMemo.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : IV_InsertCommercialCreditMemo
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 10/02/2022
//-- Version     : 1.0
//-- * 1.0 - Init
//-- --------------------------------------------------------------------------------- --
public class IV_InsertCommercialCreditMemo {
    private static final String CREDITMEMO_INVOICECREDITMEMO_RTID = DAL.getRecordTypeIdByDevName('CreditMemo__c', Constants.CREDITMEMO_INVOICECREDITMEMO_RT);
    private static final String CREDITMEMO_COMMERCIALCREDITMEMO_RTID = DAL.getRecordTypeIdByDevName('CreditMemo__c', Constants.CREDITMEMO_COMMERCIALCREDITMEMO_RT);
        
    @InvocableMethod(label='Action Avoir Commercial')
    public static List<FlowOutputParameters> insertCommercialCreditMemo(List<FlowInputParameters> inputList) {
        System.debug('### DEBUT IV_InsertCommercialCreditMemo.insertCommercialCreditMemo');
        List<FlowOutputParameters> outputList = new List<FlowOutputParameters>();
        Order order = null;

        // Sauvegarde
        System.Savepoint sp = Database.setSavepoint();
        
        try{
            String recordId = inputList[0].recordId;
            if(String.isBlank(recordId)) {                
                throw new FlowActionException('Id de l\'enregistrement inexistante');
            }
            Date creditMemoDate = inputList[0].creditMemoDate;
            String invoiceId = inputList[0].invoiceId;

            order = [SELECT Id, AccountId, serviceEntity__r.ParentId, serviceEntity__c, chantier__c, SBQQ__Quote__c,
                    SBQQ__Quote__r.montantTVAReduite__c, SBQQ__Quote__r.montantTVAIntermediaire__c,
                    SBQQ__Quote__r.tauxTVAReduite__c, SBQQ__Quote__r.tauxTVAIntermediaire__c, SBQQ__Quote__r.tauxTVAFort__c,
                    quote.tvaReduite__c, quote.tvaIntermediaire__c
                    FROM Order WHERE Id =: recordId];
            
            // Création avoir
            CreditMemo__c creditMemo = new CreditMemo__c();
            creditMemo.recordTypeId = CREDITMEMO_COMMERCIALCREDITMEMO_RTID;
            creditMemo.OwnerId = Label.System_id_user_kpark;
            creditMemo.status__c = Constants.CREDITMEMO_BROUILLON;
            creditMemo.customerOrder__c = recordId;
            creditMemo.autoComputedAmount__c = true;
            System.debug('## CreditMemo: '+creditMemo);    

            insert creditMemo;
            
            // 2 – Alimentation des lignes d'avoir
            // L'avoir annule la totalité des lignes (de 1er niveau de la facture / sans parent) => Recopie des données de la ligne de facture
            CreditMemoLine__c creditMemoLine = new CreditMemoLine__c();
            
            creditMemoLine.creditMemo__c = creditMemo.Id;
            creditMemoLine.lineNumber__c = 1;
            creditMemoLine.reason__c = inputList[0].reason;
            creditMemoLine.label__c = String.isBlank(inputList[0].description) ? 'Avoir commercial' : inputList[0].description;
            //creditMemoLine.description__c = invoiceLine.description__c;
            
            // Elements comptables
            creditMemoLine.amount__c = inputList[0].amount;
            if(order != null && order.SBQQ__Quote__c != null) {
                if(order.SBQQ__Quote__r.montantTVAReduite__c > 0) {
                    creditMemoLine.VATRate__c = order.SBQQ__Quote__r.tauxTVAReduite__c;
                } else if(order.SBQQ__Quote__r.montantTVAIntermediaire__c > 0) {
                    creditMemoLine.VATRate__c = order.SBQQ__Quote__r.tauxTVAIntermediaire__c;
                } else {
                    creditMemoLine.VATRate__c = order.SBQQ__Quote__r.tauxTVAFort__c;
                }
            } else if(order != null && order.quote != null) {
                if(order.quote.tvaReduite__c > 0) {
                    creditMemoLine.VATRate__c = 5.5;
                } else if(order.quote.tvaIntermediaire__c > 0) {
                    creditMemoLine.VATRate__c = 10;
                } else {
                    creditMemoLine.VATRate__c = 20;
                }
            } else { // Pour les test
                creditMemoLine.VATRate__c = 5.5;
            }
            creditMemoLine.pretaxAmount__c = creditMemoLine.amount__c / (1+(creditMemoLine.VATRate__c/100)); // HT = TTC / [1 + (taux de TVA / 100)]
            creditMemoLine.VATAmount__c = creditMemoLine.amount__c - creditMemoLine.pretaxAmount__c;
            creditMemoLine.unitPrice__c = creditMemoLine.pretaxAmount__c;
            creditMemoLine.quantity__c = 1;
            creditMemoLine.unit__c = 'UNIT';
            creditMemoLine.invoice__c = invoiceId;
            
            // Reprise d'historique
            creditMemoLine.legacyReference__c = null;
            
            insert creditMemoLine;
            
            // 3 – Validation de l'avoir
            if(creditMemoDate != null) {
                creditMemo.creditMemoDate__c = creditMemoDate;
                update creditMemo; // L’algo alimentera automatiquement le n° fiscal creditMemoReference__c et passera le statut à Validé
            } 

            // Alimentation variable de sortie
            FlowOutputParameters out = new FlowOutputParameters();
            out.creditMemoId = creditMemo.Id;
            out.creditMemoName = creditMemo.Name;
            outputList.add(out);
            
            System.debug('### FIN IV_InsertCommercialCreditMemo.insertCommercialCreditMemo');
            return outputList;
        }catch(Exception e){
            Database.rollback(sp);
            System.debug('ERREUR : ' + e.getMessage() + ' ' + e.getTypeName() + ' ' + e.getStackTraceString());
            throw e;
        }
    }
    
    /* Input parameters for the Apex action */
    public class FlowInputParameters{
        @InvocableVariable(label='Id de l\'enregistrement associé' required = true )
        public String recordId;
        @InvocableVariable(label='Montant de l\'avoir' required = true )
        public Decimal amount;
        @InvocableVariable(label='Motif de l\'avoir' required = true )
        public String reason;
        @InvocableVariable(label='Libellé de la ligne d\'avoir' required = false )
        public String description;
        @InvocableVariable(label='Date de l\'avoir' required = false )
        public Date creditMemoDate;
        @InvocableVariable(label='Id de la facture' required = false )
        public String invoiceId;
    }
    
    /* Output parameters of the Apex action */
    public class FlowOutputParameters{
        @InvocableVariable(label='Id de l\'avoir')
        public String creditMemoId;
        @InvocableVariable(label='Nom de l\'avoir')
        public String creditMemoName;
    }

    public class FlowActionException extends Exception {}
}