force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/serviceEntity__c.field-meta.xml
<CustomField>
    <fullName>serviceEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dépôt (Entité service)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entités service (Chantier)</relationshipLabel>
    <relationshipName>ChantierServiceEntities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/CreditMemo__c.object-meta.xml
<CustomObject>
    <description>Gestion des avoirs basée sur la modélisation des avoirs du modules Salesforce Billing</description>
    <label>Avoir</label>
    <nameField>
        <displayFormat>AVR/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de l’avoir</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avoirs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditMemo__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>CreditMemos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>Avoirs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/pretaxAmount__c.field-meta.xml
<CustomField>
    <fullName>pretaxAmount__c</fullName>
    <label>Montant (HT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/CreditMemoLine__c.object-meta.xml
<CustomObject>
    <description>Ligne d&apos;avoir basée sur la modélisation des factures du module Salesforce Billing</description>
    <label>Ligne d&apos;avoir</label>
    <nameField>
        <displayFormat>LAVR/{YYYY}/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;avoir</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditMemoLine__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant total (TTC)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/asset__c.field-meta.xml
<CustomField>
    <fullName>asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actif</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Lignes d&apos;avoir</relationshipLabel>
    <relationshipName>CreditMemoLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/creditMemo__c.field-meta.xml
<CustomField>
    <fullName>creditMemo__c</fullName>
    <label>Avoir</label>
    <referenceTo>CreditMemo__c</referenceTo>
    <relationshipLabel>Lignes d&apos;avoir</relationshipLabel>
    <relationshipName>CreditMemoLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Lignes d&apos;avoir</relationshipLabel>
    <relationshipName>CreditMemoLines_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/invoiceLine__c.field-meta.xml
<CustomField>
    <fullName>invoiceLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne de la facture</label>
    <referenceTo>InvoiceLine__c</referenceTo>
    <relationshipLabel>Lignes d&apos;avoir</relationshipLabel>
    <relationshipName>CreditMemoLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <label>Libellé de la ligne</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/orderItem__c.field-meta.xml
<CustomField>
    <fullName>orderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne de commande client</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Lignes d&apos;avoir</relationshipLabel>
    <relationshipName>CreditMemoLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/pretaxAmount__c.field-meta.xml
<CustomField>
    <fullName>pretaxAmount__c</fullName>
    <label>Montant total (HT)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lignes d&apos;avoir</relationshipLabel>
    <relationshipName>CreditMemoLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/quantity__c.field-meta.xml
<CustomField>
    <fullName>quantity__c</fullName>
    <label>Quantité</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/unitPrice__c.field-meta.xml
<CustomField>
    <fullName>unitPrice__c</fullName>
    <label>Prix unitaire (HT)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/VATAmount__c.field-meta.xml
<CustomField>
    <fullName>VATAmount__c</fullName>
    <label>Montant TVA</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemoLine__c/fields/VATRate__c.field-meta.xml
<CustomField>
    <fullName>VATRate__c</fullName>
    <label>Taux TVA</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Gestion des factures basée sur la modélisation du module Salesforce Billing</description>
    <label>Facture</label>
    <nameField>
        <displayFormat>FAC/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de la facture</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Order.RecordTypeId</field>
            <operation>equals</operation>
            <value>Commande client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/pretaxAmount__c.field-meta.xml
<CustomField>
    <fullName>pretaxAmount__c</fullName>
    <label>Montant (HT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VATAmount__c.field-meta.xml
<CustomField>
    <fullName>VATAmount__c</fullName>
    <formula>VATAmount1__c + VATAmount2__c + VATAmount3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant TVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Facture</label>
</RecordType>

force-app/main/default/objects/InvoiceLine__c/InvoiceLine__c.object-meta.xml
<CustomObject>
    <description>Ligne de facture basée sur la modélisation des factures du module Salesforce Billing</description>
    <label>Ligne de facture</label>
    <nameField>
        <displayFormat>LFAC/{YYYY}/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de facture</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLine__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant total (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/asset__c.field-meta.xml
<CustomField>
    <fullName>asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actif</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <label>Facture</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.isParentLine__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/location__c.field-meta.xml
<CustomField>
    <fullName>location__c</fullName>
    <label>Emplacement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/orderItem__c.field-meta.xml
<CustomField>
    <fullName>orderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne de la commande client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OrderItem.orderRecordType__c</field>
            <operation>equals</operation>
            <value>CustomerOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/pretaxAmount__c.field-meta.xml
<CustomField>
    <fullName>pretaxAmount__c</fullName>
    <label>Montant total (HT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/quantity__c.field-meta.xml
<CustomField>
    <fullName>quantity__c</fullName>
    <label>Quantité</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/unit__c.field-meta.xml
<CustomField>
    <fullName>unit__c</fullName>
    <defaultValue>&quot;UNIT&quot;</defaultValue>
    <label>Unité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UnitType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/unitPrice__c.field-meta.xml
<CustomField>
    <fullName>unitPrice__c</fullName>
    <label>Prix unitaire (HT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/VATAmount__c.field-meta.xml
<CustomField>
    <fullName>VATAmount__c</fullName>
    <label>Montant TVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/VATRate__c.field-meta.xml
<CustomField>
    <fullName>VATRate__c</fullName>
    <label>Taux TVA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/IV_InsertCreditMemoFromInvoiceLine.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : IV_InsertCreditMemoFromInvoiceLine
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 10/02/2022
//-- Version     : 1.0
//-- * 1.0 - Init
//-- --------------------------------------------------------------------------------- --
public without sharing class IV_InsertCreditMemoFromInvoiceLine {
    private static final String CREDITMEMO_INVOICECREDITMEMO_RTID = DAL.getRecordTypeIdByDevName('CreditMemo__c', Constants.CREDITMEMO_INVOICECREDITMEMO_RT);
    private static final String CREDITMEMO_COMMERCIALCREDITMEMO_RTID = DAL.getRecordTypeIdByDevName('CreditMemo__c', Constants.CREDITMEMO_COMMERCIALCREDITMEMO_RT);
        
    /**
    * @description Action de création d'un avoir depuis une ligne de facture
    * @param inputList Liste des paramètres d'entrée provenant du Flow
    */
    @InvocableMethod(label='Action Avoir depuis ligne de facture')
    public static List<FlowOutputParameters> insertCreditMemoFromInvoiceLine(List<FlowInputParameters> inputList) {
        System.debug('### DEBUT IV_InsertCreditMemoFromInvoiceLine.insertCreditMemoFromInvoiceLine');
        List<FlowOutputParameters> outputList = new List<FlowOutputParameters>();
        String invoiceLineId = inputList[0].invoiceLineId;
        Date creditMemoDate = inputList[0].creditMemoDate;
        InvoiceLine__c invoiceLine;
        System.debug('## invoiceLineId: '+invoiceLineId);
        System.debug('## creditMemoDate: '+creditMemoDate);

        // Sauvegarde
        System.Savepoint sp = Database.setSavepoint();

        try{
            if(String.isBlank(invoiceLineId)) {                
                throw new FlowActionException('Id de ligne de facture inexistante');
            }

            // Récupération facture et ligne
            List<InvoiceLine__c> invoiceLineList = [SELECT Id, invoice__c, label__c, product__c, asset__c, orderItem__c, pretaxAmount__c, VATRate__c, VATAmount__c,
                                                    quantity__c, unit__c, unitPrice__c, amount__c, location__c 
                                                    FROM InvoiceLine__c WHERE Id =: invoiceLineId];
            if(invoiceLineList.isEmpty()) {                
                throw new FlowActionException('Ligne de facture inexistante');
            } else {
                invoiceLine = invoiceLineList[0];
            }
        
            Invoice__c invoice = [SELECT Id, customerOrder__c, customerOrder__r.serviceEntity__c, customerOrder__r.chantier__c, billingAccount__c, 
                              customerOrder__r.serviceEntity__r.ParentId, workOrder__c
                              FROM Invoice__c WHERE Id =:invoiceLine.invoice__c];

            // Création avoir
            CreditMemo__c creditMemo = new CreditMemo__c();
            creditMemo.recordTypeId = CREDITMEMO_INVOICECREDITMEMO_RTID;
            creditMemo.OwnerId = Label.System_id_user_kpark;
            creditMemo.customerOrder__c = invoice.customerOrder__c;
            creditMemo.invoice__c = invoice.Id;
            creditMemo.status__c = Constants.CREDITMEMO_BROUILLON;
            creditMemo.workOrder__c = invoice.workOrder__c;
            creditMemo.autoComputedAmount__c = true;
            System.debug('## CreditMemo: '+creditMemo);     
            insert creditMemo;
            
            // 2 – Alimentation des lignes de facture
            // L'avoir annule la totalité des lignes (de 1er niveau de la facture / sans parent) => Recopie des données de la ligne de facture
            CreditMemoLine__c creditMemoLine = new CreditMemoLine__c();

            creditMemoLine.creditMemo__c = creditMemo.Id;
            creditMemoLine.lineNumber__c =0;
            creditMemoLine.reason__c = 'Annulation facture';
            creditMemoLine.label__c = invoiceLine.label__c;
            creditMemoLine.unitPrice__c = invoiceLine.unitPrice__c;
            creditMemoLine.invoice__c = invoiceLine.invoice__c;
            creditMemoLine.invoiceLine__c = invoiceLine.id;
            creditMemoLine.product__c = invoiceLine.product__c;
            creditMemoLine.asset__c = invoiceLine.asset__c;
            creditMemoLine.orderItem__c = invoiceLine.orderItem__c;
            creditMemoLine.location__c = invoiceLine.location__c;
            // Elements comptables
            creditMemoLine.pretaxAmount__c = invoiceLine.pretaxAmount__c;
            creditMemoLine.VATRate__c = invoiceLine.VATRate__c;
            creditMemoLine.VATAmount__c = invoiceLine.VATAmount__c;
            creditMemoLine.amount__c = invoiceLine.amount__c;
            creditMemoLine.quantity__c = invoiceLine.quantity__c;
            creditMemoLine.unit__c = invoiceLine.unit__c;

            System.debug('## CreditMemoLine: '+creditMemoLine);               
            insert creditMemoLine;
            
            // 3 – Validation de l'avoir
            if(creditMemoDate != null) {
                creditMemo.creditMemoDate__c = creditMemoDate;
                update creditMemo; // L’algo alimentera automatiquement le n° fiscal creditMemoReference__c et passera le statut à Validé
            }

            // Alimentation variable de sortie
            FlowOutputParameters out = new FlowOutputParameters();
            out.creditMemoId = creditMemo.Id;
            out.creditMemoName = creditMemo.Name;
            outputList.add(out);
            
            System.debug('### FIN IV_InsertCreditMemoFromInvoiceLine.insertCreditMemoFromInvoiceLine');
            return outputList;
        }catch(Exception e){
            Database.rollback(sp);
            System.debug('ERREUR : ' + e.getMessage() + ' ' + e.getTypeName() + ' ' + e.getStackTraceString());
            throw e;
        }
    }
    
    /* Input parameters for the Apex action */
    public class FlowInputParameters{
        @InvocableVariable(label='Id de l\'objet ligne de facture' required = true )
        public String invoiceLineId;
        @InvocableVariable(label='Date de l\'avoir' required = false )
        public Date creditMemoDate;
    }
    
    /* Output parameters of the Apex action */
    public class FlowOutputParameters{
        @InvocableVariable(label='Id de l\'avoir')
        public String creditMemoId;
        @InvocableVariable(label='Nom de l\'avoir')
        public String creditMemoName;
    }

    public class FlowActionException extends Exception {}
}