force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/anneeConstruction__c.field-meta.xml
<CustomField>
    <fullName>anneeConstruction__c</fullName>
    <label>Année de construction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NSP</fullName>
            </value>
            <value>
                <fullName>Avant 1940</fullName>
            </value>
            <value>
                <fullName>1950</fullName>
            </value>
            <value>
                <fullName>1960</fullName>
            </value>
            <value>
                <fullName>1970</fullName>
            </value>
            <value>
                <fullName>1980</fullName>
            </value>
            <value>
                <fullName>1990</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2010+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreLocataire__c.field-meta.xml
<CustomField>
    <fullName>autreLocataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre locataire)</relationshipLabel>
    <relationshipName>autreLocataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreOccupant__c.field-meta.xml
<CustomField>
    <fullName>autreOccupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre occupant)</relationshipLabel>
    <relationshipName>autreOccupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreProprietaire__c.field-meta.xml
<CustomField>
    <fullName>autreProprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre propriétaire)</relationshipLabel>
    <relationshipName>autreProprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/codePostal__c.field-meta.xml
<CustomField>
    <fullName>codePostal__c</fullName>
    <label>Code postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/iris__c.field-meta.xml
<CustomField>
    <fullName>iris__c</fullName>
    <label>Iris</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/locataire__c.field-meta.xml
<CustomField>
    <fullName>locataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du propriétaire</inlineHelpText>
    <label>Locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Locataire)</relationshipLabel>
    <relationshipName>locataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/occupant__c.field-meta.xml
<CustomField>
    <fullName>occupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du locataire</inlineHelpText>
    <label>Occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Occupant)</relationshipLabel>
    <relationshipName>occupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/pays__c.field-meta.xml
<CustomField>
    <fullName>pays__c</fullName>
    <label>Pays</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/proprietaire__c.field-meta.xml
<CustomField>
    <fullName>proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire)</relationshipLabel>
    <relationshipName>proprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/rue__c.field-meta.xml
<CustomField>
    <fullName>rue__c</fullName>
    <label>Rue</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/sectorisation__c.field-meta.xml
<CustomField>
    <fullName>sectorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sectorisation</label>
    <referenceTo>Sectorisation__c</referenceTo>
    <relationshipLabel>Chantiers</relationshipLabel>
    <relationshipName>sectorisationChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/typeHabitation__c.field-meta.xml
<CustomField>
    <fullName>typeHabitation__c</fullName>
    <label>Type d&apos;habitation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pavillon</fullName>
            </value>
            <value>
                <fullName>Appartement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/typeResidence__c.field-meta.xml
<CustomField>
    <fullName>typeResidence__c</fullName>
    <label>Type de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Secondaire</fullName>
            </value>
            <value>
                <fullName>Locative</fullName>
            </value>
            <value>
                <fullName>Professionnelle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/ville__c.field-meta.xml
<CustomField>
    <fullName>ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/x__c.field-meta.xml
<CustomField>
    <fullName>x__c</fullName>
    <label>X</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/y__c.field-meta.xml
<CustomField>
    <fullName>y__c</fullName>
    <label>Y</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/KContrat__c/KContrat__c.object-meta.xml
<CustomObject>
    <label>Contrat (K)</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats (K)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KContrat__c/fields/autreCompte__c.field-meta.xml
<CustomField>
    <fullName>autreCompte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats (K) (Autre compte)</relationshipLabel>
    <relationshipName>autreCompteContrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/chantier__c.field-meta.xml
<CustomField>
    <fullName>chantier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Client chantier du contrat</description>
    <label>Chantier</label>
    <referenceTo>Chantier__c</referenceTo>
    <relationshipLabel>Contrats (K)</relationshipLabel>
    <relationshipName>chantierContrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/compte__c.field-meta.xml
<CustomField>
    <fullName>compte__c</fullName>
    <description>Client signataire du contrat</description>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats (K)</relationshipLabel>
    <relationshipName>compteContrats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/dateSignature__c.field-meta.xml
<CustomField>
    <fullName>dateSignature__c</fullName>
    <description>Date de signature du contrat</description>
    <label>Date de signature</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/devis__c.field-meta.xml
<CustomField>
    <fullName>devis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Devis de référence pour la création du contrat</description>
    <label>Devis</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>devisContrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/libelleStatutContrat__c.field-meta.xml
<CustomField>
    <fullName>libelleStatutContrat__c</fullName>
    <description>Statut du contrat</description>
    <externalId>true</externalId>
    <label>Statut du contrat</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/montantECS__c.field-meta.xml
<CustomField>
    <fullName>montantECS__c</fullName>
    <description>Ecart de cotation service en valeur</description>
    <label>Montant de l&apos;ECS</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/montantHT__c.field-meta.xml
<CustomField>
    <fullName>montantHT__c</fullName>
    <description>Montant HT du contrat</description>
    <label>Montant HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/montantTTC__c.field-meta.xml
<CustomField>
    <fullName>montantTTC__c</fullName>
    <description>Montant TTC du contrat</description>
    <label>Montant TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/numeroContrat__c.field-meta.xml
<CustomField>
    <fullName>numeroContrat__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Numéro de contrat</description>
    <externalId>true</externalId>
    <label>N° contrat</label>
    <length>14</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/KInstance__c/KInstance__c.object-meta.xml
<CustomObject>
    <label>Instance en cours (K)</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances en cours (K)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KInstance__c/fields/contrat__c.field-meta.xml
<CustomField>
    <fullName>contrat__c</fullName>
    <label>Contrat</label>
    <referenceTo>KContrat__c</referenceTo>
    <relationshipName>contratInstances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KInstance__c/fields/dateEcheance__c.field-meta.xml
<CustomField>
    <fullName>dateEcheance__c</fullName>
    <label>Date d&apos;échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KInstance__c/fields/dateEntree__c.field-meta.xml
<CustomField>
    <fullName>dateEntree__c</fullName>
    <label>Date d&apos;entrée</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KInstance__c/fields/dateSortie__c.field-meta.xml
<CustomField>
    <fullName>dateSortie__c</fullName>
    <label>Date de sortie</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KInstance__c/fields/nInstance__c.field-meta.xml
<CustomField>
    <fullName>nInstance__c</fullName>
    <externalId>true</externalId>
    <label>N° instance</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sectorisation__c/Sectorisation__c.object-meta.xml
<CustomObject>
    <label>Sectorisation</label>
    <nameField>
        <label>Nom de Sectorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sectorisation__c/fields/codeDV__c.field-meta.xml
<CustomField>
    <fullName>codeDV__c</fullName>
    <label>Code DV</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/codeMagasin__c.field-meta.xml
<CustomField>
    <fullName>codeMagasin__c</fullName>
    <label>Code magasin</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/IRIS__c.field-meta.xml
<CustomField>
    <fullName>IRIS__c</fullName>
    <externalId>true</externalId>
    <label>IRIS</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleDV__c.field-meta.xml
<CustomField>
    <fullName>libelleDV__c</fullName>
    <label>DV</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleMagasin__c.field-meta.xml
<CustomField>
    <fullName>libelleMagasin__c</fullName>
    <externalId>true</externalId>
    <label>Magasin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_TR02x_KInstance.cls
@isTest(SeeAllData=true)
private class Test_TR02x_KInstance {
    
    private static final RecordType rtB2B    = [SELECT id FROM RecordType WHERE name = 'Compte professionnel' LIMIT 1];
    private static final RecordType rtB2C    = [SELECT id FROM RecordType WHERE name = 'Compte personnel' LIMIT 1];
    private static final RecordType rtRDV    = [SELECT id FROM RecordType WHERE name = 'FRA- Activité commerciale' LIMIT 1];
    private static final RecordType rtDEVIS  = [SELECT id FROM RecordType WHERE name = 'FRA- Devis A configurer' LIMIT 1];
    
    private static final Sectorisation__c defaultSectorisation = TestCommon.createSectorisation();
    
    static testMethod void testKInstance() {
        insert defaultSectorisation;
        User user = getUser();
        update user;
        
        System.runAs(user) {
            Account B2C1 = createAccountB2C();
            Account B2C2 = createAccountB2C();
            
            List<Account> accounts = new List<Account>();
            accounts.add(B2C1);
            accounts.add(B2C2);
            insert accounts;
            
            Map<Id, Account> accountMap = new Map<Id, Account>((List<Account>) SchemaUtils.executeQuery('Account', IDUtils.getIDs(accounts)));
            B2C1 = accountMap.get(B2C1.id);
            B2C2 = accountMap.get(B2C2.id);
            
            
            // Creation produits
            Product2 prod = Utils_Test.createProduct('Produit Test','FFFETT','Fenetre','PVC',50,50,true);
            Pricebook2 pBook = new Pricebook2(Name ='Test');
            insert pBook;
            PricebookEntry priceBookEntry = new PricebookEntry(UnitPrice = 125, Pricebook2Id = pBook.Id, Product2Id = prod.Id, IsActive = true);
            insert priceBookEntry;
            
            Chantier__c chantier = createChantier(B2C1, null, null, null, null, null);
            insert chantier;
            
            chantier = ((List<Chantier__c>) SchemaUtils.executeQuery('Chantier__c', chantier.id))[0];
            
            Opportunity projet = createOpportunity(B2C1, B2C2, chantier);
            
            insert projet;
            
            projet = ((List<Opportunity>) SchemaUtils.executeQuery('Opportunity', projet.id))[0];
            
            Test.startTest();
            Event event = createEvent(projet, B2C1);
            event.resultatDuRDV__c = null;
            
            insert event;
            
            
            Quote quote = createQuote(projet);
            quote.moyenTransmissionClient__c = 'Par email';
            quote.delaiInstallationMax__c = 2;
            quote.delaiInstallationMin__c = 2;
            
            insert quote;
            
            QuoteLineItem qli = Utils_Test.createQuoteLineItem(quote.Id, '2', 180, 180,1,300, 200, priceBookEntry.Id, true);
            
            
            quote.dateAcceptationClient__c = date.today();
            update quote;
            
            Test.stopTest();
            quote = ((List<Quote>) SchemaUtils.executeQuery('Quote', quote.id))[0];
            
            KContrat__c contrat = createKContrat(B2C1, B2C2, chantier, quote);
            
            insert contrat;
            
            KInstance__c instance = createKInstance(contrat);
            
            insert instance;
            
            
            
            instance.actif__c = True;
            instance.dateSortie__c = null;
            instance.statut__c = 'En cours';
            update instance;
            
            delete instance;
            
            
        }
    }
    
    private static Account createAccountB2B() {
        Account account = new Account(recordTypeId = rtB2B.id);
        
        account.name = 'Compte professionnel';
        account.accountCallSource__c = '15 - Campagne Marketing';
        account.billingStreet = '1200 rue félix faure';
        account.billingPostalCode = '76320';
        account.billingCity = 'Caudebec les Elbeuf';
        account.billingCountry = 'F';
        account.phone = '010203ADGJ';
        account.fax = '010204MPTW';
        
        account.x__c = 0;
        account.y__c = 0;
        account.Localisation__Latitude__s = 0;
        account.Localisation__Longitude__s = 0;
        account.iris__c = defaultSectorisation.iris__c;
        
        System.assertNotEquals(null, account.iris__c);
        
        return account;
    }
    
    private static Account createAccountB2C() {
        Account account = new Account(recordTypeId = rtB2C.id);
        
        account.salutation = 'M.';
        account.lastName = 'Nom';
        account.firstName = 'Prénom';
        account.accountCallSource__c = '17 - JPO';
        account.personMailingStreet = '1 rue félix faure';
        account.personMailingPostalCode = '76320';
        account.personMailingCity = 'Saint-Pierre les Elbeuf';
        account.personMailingCountry = 'F';
        account.personHomePhone = '010203ADGJ';
        account.personMobilePhone = '060203ADGJ';
        account.personOtherPhone = '010204TEST';
        account.phone = '010204MPTW';
        account.fax = '010204MPTW';
        account.personEmail = 'test@kpark.fr';
        
        account.x__c = 0;
        account.y__c = 0;
        account.Localisation__Latitude__s = 0;
        account.Localisation__Longitude__s = 0;
        account.iris__c = defaultSectorisation.iris__c;
        
        System.assertNotEquals(null, account.iris__c);
        
        return account;
    }
    
    private static Chantier__c createChantier(Account proprietaire, Account autreProprietaire, Account locataire, Account autreLocataire, Account occupant, Account autreOccupant) {
        Chantier__c chantier = new Chantier__c();
        
        chantier.name = 'CHA - Test';
        
        chantier.rue__c = '1200 rue félix faure';
        chantier.codePostal__c = '76320';
        chantier.ville__c = 'Saint-Pierre les Elbeuf';
        chantier.pays__c = 'F';
        chantier.anneeConstruction__c = '2000';
        chantier.typeHabitation__c = 'Pavillon';
        chantier.typeResidence__c = 'Principale';
        
        if (proprietaire != null)
            chantier.proprietaire__c = proprietaire.id;
        if (autreProprietaire != null)
            chantier.autreProprietaire__c = autreProprietaire.id;
        if (locataire != null)
            chantier.locataire__c = locataire.id;
        if (autreLocataire != null)
            chantier.autreLocataire__c = autreLocataire.id;
        if (occupant != null)
            chantier.occupant__c = occupant.id;
        if (autreOccupant != null)
            chantier.autreOccupant__c = autreOccupant.id;
        
        chantier.x__c = 0;
        chantier.y__c = 0;
        chantier.Localisation__Latitude__s = 0;
        chantier.Localisation__Longitude__s = 0;
        chantier.iris__c = defaultSectorisation.iris__c;
        
        System.assertNotEquals(null, chantier.iris__c);
        
        return chantier;
    }
    
    private static Opportunity createOpportunity(Account demandeur, Account autreDemandeur, Chantier__c chantier) {
        Opportunity opportunity = new Opportunity();
        
        opportunity.name = 'PRJ - Test';
        opportunity.accountId = demandeur.id;
        if (autreDemandeur != null)
            opportunity.autreCompte__c = autreDemandeur.id;
        opportunity.chantier__c = chantier.id;
        opportunity.type = 'Nouveau';
        opportunity.StageName = 'Analyse';
        opportunity.leadSource = demandeur.accountSource != null ? demandeur.accountSource : ((autreDemandeur != null && autreDemandeur.accountSource != null) ? autreDemandeur.accountSource : 'JPO');
            opportunity.callSource__c = demandeur.accountSource != null ? demandeur.accountCallSource__c : ((autreDemandeur != null && autreDemandeur.accountSource != null) ? autreDemandeur.accountCallSource__c : null);
                opportunity.closeDate = System.today() + 10;
        opportunity.probability = 10;
        
        return opportunity;
    }
    
    //SEO 02/08/2013 Ajout du whoId
    private static Event createEvent(Opportunity opportunity, Account demandeur) {
        Event event = new Event(recordTypeId = rtRDV.id);
        
        event.type = 'R1';
        event.activityDate = System.today();
        event.startDateTime = System.now();
        event.endDateTime = System.now();
        event.whatId = opportunity.id;
        event.whoId = demandeur.personContactId;
        event.couplePresent__c = 'Oui';
        event.decisionnaire__c = True;
        event.statutRDV__c = 'Effectué';
        event.resultatDuRDV__c = 'Devisable';
        
        return event;
    }
    
    private static Quote createQuote(Opportunity opportunity) {
        Quote quote = new Quote(recordTypeId = rtDEVIS.id);
        
        Id pricebookId = [SELECT Id FROM Pricebook2 WHERE Name ='Test' LIMIT 1].Id;
        
        quote.OpportunityId = opportunity.Id;
        quote.Pricebook2Id = pricebookId;
        quote.Name = 'MyQuote';
        quote.compte__c = opportunity.accountId;
        //quote.C2E__c = 'Oui';
        quote.source__c = 'BAL VENDEUR';
        quote.moyenTransmissionClient__c = 'Par email';
        quote.autreCompte__c = opportunity.autreCompte__c;
        quote.modeFinancement__c = 'PAIEMENT COMPTANT';
        quote.Total_TTC_devis__c = 123;
        
        return quote;
    }
    
    private static KContrat__c createKContrat(Account compte, Account autreCompte, Chantier__c chantier, Quote devis) {
        KContrat__c contrat = new KContrat__c();
        
        contrat.compte__c = compte.id;
        contrat.autreCompte__c = autreCompte.id;
        contrat.chantier__c = chantier.id;
        contrat.devis__c = devis.id;
        contrat.montantECS__c = -50;
        contrat.montantHT__c = 5000;
        contrat.montantTTC__c = 7000;
        contrat.dateSignature__c = System.today();
        contrat.numeroContrat__c = 'CNT/0102030405';
        contrat.libelleStatutContrat__c = 'Test';
        
        return contrat;
    }
    
    private static KInstance__c createKInstance(KContrat__c contrat) {
        KInstance__c instance = new KInstance__c();
        
        instance.contrat__c = contrat.id;
        instance.actif__c = False;
        instance.dateEcheance__c = System.today() + 10;
        instance.dateEntree__c = System.today() - 1;
        instance.dateSortie__c = System.today();
        instance.nInstance__c = 'IEC/0102030405/01';
        instance.statut__c = 'Terminé';
        
        return instance;
    }
    
    private static User getUser() {
        UserContext context = UserContext.getContext();
        User user = context.getUser();
        if (StringUtils.isEmpty(user.codeMagasin__c))
            user.codeMagasin__c = 'MAG0000';
        if (StringUtils.isEmpty(user.libelleMagasin__c))
            user.codeMagasin__c = 'Magasin 0000';
        if (StringUtils.isEmpty(user.codeDV__c))
            user.codeMagasin__c = 'DV0000';
        if (StringUtils.isEmpty(user.libelleDV__c))
            user.codeMagasin__c = 'DV 0000';
        if (StringUtils.isEmpty(user.codeDR__c))
            user.codeMagasin__c = 'DV0000';
        if (StringUtils.isEmpty(user.libelleDR__c))
            user.codeMagasin__c = 'DV 0000';
        return user;
    }
}