force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/codePostal__c.field-meta.xml
<CustomField>
    <fullName>codePostal__c</fullName>
    <label>Code postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/complementAdresse__c.field-meta.xml
<CustomField>
    <fullName>complementAdresse__c</fullName>
    <inlineHelpText>Informations affichées comme 2nd ligne sur l’adresse postale.
Résidence, bâtiment, zone, etc.</inlineHelpText>
    <label>Complément d&apos;adresse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/departement__c.field-meta.xml
<CustomField>
    <fullName>departement__c</fullName>
    <label>Département/Région</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/etage__c.field-meta.xml
<CustomField>
    <fullName>etage__c</fullName>
    <label>Etage</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/methodeGeocodage__c.field-meta.xml
<CustomField>
    <fullName>methodeGeocodage__c</fullName>
    <label>Méthode de géocodage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automatique</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>Manuel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/pays__c.field-meta.xml
<CustomField>
    <fullName>pays__c</fullName>
    <label>Pays</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/rue__c.field-meta.xml
<CustomField>
    <fullName>rue__c</fullName>
    <label>Rue</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/ville__c.field-meta.xml
<CustomField>
    <fullName>ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/Collaborator__c/Collaborator__c.object-meta.xml
<CustomObject>
    <description>This object manage internal and external KparK collaborators.
It allow HR Team to manage collaborators  without using salesforce user management. There&apos;s two type of collaborator :
 - Internal collaborator
 - External collaborator
A collaborator is unique.</description>
    <label>Collaborateur</label>
    <nameField>
        <label>Nom complet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collaborateurs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Collaborator__c/fields/addressComplement__c.field-meta.xml
<CustomField>
    <fullName>addressComplement__c</fullName>
    <label>Complément d&apos;adresse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/city__c.field-meta.xml
<CustomField>
    <fullName>city__c</fullName>
    <label>Ville</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <defaultValue>&quot;FRANCE&quot;</defaultValue>
    <label>Pays</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/postalCode__c.field-meta.xml
<CustomField>
    <fullName>postalCode__c</fullName>
    <label>Code postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/state__c.field-meta.xml
<CustomField>
    <fullName>state__c</fullName>
    <label>Département/région</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/street__c.field-meta.xml
<CustomField>
    <fullName>street__c</fullName>
    <label>Rue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityVersion__c/EntityVersion__c.object-meta.xml
<CustomObject>
    <description>Référentiel des version d&apos;entités de KparK (Magasin, dépôt, agence etc...)</description>
    <label>Version d&apos;entité</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions d&apos;entité</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EntityVersion__c/fields/addressSupplement__c.field-meta.xml
<CustomField>
    <fullName>addressSupplement__c</fullName>
    <inlineHelpText>Toute information pertinente pour définir/localiser plus précisément l&apos;adresse de l&apos;entité (ex: ZI, Parc à, etc.)</inlineHelpText>
    <label>Complément d&apos;adresse</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityVersion__c/fields/city__c.field-meta.xml
<CustomField>
    <fullName>city__c</fullName>
    <label>Ville</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityVersion__c/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <defaultValue>&quot;FRANCE&quot;</defaultValue>
    <label>Pays</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityVersion__c/fields/postalCode__c.field-meta.xml
<CustomField>
    <fullName>postalCode__c</fullName>
    <label>Code postal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EntityVersion__c/fields/street__c.field-meta.xml
<CustomField>
    <fullName>street__c</fullName>
    <label>Rue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Liste des départements et régions français</description>
    <label>State</label>
</CustomObject>

force-app/main/default/classes/LWC_DQEFormAddress.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : LWC_DQEFormAddress
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 26/11/2020
//-- Version     : 1.0
//-- * 1.0 - Init
//-- --------------------------------------------------------------------------------- --
public with sharing class LWC_DQEFormAddress {

    /**
    * @description Function to call generic function of DQE
    * @param params Object with parameters information
    * @param service Name of the DQE service
    * @return String Response 
    */
    @AuraEnabled
    public static String executeDQERequest(Map<String, String> params, String service){
        System.debug('### DEBUT LWC_DQEFormAddress.executeDQERequest');
        String result;
        try{
            result = Utils_DQE.executeDQEAddressRequest(service, params);
            System.debug('### FIN LWC_DQEFormAddress.executeDQERequest');
            return result;
        } catch(Exception e) {
            System.debug('ERREUR : ' + e.getMessage() + ' ' + e.getTypeName() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /**
    * @description Function to save the address in the record and call RNVP service of DQE to get IRIS
    * @param objectAPIName API name of the object
    * @param recordId Id of the record
    * @param street New value of the street
    * @param city New value of the city
    * @param state New value of the region
    * @param zip New value of the zip code
    * @param country New value of the country
    * @param longitude New value of the longitude
    * @param latitude New value of the latitude
    * @param complementAddress New value of the complementAddress
    * @param npai New value of the npai
    * @param etage New value of the etage
    */
    @AuraEnabled
    public static void modifyRecordInformation(String objectAPIName, Id recordId, String street, String city, String state,
                                                String zip, String country, Decimal longitude, Decimal latitude, 
                                                String complementAddress, Decimal etage){
        System.debug('### START_LWC_DQEFormAddress.modifyRecordInformation');
        System.debug('## objectAPIName : '+objectAPIName);
        System.debug('## recordId : '+recordId);
        System.debug('## zip : '+zip);
        System.debug('## city : '+city);
        System.debug('## street : '+street);
        System.debug('## longitude : '+longitude);
        System.debug('## latitude : '+latitude);
        System.debug('## complementAddress : '+complementAddress);
        System.debug('## etage : '+etage);
        try {
            if(String.isNotBlank(recordId) && String.isNotBlank(objectAPIName)) {
                Boolean sauvegardeOk;
                Boolean adresseNonRenseignee = (String.isBlank(street) && String.isBlank(city) && String.isBlank(zip));
                Boolean paysFR = ((String.isBlank(country)) || (country.equalsIgnoreCase('FRANCE')) || (country.equalsIgnoreCase('FRA')) || (country.equalsIgnoreCase('FR')) || (country.equalsIgnoreCase('F')));

                // Process for ACCOUNT
                if(objectAPIName == 'Account') {
                    List<Account> accList = [SELECT Id, PersonMailingStreet, BillingStreet, PersonMailingCity, BillingCity, IsPersonAccount,
                                                Localisation__Latitude__s, Localisation__Longitude__s, PersonMailingPostalCode, PersonMailingCountry,
                                                BillingPostalCode, BillingCountry FROM Account WHERE Id = :recordId];
                    if(!accList.isEmpty()) {
                        Account acc = accList[0];

                        if(acc.IsPersonAccount) {
                            acc.PersonMailingStreet = street;
                            acc.PersonMailingCity = city;
                            acc.PersonMailingState = state;
                            acc.PersonMailingPostalCode = zip;
                            acc.PersonMailingCountry = country;
                        } else {
                            acc.BillingStreet = street;
                            acc.BillingCity = city;
                            acc.BillingState = state;
                            acc.BillingPostalCode = zip;
                            acc.BillingCountry = country;
                        }
                        acc.Localisation__Latitude__s = latitude;
                        acc.Localisation__Longitude__s = longitude;
                        acc.complementAdresse__c = complementAddress;
                        acc.etage__c = etage;
                        // DQE geocodage
                        if (adresseNonRenseignee == false & paysFR) {
                            if(PropertiesUtils.getBooleanValue('dqe.geocoder.enabled', false)) {
                                Utils_DQE.GeocodeResultType responseDQE = GeoUtils.geolocationAccountDQE(acc, acc.IsPersonAccount, null);
                                if(responseDQE != null){
                                    sauvegardeOk = true;
                                } else {
                                    sauvegardeOk = false;
                                }
                                acc.methodeGeocodage__c = 'Manuel';
                                if(!sauvegardeOk) {
                                    throw new KubeException(Label.AdresseNonTrouveeGeoloc);
                                } 
                            }
                        }

                        update acc;
                    }			
                }
                // Process for CHANTIER
                if(objectAPIName == 'Chantier__c') {
                    List<Chantier__c> chantierList = [SELECT Id, rue__c, codePostal__c, ville__c, departement__c, complementAdresse__c, 
                                                        Localisation__Latitude__s, Localisation__Longitude__s, pays__c 
                                                        FROM Chantier__c WHERE Id = :recordId];
                    if(!chantierList.isEmpty()) {
                        Chantier__c cha = chantierList[0];
                        cha.rue__c = street;
                        cha.ville__c = city;
                        cha.departement__c = state;
                        cha.codePostal__c = zip;
                        cha.pays__c = country;
                        cha.Localisation__Latitude__s = latitude;
                        cha.Localisation__Longitude__s = longitude;
                        cha.complementAdresse__c = complementAddress;
                        cha.etage__c = etage;
                        // DQE geocodage
                        if (adresseNonRenseignee == false & paysFR) {
                            if(PropertiesUtils.getBooleanValue('dqe.geocoder.enabled', false)) {
                                Utils_DQE.GeocodeResultType responseDQE = GeoUtils.geolocationChantierDQE(cha, null);
                                if(responseDQE != null){
                                    sauvegardeOk = true;
                                } else {
                                    sauvegardeOk = false;
                                }
                                cha.methodeGeocodage__c = 'Manuel';
                                if(!sauvegardeOk) {
                                    throw new KubeException(Label.AdresseNonTrouveeGeoloc);
                                } 
                            }
                        }

                        update cha;
                    }			
                }
                // Process for COLLABORATOR
                if(objectAPIName == 'Collaborator__c') {
                    List<Collaborator__c> collabList = [SELECT Id, street__c, postalCode__c, city__c, state__c, addressComplement__c,
                                                        localisation__Latitude__s, localisation__Longitude__s, country__c 
                                                        FROM Collaborator__c WHERE Id = :recordId];
                    if(!collabList.isEmpty()) {
                        Collaborator__c collab = collabList[0];
                        collab.street__c = street;
                        collab.city__c = city;
                        collab.state__c = state;
                        collab.postalCode__c = zip;
                        collab.country__c = country;
                        collab.addressComplement__c = complementAddress;
                        collab.localisation__Latitude__s = latitude;
                        collab.localisation__Longitude__s = longitude;
                        

                        update collab;
                    }			
                }
                // Process for ENTITY VERSION
                if(objectAPIName == 'EntityVersion__c') {
                    List<EntityVersion__c> entVersList = [SELECT Id, street__c, postalCode__c, city__c, addressSupplement__c,
                                                        geolocalisation__Latitude__s, geolocalisation__Longitude__s, country__c 
                                                        FROM EntityVersion__c WHERE Id = :recordId];
                    if(!entVersList.isEmpty()) {
                        EntityVersion__c entVer = entVersList[0];
                        entVer.street__c = street;
                        entVer.city__c = city;
                        entVer.postalCode__c = zip;
                        entVer.country__c = country;
                        entVer.addressSupplement__c = complementAddress;
                        entVer.geolocalisation__Latitude__s = latitude;
                        entVer.geolocalisation__Longitude__s = longitude;

                        update entVer;
                    }			
                }
            }
        } catch(Exception e) {
            System.debug('ERREUR : ' + e.getMessage() + ' ' + e.getTypeName() + ' ' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }
}