force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/anneeConstruction__c.field-meta.xml
<CustomField>
    <fullName>anneeConstruction__c</fullName>
    <label>Année de construction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NSP</fullName>
            </value>
            <value>
                <fullName>Avant 1940</fullName>
            </value>
            <value>
                <fullName>1950</fullName>
            </value>
            <value>
                <fullName>1960</fullName>
            </value>
            <value>
                <fullName>1970</fullName>
            </value>
            <value>
                <fullName>1980</fullName>
            </value>
            <value>
                <fullName>1990</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>2010+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreLocataire__c.field-meta.xml
<CustomField>
    <fullName>autreLocataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre locataire)</relationshipLabel>
    <relationshipName>autreLocataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreOccupant__c.field-meta.xml
<CustomField>
    <fullName>autreOccupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre occupant)</relationshipLabel>
    <relationshipName>autreOccupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreProprietaire__c.field-meta.xml
<CustomField>
    <fullName>autreProprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre propriétaire)</relationshipLabel>
    <relationshipName>autreProprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/codePostal__c.field-meta.xml
<CustomField>
    <fullName>codePostal__c</fullName>
    <label>Code postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/iris__c.field-meta.xml
<CustomField>
    <fullName>iris__c</fullName>
    <label>Iris</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/locataire__c.field-meta.xml
<CustomField>
    <fullName>locataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du propriétaire</inlineHelpText>
    <label>Locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Locataire)</relationshipLabel>
    <relationshipName>locataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/occupant__c.field-meta.xml
<CustomField>
    <fullName>occupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du locataire</inlineHelpText>
    <label>Occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Occupant)</relationshipLabel>
    <relationshipName>occupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/pays__c.field-meta.xml
<CustomField>
    <fullName>pays__c</fullName>
    <label>Pays</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/proprietaire__c.field-meta.xml
<CustomField>
    <fullName>proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire)</relationshipLabel>
    <relationshipName>proprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/rue__c.field-meta.xml
<CustomField>
    <fullName>rue__c</fullName>
    <label>Rue</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/sectorisation__c.field-meta.xml
<CustomField>
    <fullName>sectorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sectorisation</label>
    <referenceTo>Sectorisation__c</referenceTo>
    <relationshipLabel>Chantiers</relationshipLabel>
    <relationshipName>sectorisationChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/typeHabitation__c.field-meta.xml
<CustomField>
    <fullName>typeHabitation__c</fullName>
    <label>Type d&apos;habitation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pavillon</fullName>
            </value>
            <value>
                <fullName>Appartement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/typeResidence__c.field-meta.xml
<CustomField>
    <fullName>typeResidence__c</fullName>
    <label>Type de résidence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Principale</fullName>
            </value>
            <value>
                <fullName>Secondaire</fullName>
            </value>
            <value>
                <fullName>Locative</fullName>
            </value>
            <value>
                <fullName>Professionnelle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/ville__c.field-meta.xml
<CustomField>
    <fullName>ville__c</fullName>
    <label>Ville</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/x__c.field-meta.xml
<CustomField>
    <fullName>x__c</fullName>
    <label>X</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/y__c.field-meta.xml
<CustomField>
    <fullName>y__c</fullName>
    <label>Y</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/ObjectifsVendeur__c/ObjectifsVendeur__c.object-meta.xml
<CustomObject>
    <description>CRM-540 : Objectifs des vendeurs par semaine</description>
    <label>Objectif vendeur</label>
    <nameField>
        <displayFormat>OV/{YYYY}/{00000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectifs vendeur</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectifsVendeur__c/fields/anneeObjectif__c.field-meta.xml
<CustomField>
    <fullName>anneeObjectif__c</fullName>
    <defaultValue>YEAR(TODAY())</defaultValue>
    <description>CRM-540 : Année sélectionnée par l’utilisateur</description>
    <label>Année des objectifs</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ObjectifsVendeur__c/fields/chiffreAffaireVenduS1__c.field-meta.xml
<CustomField>
    <fullName>chiffreAffaireVenduS1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>CRM-540 : Objectif du chiffre d’affaire vendu pour la semaine 1</description>
    <label>CA (K€) vendu (S1)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ObjectifsVendeur__c/fields/moisObjectif__c.field-meta.xml
<CustomField>
    <fullName>moisObjectif__c</fullName>
    <description>CRM-540 : Mois sélectionné par l’utilisateur</description>
    <label>Mois des objectifs</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Janvier</fullName>
                <default>true</default>
                <label>Janvier</label>
            </value>
            <value>
                <fullName>Février</fullName>
            </value>
            <value>
                <fullName>Mars</fullName>
            </value>
            <value>
                <fullName>Avril</fullName>
            </value>
            <value>
                <fullName>Mai</fullName>
            </value>
            <value>
                <fullName>Juin</fullName>
            </value>
            <value>
                <fullName>Juillet</fullName>
            </value>
            <value>
                <fullName>Août</fullName>
            </value>
            <value>
                <fullName>Septembre</fullName>
            </value>
            <value>
                <fullName>Octobre</fullName>
            </value>
            <value>
                <fullName>Novembre</fullName>
            </value>
            <value>
                <fullName>Décembre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ObjectifsVendeur__c/fields/nbContactsActifsS1__c.field-meta.xml
<CustomField>
    <fullName>nbContactsActifsS1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>CRM-540 : Objectif de comptes actifs pour la semaine 1</description>
    <label>Nombre de contacts actifs (S1)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ObjectifsVendeur__c/fields/nbVentesS1__c.field-meta.xml
<CustomField>
    <fullName>nbVentesS1__c</fullName>
    <defaultValue>0</defaultValue>
    <description>CRM-540 : Objectif de ventes pour la semaine 1</description>
    <label>Nombre de ventes (S1)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ObjectifsVendeur__c/fields/vendeur__c.field-meta.xml
<CustomField>
    <fullName>vendeur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRM-540 : Vendeur pour les objectifs</description>
    <label>Vendeur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ObjectifsVendeur</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/Sectorisation__c.object-meta.xml
<CustomObject>
    <label>Sectorisation</label>
    <nameField>
        <label>Nom de Sectorisation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sectorisation__c/fields/codeMagasin__c.field-meta.xml
<CustomField>
    <fullName>codeMagasin__c</fullName>
    <label>Code magasin</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/codeRegion__c.field-meta.xml
<CustomField>
    <fullName>codeRegion__c</fullName>
    <label>Code région</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/IRIS__c.field-meta.xml
<CustomField>
    <fullName>IRIS__c</fullName>
    <externalId>true</externalId>
    <label>IRIS</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleMagasin__c.field-meta.xml
<CustomField>
    <fullName>libelleMagasin__c</fullName>
    <externalId>true</externalId>
    <label>Magasin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sectorisation__c/fields/libelleRegion__c.field-meta.xml
<CustomField>
    <fullName>libelleRegion__c</fullName>
    <label>Région</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_Ctrl_ObjectifsDashboard.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_Ctrl_ObjectifsDashboard
//-- Modifié par : SOPRA - William DE GAËTANO
//-- Modifié le  : 21/07/2015
//-- Version     : 1.0
//-- * Initialisation
//-- --------------------------------------------------------------------------------- --
@isTest
private class Test_Ctrl_ObjectifsDashboard {	
	private static final RecordType rtRDV    = [SELECT id FROM RecordType WHERE name = 'FRA- Activité commerciale' LIMIT 1];
	private static final RecordType rtDEVIS  = [SELECT id FROM RecordType WHERE name = 'FRA- Devis A configurer' LIMIT 1];

	@testSetup static void setup() {
		TestCommon.createGlobalProperties(true, 17, true, true, true, 30, 10, true);

		// Création Sectorisation
		Sectorisation__c sect = New Sectorisation__c (codeRegion__c='R123',libelleRegion__c='Région 123',
													codeMagasin__c='M123',libelleMagasin__c='Magasin 123');
		insert sect;
	}
	
	@isTest static void test_atteinte_objectifs() {
		// Récupération profil RV
		Profile profilRV = [select id  from profile where Name LIKE '%RV%' limit 1];
		Profile profilVendeur = [select id  from profile where Name LIKE '%Vendeur%' limit 1];

		//creation utilisateur RV
		String testemail = 'puser'+system.now().format('hhmmss')+'@testemail.com';
		User userTestRV = new User(profileId = profilRV.id, username = testemail, email = testemail,
									emailencodingkey = 'ISO-8859-1', localesidkey = 'fr_FR',
									languagelocalekey = 'fr', timezonesidkey = 'Europe/Paris', CodeMagasin__c = 'M123',
									alias='cspu', lastname='lastname',ByPassValidationRule__c = true, ByPassWorkflowRule__c= true, Division= 'VENTE');
		insert userTestRV;

		// Récupération des recordtypes
		RecordType accRecordType = [select id , Name, sobjectType from RecordType where sobjectType = 'Account' and isPersonType = true limit 1];

		System.RunAs(userTestRV) {
			PageReference pageRef = Page.VF_ObjectifsDashboard;

			String month = String.valueOf(Date.today().month());
			String year = String.valueOf(Date.today().year());
			system.debug('month ' + month);
			system.debug('year ' + year);

			// Création d'un compte
			List<Account> acc = new List<Account>{};
			Account a = new Account(Type='Contact',LastName='Dupont', FirstName='Jean',
									RecordTypeId=accRecordType.Id,PersonMailingPostalCode='12345',
									AccountSource = 'BAL VENDEUR', accountCallSource__c = null,
									PersonMailingCity='City123',PersonMailingCountry='Country123');
			acc.add(a);

			Account b = new Account(Type='Contact',LastName='Dupont', FirstName='Jeanne',
									RecordTypeId=accRecordType.Id,PersonMailingPostalCode='12345',
									PersonMailingCity='City123',PersonMailingCountry='Country123',
									AccountSource = 'PORTE A PORTE VENDEUR', accountCallSource__c = 'test',
									optinTelephoneDomicileKparK__c = true, optinTelephoneMobileKparK__c = true);
			acc.add(b);
			insert acc;
			Map<Id, Account> accountMap = new Map<Id, Account>([Select Id, AccountSource, accountCallSource__c, PersonContactId FROM Account WHERE ID IN :acc]);
			Account B2C1 = accountMap.get(a.id);
			Account B2C2 = accountMap.get(b.id);

			// Creation des objectifs
			ObjectifsVendeur__c obj = new ObjectifsVendeur__c(anneeObjectif__c = Integer.valueOf(year), vendeur__c = userTestRV.Id, 
															moisObjectif__c = Constants.MONTHS[Date.today().month()-1],
															nbContactsActifsS1__c = 1,
															nbVentesS1__c = 5, chiffreAffaireVenduS1__c = 30);
			insert obj;

			// Création données
			Chantier__c chantier = createChantier(B2C1, null, null, null, null, null);
			insert chantier;
			chantier = ((List<Chantier__c>) SchemaUtils.executeQuery('Chantier__c', chantier.id))[0];
			Opportunity projet = createOpportunity(B2C1, B2C2, chantier);
			insert projet;

			Event eventR1 = createEvent(projet, B2C1);
			insert eventR1;
			Event eventR2 = createEvent(projet, B2C1);
			eventR2.Type = 'R2';
			insert eventR2;
			Event event1 = createEvent(projet, B2C1);
			event1.Type = 'Prospection physique';
			event1.nbBAL50__c = 2;
			event1.NbTAP51__c = 3;
			insert event1;
			Event event2 = createEvent(projet, B2C1);
			event2.Type = 'Phone';
			event2.NbPhone55__c = 2;
			insert event2;
			Event event3 = createEvent(projet, B2C1);
			event3.Type = 'Stand/Galerie Marchande';
			insert event3;
			Event event4 = createEvent(projet, B2C1);
			event4.Type = 'Foire';
			insert event4;
			Event event5 = createEvent(projet, B2C1);
			event5.Type = 'Stand/Marché';
			insert event5;

			Quote quote = createQuote(projet);
			quote.forcageEtat__c = 'Vendu en attente d\'enregistrement';
			quote.Status = 'Vendu en attente d\'enregistrement';
			quote.Total_TTC_devis__c = 3;
			quote.RemisevendeurglobaleDevise__c = 3;
			quote.dateAcceptationClient__c = Date.today();
            quote.source__c = 'BAL VENDEUR';
			insert quote;

			// TEST
			Test.startTest();
			Test.setCurrentPage(pageRef);
			Ctrl_ObjectifsDashboard ctrl = new Ctrl_ObjectifsDashboard();

			List<SelectOption> semaineOptions = ctrl.getsemaine();
			List<SelectOption> moisOptions = ctrl.mois;
			ctrl.insertUserStats();

			system.debug('ctrl.anneeActuelle ' + ctrl.anneeActuelle);
			system.debug('ctrl.moisActuel ' + ctrl.moisActuel);
			system.debug('ctrl.semaineActuelle ' + ctrl.semaineActuelle);
			String semaine = '1';
			ctrl.codeMagasinActuel='M123';

			List<String> vendeursIdList = new List<String>();
			vendeursIdList.add(userTestRV.Id);
			
			Ctrl_ObjectifsDashboard.getObjectifsMensuel(year, month, vendeursIdList);
			Ctrl_ObjectifsDashboard.getObjectifsVendeursHebdomadaire(year, month, semaine, ctrl.periodId, vendeursIdList);
			Ctrl_ObjectifsDashboard.getObjectifsVendeursMensuel(year, month, ctrl.fiscalSettingsId, vendeursIdList);

			semaine = '4';
			Ctrl_ObjectifsDashboard.getObjectifsMensuel(year, month, vendeursIdList);
			Ctrl_ObjectifsDashboard.getObjectifsVendeursMensuel(year, month, ctrl.fiscalSettingsId, vendeursIdList);
			Ctrl_ObjectifsDashboard.getObjectifsVendeursHebdomadaire(year, month, semaine, ctrl.periodId, vendeursIdList);

			semaine = '5';
			Ctrl_ObjectifsDashboard.getObjectifsVendeursHebdomadaire(year, month, semaine, ctrl.periodId, vendeursIdList);
			Test.stopTest();
		}
	}

	private static Chantier__c createChantier(Account proprietaire, Account autreProprietaire, Account locataire, Account autreLocataire, Account occupant, Account autreOccupant) {
		Chantier__c chantier = new Chantier__c();
		chantier.name = 'CHA - Test';
		chantier.rue__c = '1200 rue félix faure';
		chantier.codePostal__c = '76320';
		chantier.ville__c = 'Saint-Pierre les Elbeuf';
		chantier.pays__c = 'F';
		chantier.anneeConstruction__c = '2000';
		chantier.typeHabitation__c = 'Pavillon';
		chantier.typeResidence__c = 'Principale';
		if (proprietaire != null)
			chantier.proprietaire__c = proprietaire.id;
		if (autreProprietaire != null)
			chantier.autreProprietaire__c = autreProprietaire.id;
		if (locataire != null)
			chantier.locataire__c = locataire.id;
		if (autreLocataire != null)
			chantier.autreLocataire__c = autreLocataire.id;
		if (occupant != null)
			chantier.occupant__c = occupant.id;
		if (autreOccupant != null)
			chantier.autreOccupant__c = autreOccupant.id;
		chantier.x__c = 0;
		chantier.y__c = 0;
		chantier.Localisation__Latitude__s = 0;
		chantier.Localisation__Longitude__s = 0;
		chantier.iris__c = 'test';
		return chantier;
	}

	private static Opportunity createOpportunity(Account demandeur, Account autreDemandeur, Chantier__c chantier) {
		Opportunity opportunity = new Opportunity();
		opportunity.name = 'PRJ - Test';
		opportunity.accountId = demandeur.id;
		if (autreDemandeur != null)
			opportunity.autreCompte__c = autreDemandeur.id;
		opportunity.chantier__c = chantier.id;
		opportunity.type = 'Nouveau';
		opportunity.StageName = 'Analyse';
		opportunity.leadSource = demandeur.accountSource != null ? demandeur.accountSource : ((autreDemandeur != null && autreDemandeur.accountSource != null) ? autreDemandeur.accountSource : 'JPO');
		opportunity.callSource__c = demandeur.accountSource != null ? demandeur.accountCallSource__c : ((autreDemandeur != null && autreDemandeur.accountSource != null) ? autreDemandeur.accountCallSource__c : null);
		opportunity.closeDate = System.today() + 10;
		opportunity.probability = 10;
		return opportunity;
	}

	private static Event createEvent(Opportunity opportunity, Account demandeur) {
		Event event = new Event(recordTypeId = rtRDV.id);
		event.type = 'R1';
		event.activityDate = System.today();
		event.startDateTime = System.now();
		event.endDateTime = System.now();
		event.whatId = opportunity.id;
		event.whoId = demandeur.personContactId;
		event.couplePresent__c = 'Oui';
		event.decisionnaire__c = true;
		event.statutRDV__c = 'Effectué';
		event.resultatDuRDV__c = 'Devisable';
		return event;
	}

	private static Quote createQuote(Opportunity opportunity) {
		Quote quote = new Quote(recordTypeId = rtDEVIS.id);

		Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book', Description = 'Price Book Products', IsActive = true);
		insert pb;

		//Id pricebookId = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1].Id;

		quote.OpportunityId = opportunity.Id;
		quote.Pricebook2Id = pb.Id;
		quote.Name = 'MyQuote';
		quote.compte__c = opportunity.accountId;
		quote.C2E__c = 'Oui';
		quote.moyenTransmissionClient__c = 'Par email';
		quote.autreCompte__c = opportunity.autreCompte__c;
		quote.modeFinancement__c = 'PAIEMENT COMPTANT';

		return quote;
	}
}