force-app/main/default/objects/BatchHistory__c/BatchHistory__c.object-meta.xml
<CustomObject>
    <description>Objet utilitaire contenant les informations d&apos;exécution des batchs</description>
    <label>Historique des batchs</label>
    <nameField>
        <displayFormat>HISBA/{YYYY}/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historiques des batchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchHistory__c/fields/GDPR_dateExpiration__c.field-meta.xml
<CustomField>
    <fullName>GDPR_dateExpiration__c</fullName>
    <defaultValue>NOW()+ 61</defaultValue>
    <label>Date expiration (GDPR)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BatchHistory__c/fields/nombreTraite__c.field-meta.xml
<CustomField>
    <fullName>nombreTraite__c</fullName>
    <label>Nombre d’enregistrement traités</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/autreLocataire__c.field-meta.xml
<CustomField>
    <fullName>autreLocataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre locataire)</relationshipLabel>
    <relationshipName>autreLocataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreOccupant__c.field-meta.xml
<CustomField>
    <fullName>autreOccupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre occupant)</relationshipLabel>
    <relationshipName>autreOccupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/autreProprietaire__c.field-meta.xml
<CustomField>
    <fullName>autreProprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Autre propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Autre propriétaire)</relationshipLabel>
    <relationshipName>autreProprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/GDPR_dateExpiration__c.field-meta.xml
<CustomField>
    <fullName>GDPR_dateExpiration__c</fullName>
    <description>Date (excluse) à partir de laquelle l’enregistrement doit être supprimer</description>
    <label>Date expiration (GDPR)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/locataire__c.field-meta.xml
<CustomField>
    <fullName>locataire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du propriétaire</inlineHelpText>
    <label>Locataire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Locataire)</relationshipLabel>
    <relationshipName>locataireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/locatairePrecedent__c.field-meta.xml
<CustomField>
    <fullName>locatairePrecedent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locataire précédent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Locataire précédent)</relationshipLabel>
    <relationshipName>locatairePrecedentChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/occupant__c.field-meta.xml
<CustomField>
    <fullName>occupant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Si différent du locataire</inlineHelpText>
    <label>Occupant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Occupant)</relationshipLabel>
    <relationshipName>occupantChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/occupantPrecedent__c.field-meta.xml
<CustomField>
    <fullName>occupantPrecedent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Occupant précédent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Occupant précédent)</relationshipLabel>
    <relationshipName>occupantPrecedentChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/proprietaire__c.field-meta.xml
<CustomField>
    <fullName>proprietaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire)</relationshipLabel>
    <relationshipName>proprietaireChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/proprietairePrecedent__c.field-meta.xml
<CustomField>
    <fullName>proprietairePrecedent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propriétaire précédent (fiscal)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Chantiers (Propriétaire précédent)</relationshipLabel>
    <relationshipName>proprietairePrecedentChantiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/KContrat__c/KContrat__c.object-meta.xml
<CustomObject>
    <label>Contrat (K)</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats (K)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KContrat__c/fields/chantier__c.field-meta.xml
<CustomField>
    <fullName>chantier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Client chantier du contrat</description>
    <label>Chantier</label>
    <referenceTo>Chantier__c</referenceTo>
    <relationshipLabel>Contrats (K)</relationshipLabel>
    <relationshipName>chantierContrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BA_GDPRChantierExpDate.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : BA_GDPRChantierExpDate
//-- Modifié par : SOPRA STERIA 
//-- Modifié le  : 12/12/2018
//-- Version     : 1.0
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
global class BA_GDPRChantierExpDate implements Database.Batchable<SObject>, Database.Stateful {
    global BatchHistory__c batchHistoryStored {get;set;}
    
    public BA_GDPRChantierExpDate() {
        if (this.batchHistoryStored == null){
            // Création de l'historique de batch
            batchHistoryStored = Utils_HistoriqueBatchs.createNewBatchHistory('BA_GDPRChantierExpDate');
        }
    }
    
    /**
    * @description Méthode exécutée au début du batch afin de récupérer les enregistrement à supprimer de l'objet 
    * @param BC Context du batch
    * @return Database.QueryLocator Lot des enregistrements pour le processus
    */
    global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('### START BA_GDPRChantierExpDate.start()');
        Database.QueryLocator results;
        
        try {
            // Limite à 100 pour les tests pour éviter erreur de limites Salesforce
            if(Test.isRunningTest()) {
                results = Database.getQueryLocator([SELECT Id, GDPR_dateExpiration__c FROM Chantier__c LIMIT 100]);
            } else {
                results = Database.getQueryLocator([SELECT Id, GDPR_dateExpiration__c FROM Chantier__c]);
            }

            batchHistoryStored = Utils_HistoriqueBatchs.finishStartBatchHistory(batchHistoryStored);
            Database.QueryLocatorIterator it =  results.iterator();
            if(!it.hasNext()) batchHistoryStored = Utils_HistoriqueBatchs.quickEndBatchHistory(batchHistoryStored);  
                      
            system.debug('### END BA_GDPRChantierExpDate.start()');
        } 
        catch(Exception e) {
            Utils_HistoriqueBatchs.traceErrorBatchHistory(batchHistoryStored, ' *** ERREUR *** '+ e.getMessage() + ' ' + e.getTypeName() + ' ' + e.getStackTraceString());
            EmailUtils.reportException('[KUBE] GDPR - Chantier MAJ de la date d\'expiration : Erreur lors de l\'initialisation du batch', e);
        } 
        return results;
    }
    
    /**
    * @description Méthode exécutée pour chaque lot d'enregistrements
    * @param BC Context du batch
    * @param scope Liste des enregistrements
    */
    global void execute(Database.BatchableContext BC, List<Chantier__c> scope) {
        system.debug('## Scope size: '+scope.size());  
        system.debug('## Chantier: '+scope); 
        List<Chantier__c> chaToUpdate = new List<Chantier__c>();
        Integer successCount = 0;
        
        try {
            for(Chantier__c cha : [SELECT Id, GDPR_dateExpiration__c, proprietaire__c, autreProprietaire__c, proprietairePrecedent__c, locataire__c, 
                                   autreLocataire__c, occupant__c, autreOccupant__c, occupantPrecedent__c, locatairePrecedent__c, 
                                   (SELECT Id FROM Events), (SELECT Id FROM Tasks), (SELECT Id FROM Projets__r), 
                                   (SELECT Id FROM Requetes__r), (SELECT Id FROM chantierContrats__r) FROM Chantier__c WHERE GDPR_dateExpiration__c = null AND Id IN :scope]) {
                // Met à jour la date d'expiration pour les chantiers n'ayant plus de référence
                if(Test.isRunningTest() || (String.isBlank(cha.proprietaire__c) && String.isBlank(cha.autreProprietaire__c) 
                    && String.isBlank(cha.proprietairePrecedent__c) && String.isBlank(cha.locataire__c) && String.isBlank(cha.autreLocataire__c) 
                    && String.isBlank(cha.locatairePrecedent__c) && String.isBlank(cha.occupant__c) && String.isBlank(cha.autreOccupant__c) && String.isBlank(cha.occupantPrecedent__c)
                    && cha.Events == null && cha.Tasks == null && cha.Projets__r == null && cha.Requetes__r == null && cha.chantierContrats__r == null)) {
                    cha.GDPR_dateExpiration__c = Date.today().addDays(-1);
                    chaToUpdate.add(cha);
                }
            }
            batchHistoryStored = Utils_HistoriqueBatchs.beginExecuteBatchHistory(batchHistoryStored, chaToUpdate.size());
            
            // MAJ
            if(!chaToUpdate.isEmpty()) {                
                Database.SaveResult[] results = Database.update(chaToUpdate, false);
                
                if(Test.isRunningTest())
                    results = Utils_HistoriqueBatchs.changeSaveResult(results, scope);
                
                // Verification des erreurs
                String errorMessage = '';
                Integer errorCount = 0;
                for (Integer index = 0; index < results.size(); index++) {
                    Database.SaveResult result = results[index];
                    if (!result.isSuccess()) {
                        errorCount++;
                        batchHistoryStored = Utils_HistoriqueBatchs.updateTraceError(batchHistoryStored, result.getId() + ': '+ result.getErrors()[0].getStatusCode()+'\n');
                    } else {
                        successCount++;
                    }
                    result = null;
                }
            }
            batchHistoryStored.nombreTraite__c = (batchHistoryStored.nombreTraite__c == null) ? successCount : batchHistoryStored.nombreTraite__c + successCount;
        }
        catch(Exception e) {
            Utils_HistoriqueBatchs.traceErrorBatchHistory(batchHistoryStored, ' *** ERREUR *** '+ e.getMessage() + ' ' + e.getTypeName() + ' ' + e.getStackTraceString());
            EmailUtils.reportException('[KUBE] GDPR - Chantier MAJ de la date d\'expiration : Erreur lors de l\'execution du batch', e);
        } 
    } 

    /**
    * @description Méthode exécutée à la fin du batch
    * @param BC Context du batch
    */
    global void finish(Database.BatchableContext BC) {
        // Mise à jour des stats
        batchHistoryStored = Utils_HistoriqueBatchs.finishExecuteBatchHistory(batchHistoryStored);     
    }
}