force-app/main/default/objects/Collaborator__c/Collaborator__c.object-meta.xml
<CustomObject>
    <description>This object manage internal and external KparK collaborators.
It allow HR Team to manage collaborators  without using salesforce user management. There&apos;s two type of collaborator :
 - Internal collaborator
 - External collaborator
A collaborator is unique.</description>
    <label>Collaborateur</label>
    <nameField>
        <label>Nom complet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collaborateurs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Collaborator__c/fields/assignedTo__c.field-meta.xml
<CustomField>
    <fullName>assignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Site physique d&apos;affectation contractuelle du collaborateur (ex: un DO sera employé par une DO mais affecté contractuellement à un dépôt ou un magasin)</inlineHelpText>
    <label>Affecté à</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collaborateurs (Affecté à)</relationshipLabel>
    <relationshipName>collaboratorAssignedTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/employedBy__c.field-meta.xml
<CustomField>
    <fullName>employedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Entité hiérarchique d&apos;affectation du collaborateur (ex: un DO sera employé par une DO mais affecté contractuellement à un dépôt ou un magasin)</inlineHelpText>
    <label>Employé par</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collaborateurs (Employé par)</relationshipLabel>
    <relationshipName>collaboratorEmployedBy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/job__c.field-meta.xml
<CustomField>
    <fullName>job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Métier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Job</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Collaborateurs</relationshipLabel>
    <relationshipName>collaboratorJob</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CollaboratorContract__c/CollaboratorContract__c.object-meta.xml
<CustomObject>
    <description>Objet permettant de définir un ou plusieurs contrat pour un collaborateur de K par K</description>
    <label>Contrat collaborateur</label>
    <nameField>
        <displayFormat>JOB/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats collaborateurs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaboratorContract__c/fields/assignedTo__c.field-meta.xml
<CustomField>
    <fullName>assignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Site physique d&apos;affectation contractuelle du collaborateur (ex: un DO sera employé par une DO mais affecté contractuellement à un dépôt ou un magasin)</inlineHelpText>
    <label>Affecté à</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats collaborateurs (Affecté à)</relationshipLabel>
    <relationshipName>assignedTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaboratorContract__c/fields/collaborator__c.field-meta.xml
<CustomField>
    <fullName>collaborator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Collaborateur</label>
    <referenceTo>Collaborator__c</referenceTo>
    <relationshipLabel>Contrats collaborateurs</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaboratorContract__c/fields/employedBy__c.field-meta.xml
<CustomField>
    <fullName>employedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Entité hiérarchique d&apos;affectation du collaborateur (ex: un DO sera employé par une DO mais affecté contractuellement à un dépôt ou un magasin)</inlineHelpText>
    <label>Employé par</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats collaborateurs (Employé par)</relationshipLabel>
    <relationshipName>employedBy</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaboratorContract__c/fields/job__c.field-meta.xml
<CustomField>
    <fullName>job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Métier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Job</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Contrats collaborateurs</relationshipLabel>
    <relationshipName>CollaboratorContracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaboratorContract__c/fields/signatureDate__c.field-meta.xml
<CustomField>
    <fullName>signatureDate__c</fullName>
    <label>Date de signature</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CollaboratorContract__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CollaboratorContract__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>Type de contrat</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CDI</fullName>
            </value>
            <value>
                <fullName>CDD</fullName>
            </value>
            <value>
                <fullName>CTT</fullName>
            </value>
            <value>
                <fullName>CUI</fullName>
            </value>
            <value>
                <fullName>CAE</fullName>
            </value>
            <value>
                <fullName>CIE</fullName>
            </value>
            <value>
                <fullName>Contrat d&apos;apprentissage</fullName>
            </value>
            <value>
                <fullName>Contrat de professionnalisation</fullName>
            </value>
            <value>
                <fullName>Contrat de prestation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referencial__c/Referencial__c.object-meta.xml
<CustomObject>
    <description>Objet contenant le référentiel de KparK (Documents, MF, CGV, autre etc...)</description>
    <label>Référentiel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencial__c/fields/jobHierarchy__c.field-meta.xml
<CustomField>
    <fullName>jobHierarchy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiérarchie métier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>JobHierarchy</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Métiers</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/KparKReference__c.field-meta.xml
<CustomField>
    <fullName>KparKReference__c</fullName>
    <description>Référence interne unique à K par K</description>
    <externalId>true</externalId>
    <label>Référence</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/parent__c.field-meta.xml
<CustomField>
    <fullName>parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>Referencial__c.RecordTypeId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Référentiels enfants</relationshipLabel>
    <relationshipName>childReferencials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date de début de validité</description>
    <label>Début de validité</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_Schedule_CollaboratorCalcManager.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_Schedule_CollaboratorCalcManager 
//-- Modifie par : SOPRA STERIA
//-- Modifié le  : 30/12/2020
//-- Version     : 1.0
//-- * 1.0 : Initialisation
//-- --------------------------------------------------------------------------------- --
@isTest
private class Test_Schedule_CollaboratorCalcManager {
    private static final Id accPersoRT = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PERSO_RT);
    private static final Id refEntityRT = DAL.getRecordTypeIdByDevName('Referencial__c',Constants.REFERENCIAL_ENTITY_RT);      
    private static final Id REF_JOB_RTID = DAL.getRecordTypeIdByDevName('Referencial__c',Constants.REFERENCIAL_JOB_RT);  
    private static final Id REF_JOBHIERARCHY_RTID = DAL.getRecordTypeIdByDevName('Referencial__c',Constants.REFERENCIAL_JOBHIERARCHY_RT);     
    
    @testSetup 
    static void setup() {        
        // Création entites
        Referencial__c refMag = Utils_Test.createReferencial('Magasin', 'MAG', Date.today(), null, refEntityRT, true, true, true, true, true);
        Account entiteParent = Utils_Test.createEntity('MAGASIN', 'MAG001TEST', Date.today(), '0123456789', refMag.Id, true);
        Account entite = Utils_Test.createEntity('MAGASIN2', 'MAG002TEST', Date.today(), '0123456789', refMag.Id, false);
        entite.ParentId = entiteParent.Id;
        insert entite;  

        // Hierarchie métiers
        Referencial__c supJobHRESP = Utils_Test.createReferencial('Resp', 'HJOB-RESP', Date.today().addMonths(-12), null, REF_JOBHIERARCHY_RTID, false, false, false, false, true);
        Referencial__c supJobHVRP = Utils_Test.createReferencial('VRP', 'HJOB-VRP', Date.today().addMonths(-12), null, REF_JOBHIERARCHY_RTID, false, false, false, false, false);
        supJobHVRP.parent__c = supJobHRESP.Id;
        insert supJobHVRP;
        // Métier
        Referencial__c rvJob = Utils_Test.createReferencial('RV', 'RV', Date.today().addMonths(-12), null, REF_JOB_RTID, false, false, false, false, false);
        rvJob.jobHierarchy__c = supJobHRESP.Id;
        insert rvJob;
        Referencial__c vdJob = Utils_Test.createReferencial('Vendeur', 'Vendeur', Date.today().addMonths(-12), null, REF_JOB_RTID, false, false, false, false, false);
        vdJob.jobHierarchy__c = supJobHVRP.Id;
        insert vdJob;
    }
    
    @isTest
    private static void testBatch() {
        Account ent = [SELECT Id FROM Account WHERE KparKReference__c = 'MAG001TEST' LIMIT 1];
        Referencial__c jobVD = [SELECT Id FROM Referencial__c WHERE KparKReference__c = 'Vendeur' LIMIT 1];
        Referencial__c jobRV = [SELECT Id FROM Referencial__c WHERE KparKReference__c = 'RV' LIMIT 1];

        // Création collaborateurs
        Collaborator__c vd = Utils_Test.createCollaborator(null, 'TEST', 'VENDEUR', 'VENDEUR_MAG001TEST', false);
        Collaborator__c rv = Utils_Test.createCollaborator(null, 'TEST', 'RV', 'RV_MAG001TEST', false);

        Test.startTest();
        
        // Créations contrats
        CollaboratorContract__c contractVD = new CollaboratorContract__c(signatureDate__c = Date.today(),
                startDate__c = Date.today(), collaborator__c = vd.Id, assignedTo__c = ent.Id,
                employedBy__c = ent.Id, type__c = Constants.COLLABORATOR_TYPE_CDI, job__c = jobVD.Id);
        insert contractVD;
        CollaboratorContract__c contractRV = new CollaboratorContract__c(signatureDate__c = Date.today(),
                startDate__c = Date.today(), collaborator__c = rv.Id, assignedTo__c = ent.Id,
                employedBy__c = ent.Id, type__c = Constants.COLLABORATOR_TYPE_CDI, job__c = jobRV.Id);
        insert contractRV;

        // Exécution du Batch 
        BA_CollaboratorCalculateManager ba = new BA_CollaboratorCalculateManager();
        Database.executebatch(ba);

        Test.stopTest();
    }
    
    @isTest
    private static void testSchedule() {
        Account ent = [SELECT Id FROM Account WHERE KparKReference__c = 'MAG001TEST' LIMIT 1];
        Account ent2 = [SELECT Id FROM Account WHERE KparKReference__c = 'MAG002TEST' LIMIT 1];
        Referencial__c jobVD = [SELECT Id FROM Referencial__c WHERE KparKReference__c = 'Vendeur' LIMIT 1];
        Referencial__c jobRV = [SELECT Id FROM Referencial__c WHERE KparKReference__c = 'RV' LIMIT 1];

        // Création collaborateurs
        Collaborator__c vd = Utils_Test.createCollaborator(null, 'TEST', 'VENDEUR', 'VENDEUR_MAG001TEST', false);
        Collaborator__c rv = Utils_Test.createCollaborator(null, 'TEST', 'RV', 'RV_MAG002TEST', false);

        Test.startTest();

        // Créations contrats
        CollaboratorContract__c contractVD = new CollaboratorContract__c(signatureDate__c = Date.today(),
                startDate__c = Date.today(), collaborator__c = vd.Id, assignedTo__c = ent2.Id,
                employedBy__c = ent2.Id, type__c = Constants.COLLABORATOR_TYPE_CDI, job__c = jobVD.Id);
        insert contractVD;
        CollaboratorContract__c contractRV = new CollaboratorContract__c(signatureDate__c = Date.today(),
                startDate__c = Date.today(), collaborator__c = rv.Id, assignedTo__c = ent.Id,
                employedBy__c = ent.Id, type__c = Constants.COLLABORATOR_TYPE_CDI, job__c = jobRV.Id);
        insert contractRV;

        String jobId = System.schedule('Schedule_CollaboratorCalculateManager', '0 0 * * * ?', new Schedule_CollaboratorCalculateManager() );
        Schedule_CollaboratorCalculateManager schedule = new Schedule_CollaboratorCalculateManager();
        schedule.execute(null);

        Test.stopTest();
    }
}