force-app/main/default/objects/Collaborator__c/Collaborator__c.object-meta.xml
<CustomObject>
    <description>This object manage internal and external KparK collaborators.
It allow HR Team to manage collaborators  without using salesforce user management. There&apos;s two type of collaborator :
 - Internal collaborator
 - External collaborator
A collaborator is unique.</description>
    <label>Collaborateur</label>
    <nameField>
        <label>Nom complet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collaborateurs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Collaborator__c/fields/city__c.field-meta.xml
<CustomField>
    <fullName>city__c</fullName>
    <label>Ville</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/country__c.field-meta.xml
<CustomField>
    <fullName>country__c</fullName>
    <defaultValue>&quot;FRANCE&quot;</defaultValue>
    <label>Pays</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/employedBy__c.field-meta.xml
<CustomField>
    <fullName>employedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Entité hiérarchique d&apos;affectation du collaborateur (ex: un DO sera employé par une DO mais affecté contractuellement à un dépôt ou un magasin)</inlineHelpText>
    <label>Employé par</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collaborateurs (Employé par)</relationshipLabel>
    <relationshipName>collaboratorEmployedBy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/job__c.field-meta.xml
<CustomField>
    <fullName>job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Métier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Job</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Collaborateurs</relationshipLabel>
    <relationshipName>collaboratorJob</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/manager__c.field-meta.xml
<CustomField>
    <fullName>manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable</label>
    <referenceTo>Collaborator__c</referenceTo>
    <relationshipLabel>Collaborateurs</relationshipLabel>
    <relationshipName>collaborators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/postalCode__c.field-meta.xml
<CustomField>
    <fullName>postalCode__c</fullName>
    <label>Code postal</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/street__c.field-meta.xml
<CustomField>
    <fullName>street__c</fullName>
    <label>Rue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TR020_Collaborator.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR020_Collaborator 
//-- Modifié par : SOPRA STERIA 
//-- Modifié le  : 18/12/2020
//-- Version     : 1.0
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
public without sharing class TR020_Collaborator {

    /**
    * @description Méthode exécutant les différentes méthode de MAJ pour les collaborateurs
    * @param userContext Objet contexte de l'utilisateur courant
    */
    public static void applyUpdateRules(UserContext userContext) {
        if (!Trigger.isExecuting) {
            return;
        }

        applyDataUpdateRules(userContext);
        applyAsyncUpdateRules(userContext);
    }

    /**
    * @description Méthode exécutant les différentes méthode de MAJ pour les collaborateurs
    * @param userContext Objet contexte de l'utilisateur courant
    */
   private static void applyDataUpdateRules(UserContext userContext) {
        // Initialisation des données intermédiaires 
        Map<Id, Collaborator__c>  oldCollaborators = (Map<Id, Collaborator__c>)Trigger.oldMap;
        List<Collaborator__c> calManagerCollaborator = new List<Collaborator__c>();

        for (Collaborator__c newCollaborator : (List<Collaborator__c>)Trigger.new) {
            if (!AlreadyUsed.isUsed('TR020_Collaborator.applyUpdateRules', newCollaborator.id)) {
                Collaborator__c oldCollaborator = oldCollaborators == null ? null : oldCollaborators.get(newCollaborator.id);

                /* Manager */
                if (Trigger.isBefore && String.isNotBlank(newCollaborator.employedBy__c) && String.isNotBlank(newCollaborator.job__c)
                    && (Trigger.isInsert || (Trigger.isUpdate && (newCollaborator.employedBy__c != oldCollaborator.employedBy__c || newCollaborator.job__c != oldCollaborator.job__c || ( newCollaborator.manager__c != oldCollaborator.manager__c && String.isNotBlank(oldCollaborator.manager__c) )
                            || ( newCollaborator.stageName__c != oldCollaborator.stageName__c && (newCollaborator.stageName__c == 'Provisionné' || newCollaborator.stageName__c == 'En cours') ) )
                            )
                        )
                    ) 
                {
                    calManagerCollaborator.add(newCollaborator);
                }
            }
        }

        // Calcul des managers
        if (!calManagerCollaborator.isEmpty()) {
            Map<String, Collaborator__c> managerMap = Utils_Collaborator.getManager(calManagerCollaborator, Date.today());
            if(managerMap != null) {
                for(Collaborator__c collab : calManagerCollaborator) {
                    collab.manager__c = (managerMap.get(collab.Id) != null) ? managerMap.get(collab.Id).Id : null;
                }
            }
        }
    }

    /**
    * @description Méthode exécutant les différentes méthode de MAJ asynchrone pour les collaborateurs
    * @param userContext Objet contexte de l'utilisateur courant
    */
    private static void applyAsyncUpdateRules(UserContext userContext) {
        if (!Trigger.isExecuting) {
            return;
        }

        // A - Initialisation des données intermédiaires 
        List<Collaborator__c> newCollaborators = (List<Collaborator__c>)Trigger.new;
        Map<Id, Collaborator__c>  oldCollaborators = (Map<Id, Collaborator__c>)Trigger.oldMap;
        Boolean geoEnabled = PropertiesUtils.getBooleanValue('dqe.geocoder.enabled', false);
        List<Collaborator__c> geoCollaborator = new List<Collaborator__c>();

        if (Test.isRunningTest() || geoEnabled) {
            for (Collaborator__c newCollaborator : newCollaborators) {
                if (!AlreadyUsed.isUsed('TR020_Collaborator.applyAsyncUpdateRules', newCollaborator.id)) {
                    Collaborator__c oldCollaborator = oldCollaborators == null ? null : oldCollaborators.get(newCollaborator.id); 

                    // Géocodage
                    Boolean adresseModifiee = Trigger.isInsert ? true : (newCollaborator.street__c != oldCollaborator.street__c || newCollaborator.postalCode__c != oldCollaborator.postalCode__c 
                                                                        || newCollaborator.city__c != oldCollaborator.city__c || newCollaborator.country__c != oldCollaborator.country__c
                                                                        || newCollaborator.localisation__Latitude__s == null || newCollaborator.localisation__Longitude__s == null);

                    if (adresseModifiee && Trigger.isAfter) {
                        geoCollaborator.add(newCollaborator);
                    }
                }
            }
        }

        // B - Application des règles de mise à jour asynchrone 
        if (geoEnabled && !geoCollaborator.isEmpty()) {
            GeoUtils.updateCollaborators(geoCollaborator);
        }
    }
}