force-app/main/default/objects/Collaborator__c/Collaborator__c.object-meta.xml
<CustomObject>
    <description>This object manage internal and external KparK collaborators.
It allow HR Team to manage collaborators  without using salesforce user management. There&apos;s two type of collaborator :
 - Internal collaborator
 - External collaborator
A collaborator is unique.</description>
    <label>Collaborateur</label>
    <nameField>
        <label>Nom complet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collaborateurs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Collaborator__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/user__c.field-meta.xml
<CustomField>
    <fullName>user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utilisateur associé</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Collaborateurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KMDC__c/KMDC__c.object-meta.xml
<CustomObject>
    <description>Objet utilisé pour les tableaux Einstein</description>
    <label>KMDC</label>
    <nameField>
        <label>Nom de KMDC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KMDC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KMDC__c/fields/dateStats__c.field-meta.xml
<CustomField>
    <fullName>dateStats__c</fullName>
    <label>Date stats</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KMDC__c/fields/montantHT__c.field-meta.xml
<CustomField>
    <fullName>montantHT__c</fullName>
    <label>Montant (HT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/KMDC__c/fields/SGID__c.field-meta.xml
<CustomField>
    <fullName>SGID__c</fullName>
    <externalId>true</externalId>
    <label>Vendeur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NRV10Calendar__c/NRV10Calendar__c.object-meta.xml
<CustomObject>
    <label>Calendrier de rémunération</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendriers de rémunération</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NRV10Calendar__c/fields/commDate__c.field-meta.xml
<CustomField>
    <fullName>commDate__c</fullName>
    <description>Date de déclenchement du cliché. Utilisé par la tâche programmée pour passer les commissions en cliché et aboutir à leur versement.</description>
    <label>Date de commissionnement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/NRV10Commission__c.object-meta.xml
<CustomObject>
    <description>Stocke tous les enregistrements des différentes commissions calculées par lignes de produit CPQ et avenants.
4 types de commissions possibles :
 - Commissions par vendeur calculées sur la base des produits des devis CPQ et avenants; et stockées par lignes produit
 - Commissions d&apos;équipes calculées sur la base des commissions vendeurs, en fonction des responsables d&apos;équipes (RV, RVJ, Remplaçants)
 - Commissions bonus calculées sur la base des performances des vendeurs
 - Commissions report calculées sur la base des régularisations des commissions</description>
    <label>Commission</label>
    <nameField>
        <displayFormat>COMM/{YYYY}/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NRV10Commission__c/fields/calculationDate__c.field-meta.xml
<CustomField>
    <fullName>calculationDate__c</fullName>
    <label>Date de calcul</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/comType__c.field-meta.xml
<CustomField>
    <fullName>comType__c</fullName>
    <label>Type de commission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vendeur</fullName>
            </value>
            <value>
                <fullName>Equipe</fullName>
            </value>
            <value>
                <fullName>Bonus</fullName>
            </value>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Malus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/discountCoefficient__c.field-meta.xml
<CustomField>
    <fullName>discountCoefficient__c</fullName>
    <label>Coefficient de décote</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/ecPercent__c.field-meta.xml
<CustomField>
    <fullName>ecPercent__c</fullName>
    <label>[#] Écart cotation (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/instantDate__c.field-meta.xml
<CustomField>
    <fullName>instantDate__c</fullName>
    <label>Date du cliché</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/orderProduct__c.field-meta.xml
<CustomField>
    <fullName>orderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne de commande</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/productRate__c.field-meta.xml
<CustomField>
    <fullName>productRate__c</fullName>
    <label>Taux de produit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/remuneration__c.field-meta.xml
<CustomField>
    <fullName>remuneration__c</fullName>
    <label>Rémunération (€)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/salesRem__c.field-meta.xml
<CustomField>
    <fullName>salesRem__c</fullName>
    <label>Commission vendeur</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prévisionnelle</fullName>
                <default>true</default>
                <label>Prévisionnelle</label>
            </value>
            <value>
                <fullName>Non commissionnable</fullName>
            </value>
            <value>
                <fullName>Commissionnable</fullName>
            </value>
            <value>
                <fullName>Décommissionnable</fullName>
            </value>
            <value>
                <fullName>Commissionnée</fullName>
            </value>
            <value>
                <fullName>Régularisable</fullName>
            </value>
            <value>
                <fullName>Régularisée</fullName>
            </value>
            <value>
                <fullName>Annulée</fullName>
            </value>
            <value>
                <fullName>Décommissionnée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/teamRate__c.field-meta.xml
<CustomField>
    <fullName>teamRate__c</fullName>
    <label>Taux d&apos;équipe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/totalAmountTTC__c.field-meta.xml
<CustomField>
    <fullName>totalAmountTTC__c</fullName>
    <label>Montant total TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/turnoverLevel__c.field-meta.xml
<CustomField>
    <fullName>turnoverLevel__c</fullName>
    <label>Palier CA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/user__c.field-meta.xml
<CustomField>
    <fullName>user__c</fullName>
    <label>Vendeur</label>
    <referenceTo>Collaborator__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NRV10GridRevision__c/NRV10GridRevision__c.object-meta.xml
<CustomObject>
    <label>Révision de grille</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Révisions de grilles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NRV10GridRevision__c/fields/bonusGridRevision__c.field-meta.xml
<CustomField>
    <fullName>bonusGridRevision__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Révision du bonus de vente</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La révision sélectionnée n&apos;est pas de type Bonus</errorMessage>
        <filterItems>
            <field>NRV10GridRevision__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>bonus</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NRV10GridRevision__c</referenceTo>
    <relationshipLabel>Révision de grille (Contrat de travail)</relationshipLabel>
    <relationshipName>Revision_de_grille_bonus</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NRV10GridRevision__c/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <description>Date de fin d&apos;application de la révision de grille</description>
    <label>Date de fin d&apos;application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NRV10GridRevision__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <description>Date de début d&apos;application de la révision de grille</description>
    <label>Date d&apos;application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NRV10GridRevision__c/recordTypes/bonus.recordType-meta.xml
<RecordType>
    <fullName>bonus</fullName>
    <active>true</active>
    <label>Grille de Bonus</label>
</RecordType>

force-app/main/default/objects/NRV10RemunerationContract__c/NRV10RemunerationContract__c.object-meta.xml
<CustomObject>
    <label>Contrat de rémunération</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats de rémunération</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NRV10RemunerationContract__c/fields/collaborator__c.field-meta.xml
<CustomField>
    <fullName>collaborator__c</fullName>
    <formula>contract__r.collaborator__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>[#] Collaborateur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NRV10RemunerationContract__c/fields/employmentContractType__c.field-meta.xml
<CustomField>
    <fullName>employmentContractType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type de contrat de travail</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>NRV10GridRevision__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>workingContract</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NRV10GridRevision__c</referenceTo>
    <relationshipLabel>Contrats de rémunération</relationshipLabel>
    <relationshipName>Contrats_de_r_mun_ration</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NRV10RemunerationContract__c/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <formula>contract__r.endDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>[#] Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NRV10RemunerationContract__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <formula>contract__r.startDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>[#] Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NRV10RemunerationRate__c/NRV10RemunerationRate__c.object-meta.xml
<CustomObject>
    <description>Le taux de commissionnement permet de regrouper l&apos;ensemble des enregistrements représentant soit :
 - des taux de commissionnement de vente
 - des coefficients de décote
 - des taux de commissionnement d&apos;équipe
 - des bonus
 - des malus</description>
    <label>Taux de rémunération</label>
    <nameField>
        <displayFormat>TR/{YYYY}/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Taux de rémunérations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NRV10RemunerationRate__c/fields/bonusAmount__c.field-meta.xml
<CustomField>
    <fullName>bonusAmount__c</fullName>
    <label>Montant bonus/malus</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NRV10RemunerationRate__c/fields/discountCoefficient__c.field-meta.xml
<CustomField>
    <fullName>discountCoefficient__c</fullName>
    <label>Coefficient de décote</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NRV10RemunerationRate__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NRV10RemunerationRate__c/fields/turnoverLevel__c.field-meta.xml
<CustomField>
    <fullName>turnoverLevel__c</fullName>
    <label>Pallier CA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NRV10RemunerationRate__c/recordTypes/bonus.recordType-meta.xml
<RecordType>
    <fullName>bonus</fullName>
    <active>true</active>
    <label>Taux de Bonus</label>
</RecordType>

force-app/main/default/classes/TR023_SBQQ_Quote_BonusCommission.cls
/**
 * Created by 4C on 18/09/2020.
 */

public with sharing class TR023_SBQQ_Quote_BonusCommission {

    /**
     * @author Gregory Quinet
     * @date 2020-09-15
     * @description Multiple collaborator processing, create/update commissions on every sales of the list
     *
     * @param context All queried elements of sales commission processing
     */
    public static void processBonusCommissions(TR022_SBQQ_Quote_Commission.NRV10CommissionContext context) {
        System.debug('Start processing bonus commissions');
        List<NRV10Calendar__c> lastSnapshotDates;
        lastSnapshotDates = [SELECT Id, commDate__c FROM NRV10Calendar__c WHERE
                commDate__c <= TODAY ORDER BY commDate__c DESC LIMIT 2];

        if (lastSnapshotDates.isEmpty() || lastSnapshotDates.size() < 2) {
            System.debug('Can\'t find M-2 snapshotDate, cannot calculate bonus commission');
            return;
        }

        //Get all collaborators CA M-2 FROM KMDC
        System.debug('Get all sales CA on M-2 for each concerned collaborators from KMDC');
        Map<String, List<KMDC__c>> collaboratorLastCommissionsMap = new Map<String, List<KMDC__c>>();
        if (!context.collaboratorSGIds.isEmpty()) {
            for (KMDC__c CA : [
                    SELECT Id, montantHT__c, SGID__c, dateStats__c
                    FROM KMDC__c
                    WHERE
                    SGID__c IN :context.collaboratorSGIds AND dateStats__c >= :lastSnapshotDates.get(1).commDate__c
                    AND dateStats__c < :lastSnapshotDates.get(0).commDate__c
            ]) {

                if (!collaboratorLastCommissionsMap.containsKey(CA.SGID__c)) {
                    collaboratorLastCommissionsMap.put(CA.SGID__c, new List<KMDC__c>());
                }
                collaboratorLastCommissionsMap.get(CA.SGID__c).add(CA);
            }
        }
        System.debug('  -> got data for ' + collaboratorLastCommissionsMap.size() + ' collaborators');

        //get all current commissions where customer get quote or accepted it
        System.debug('Get all current sales commissions for each concerned collaborators');
        Map<Id, List<NRV10Commission__c>> collaboratorCommissionsMap = new Map<Id, List<NRV10Commission__c>>();
        for (NRV10Commission__c comm : [SELECT Id, comType__c, remuneration__c, ecPercent__c, productRate__c,
                discountCoefficient__c, teamRate__c, salesRem__c, turnoverLevel__c, orderProduct__c,
                user__c, status__c, calculationDate__c, instantDate__c FROM NRV10Commission__c WHERE user__c IN :context.collaboratorIds
        AND instantDate__c = NULL AND status__c = :Constants.COMMISSION_STATUS_COMMISSIONABLE
        AND calculationDate__c >= :lastSnapshotDates.get(0).commDate__c
        AND comType__c = :Constants.COMMISSION_TYPE_SALES]) {
            if (!collaboratorCommissionsMap.containsKey(comm.user__c)) {
                collaboratorCommissionsMap.put(comm.user__c, new List<NRV10Commission__c>());
            }
            collaboratorCommissionsMap.get(comm.user__c).add(comm);
        }

        //process collaborators to calculate bonus
        List<NRV10Commission__c> toUpsert = new List<NRV10Commission__c>();
        for (Collaborator__c c : context.collaboratorsMap.values()) {
            System.debug('Processing collaborator ' + c.Name);

            if (!context.collaboratorContractMap.containsKey(c.Id)) {
                System.debug(System.LoggingLevel.INFO, 'Collaborator don\'t have employment contract');
                continue;
            }

            //get contract according to the quote date
            NRV10RemunerationContract__c contract;
            for (NRV10RemunerationContract__c ct : context.collaboratorContractMap.get(c.Id)) {
                if (ct.startDate__c < Date.today()
                        && (ct.endDate__c == null || ct.endDate__c >= Date.today())) {
                    contract = ct;
                }
            }
            if (contract == null) {
                System.debug(System.LoggingLevel.INFO, 'Collaborator don\'t have employment contract for the period');
                continue;
            }
            System.debug('  -> Collaborator have a contract for current period: ' + contract);

            //get contract grid
            NRV10GridRevision__c ctGrid;
            if (context.contractRevisionsMap.containsKey(contract.employmentContractType__c)) {
                ctGrid = context.contractRevisionsMap.get(contract.employmentContractType__c);
            }
            if (ctGrid == null) {
                System.debug('No contract grid found for the collaborator, process next');
                continue;
            }
            System.debug('  -> Also have an associated contract grid revision: ' + ctGrid);

            //get bonus rates from bonus grid
            List<NRV10RemunerationRate__c> bonusRates = new List<NRV10RemunerationRate__c>();
            if (context.remunerationRatesGridMap.containsKey(ctGrid.bonusGridRevision__c)) {
                for(NRV10RemunerationRate__c r : context.remunerationRatesGridMap.get(ctGrid.bonusGridRevision__c)) {
                    if (r.startDate__c < Date.today() && (r.endDate__c == null || r.endDate__c >= Date.today())) {
                        bonusRates.add(r);
                    }
                }
            }
            if (bonusRates.isEmpty()) {
                System.debug('No bonus rates for the period, process next');
                continue;
            }
            System.debug('  -> Found ' + bonusRates.size() + ' bonnus rates: ' + bonusRates);

            //sum commissions to get CA
            Double totalPrev = 0.0;
            if (context.collabIdSgIdMap.containsKey(c.Id)
                    && collaboratorLastCommissionsMap.containsKey(context.collabIdSgIdMap.get(c.Id))) {

                for (KMDC__c com : collaboratorLastCommissionsMap.get(context.collabIdSgIdMap.get(c.Id))) {
                    if (com.montantHT__c != null) totalPrev = totalPrev + Double.valueOf(com.montantHT__c);
                }
            }
            System.debug('  -> Total ammount of CA for previous period is: ' + totalPrev);

            Double totalCA = 0.0;
            if (collaboratorCommissionsMap.containsKey(c.Id)) {
                for (NRV10Commission__c com : collaboratorCommissionsMap.get(c.Id)) {
                    totalCA = totalCA + Double.valueOf(com.remuneration__c);
                }
            }
            System.debug('  -> Total ammount of CA for current period is: ' + totalCA);

            Double totalBonus = 0.0;
            Double highestTO = 0.0;
            if (totalCA - totalPrev > 0) {
                System.debug('  -> CA has increased compared to last period: ' + (totalCA - totalPrev));
                for (NRV10RemunerationRate__c rem : bonusRates) {
                    if (totalCA - totalPrev > rem.turnoverLevel__c) {
                        highestTO = rem.turnoverLevel__c;
                        System.debug('  -> CA step ' + rem.turnoverLevel__c + ' has been reached, add bonus amount from ' + rem);
                        totalBonus = totalBonus + Double.valueOf(rem.bonusAmount__c);
                    }
                }
            }

            if (totalBonus > 0) {
                NRV10Commission__c bonus;
                if (context.bonusMap.containsKey(c.Id)) {
                    System.debug('  -> Collaborator already have a calculated bonus commission, update it');
                    bonus = context.bonusMap.get(c.Id);
                } else {
                    System.debug('  -> Creation of the bonus commission');
                    bonus = new NRV10Commission__c();
                    bonus.comType__c = Constants.COMMISSION_TYPE_BONUS;
                    bonus.status__c = Constants.COMMISSION_STATUS_PREVISIONEL;
                    bonus.user__c = c.Id;
                }
                bonus.totalAmountTTC__c = totalCA;
                bonus.remuneration__c = totalBonus;
                bonus.turnoverLevel__c = highestTO;
                bonus.calculationDate__c = Date.today();
                toUpsert.add(bonus);
            }
        }

        System.debug('End of bonus process, upsert ' + toUpsert.size() + ' elements');
        upsert toUpsert;
    }

}