force-app/main/default/objects/Collaborator__c/Collaborator__c.object-meta.xml
<CustomObject>
    <description>This object manage internal and external KparK collaborators.
It allow HR Team to manage collaborators  without using salesforce user management. There&apos;s two type of collaborator :
 - Internal collaborator
 - External collaborator
A collaborator is unique.</description>
    <label>Collaborateur</label>
    <nameField>
        <label>Nom complet</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Collaborateurs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Collaborator__c/fields/assignedTo__c.field-meta.xml
<CustomField>
    <fullName>assignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Site physique d&apos;affectation contractuelle du collaborateur (ex: un DO sera employé par une DO mais affecté contractuellement à un dépôt ou un magasin)</inlineHelpText>
    <label>Affecté à</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Collaborateurs (Affecté à)</relationshipLabel>
    <relationshipName>collaboratorAssignedTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collaborator__c/fields/user__c.field-meta.xml
<CustomField>
    <fullName>user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utilisateur associé</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Collaborateurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaboratorContract__c/CollaboratorContract__c.object-meta.xml
<CustomObject>
    <description>Objet permettant de définir un ou plusieurs contrat pour un collaborateur de K par K</description>
    <label>Contrat collaborateur</label>
    <nameField>
        <displayFormat>JOB/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de contrat</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrats collaborateurs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaboratorContract__c/fields/assignedTo__c.field-meta.xml
<CustomField>
    <fullName>assignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Site physique d&apos;affectation contractuelle du collaborateur (ex: un DO sera employé par une DO mais affecté contractuellement à un dépôt ou un magasin)</inlineHelpText>
    <label>Affecté à</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats collaborateurs (Affecté à)</relationshipLabel>
    <relationshipName>assignedTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaboratorContract__c/fields/collaborator__c.field-meta.xml
<CustomField>
    <fullName>collaborator__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Collaborateur</label>
    <referenceTo>Collaborator__c</referenceTo>
    <relationshipLabel>Contrats collaborateurs</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaboratorContract__c/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <description>Contrat de travail d&apos;un collaborateur</description>
    <label>Contrat</label>
</RecordType>

force-app/main/default/objects/NRV10Commission__c/NRV10Commission__c.object-meta.xml
<CustomObject>
    <description>Stocke tous les enregistrements des différentes commissions calculées par lignes de produit CPQ et avenants.
4 types de commissions possibles :
 - Commissions par vendeur calculées sur la base des produits des devis CPQ et avenants; et stockées par lignes produit
 - Commissions d&apos;équipes calculées sur la base des commissions vendeurs, en fonction des responsables d&apos;équipes (RV, RVJ, Remplaçants)
 - Commissions bonus calculées sur la base des performances des vendeurs
 - Commissions report calculées sur la base des régularisations des commissions</description>
    <label>Commission</label>
    <nameField>
        <displayFormat>COMM/{YYYY}/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NRV10Commission__c/fields/quote__c.field-meta.xml
<CustomField>
    <fullName>quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lien vers le devis sales commissionné (non rempli si la commission porte sur un devis CPQ)</description>
    <label>Devis</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/quoteCPQ__c.field-meta.xml
<CustomField>
    <fullName>quoteCPQ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Devis CPQ</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NRV10Commission__c/fields/user__c.field-meta.xml
<CustomField>
    <fullName>user__c</fullName>
    <label>Vendeur</label>
    <referenceTo>Collaborator__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TR020_CollaboratorContract.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR020_CollaboratorContract 
//-- Modifié par : SOPRA STERIA 
//-- Modifié le  : 18/12/2020
//-- Version     : 1.0
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
public without sharing class TR020_CollaboratorContract {

    /**
    * @description Méthode exécutant les différentes méthode de MAJ pour les contrats collaborateurs
    * @param userContext Objet contexte de l'utilisateur courant
    */
    public static void applyUpdateRules() {
        if (!Trigger.isExecuting) {
            return;
        }

        System.debug('@@@@ CollaboratorContract updaterules Start');
        Map<Id, CollaboratorContract__c> oldMap = (Map<Id, CollaboratorContract__c>)Trigger.oldMap;
        List<Id> collabIds = new List<Id>();
        List<Id> quoteIds = new List<Id>();

        // Parse contracts to list only those having updates in store assignment
        for (CollaboratorContract__c contract : (List<CollaboratorContract__c>)Trigger.new) {
            //process only if store assignment has changed
            if (oldMap.get(contract.Id).assignedTo__c == contract.assignedTo__c) {
                System.debug('@@ contract store assignment has not changed');
                continue;
            }

            if (!collabIds.contains(contract.collaborator__c)) {
                collabIds.add(contract.collaborator__c);
            }
        }

        System.debug('@@@ Need to process ' + collabIds.size() + ' collaborators');
        // List quotes Ids to reprocess
        if (!collabIds.isEmpty()) {
            for (NRV10Commission__c com : [SELECT Id, quoteCPQ__c, quote__c FROM NRV10Commission__c WHERE user__c IN :collabIds]) {
                if (com.quote__c != null && !quoteIds.contains(com.quote__c)) quoteIds.add(com.quote__c);
                if (com.quoteCPQ__c != null && !quoteIds.contains(com.quoteCPQ__c)) quoteIds.add(com.quoteCPQ__c);
            }
        }

        System.debug('@@@ Need to process ' + quoteIds.size() + ' quotes');
        // Launch commissions calculation if needed
        if (!quoteIds.isEmpty()) {
            System.debug('SBQQ__Quote_AfterUpdate launch remVRP commissions calculation for quotes ' + quoteIds);
            QA_QuoteProcessCommissions job = new QA_QuoteProcessCommissions(quoteIds);
            System.enqueueJob(job);
        }

    }

}