force-app/main/default/objects/fsl_tech_generateurRessource__c/fsl_tech_generateurRessource__c.object-meta.xml
<CustomObject>
    <description>CGI - FSL : Objet technique utilisé pour la création automatique des users et ressources rattachées</description>
    <label>FSL Générateur de ressource</label>
    <nameField>
        <label>FSL Générateur de ressource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FSL Générateur de ressources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_alias__c.field-meta.xml
<CustomField>
    <fullName>fsl_alias__c</fullName>
    <label>Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_communityNickname__c.field-meta.xml
<CustomField>
    <fullName>fsl_communityNickname__c</fullName>
    <label>Community Nick name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_contentEmailAsAndWhen__c.field-meta.xml
<CustomField>
    <fullName>fsl_contentEmailAsAndWhen__c</fullName>
    <label>Content Email As And When</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_contentNoEmail__c.field-meta.xml
<CustomField>
    <fullName>fsl_contentNoEmail__c</fullName>
    <label>Content No Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_dateEntree__c.field-meta.xml
<CustomField>
    <fullName>fsl_dateEntree__c</fullName>
    <label>Date d&apos;entrée</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_dateSortie__c.field-meta.xml
<CustomField>
    <fullName>fsl_dateSortie__c</fullName>
    <label>Date de sortie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_defaultGroupNotificationFrequency__c.field-meta.xml
<CustomField>
    <fullName>fsl_defaultGroupNotificationFrequency__c</fullName>
    <label>Default Notification Frequency when Join</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_depotCodeGC__c.field-meta.xml
<CustomField>
    <fullName>fsl_depotCodeGC__c</fullName>
    <label>Code GC du dépôt</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_digestFrequency__c.field-meta.xml
<CustomField>
    <fullName>fsl_digestFrequency__c</fullName>
    <label>Chatter Email Highlights Frequency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_email__c.field-meta.xml
<CustomField>
    <fullName>fsl_email__c</fullName>
    <description>CGI - FSL : Email de l&apos;utilisateur</description>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_emailEncodingKey__c.field-meta.xml
<CustomField>
    <fullName>fsl_emailEncodingKey__c</fullName>
    <label>Email Encoding</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_firstName__c.field-meta.xml
<CustomField>
    <fullName>fsl_firstName__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_languageLocaleKey__c.field-meta.xml
<CustomField>
    <fullName>fsl_languageLocaleKey__c</fullName>
    <label>Language</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_lastName__c.field-meta.xml
<CustomField>
    <fullName>fsl_lastName__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_localeSidKey__c.field-meta.xml
<CustomField>
    <fullName>fsl_localeSidKey__c</fullName>
    <label>Locale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_matriculeGC__c.field-meta.xml
<CustomField>
    <fullName>fsl_matriculeGC__c</fullName>
    <externalId>true</externalId>
    <label>Matricule GC</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_messageErreur__c.field-meta.xml
<CustomField>
    <fullName>fsl_messageErreur__c</fullName>
    <label>Message d&apos;erreur</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_metier__c.field-meta.xml
<CustomField>
    <fullName>fsl_metier__c</fullName>
    <label>Métier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_mobilePhone__c.field-meta.xml
<CustomField>
    <fullName>fsl_mobilePhone__c</fullName>
    <label>Cell</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_name__c.field-meta.xml
<CustomField>
    <fullName>fsl_name__c</fullName>
    <label>Full Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_phone__c.field-meta.xml
<CustomField>
    <fullName>fsl_phone__c</fullName>
    <label>Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_roleID__c.field-meta.xml
<CustomField>
    <fullName>fsl_roleID__c</fullName>
    <label>Role ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_SGID__c.field-meta.xml
<CustomField>
    <fullName>fsl_SGID__c</fullName>
    <label>SGID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_statut__c.field-meta.xml
<CustomField>
    <fullName>fsl_statut__c</fullName>
    <label>Statut d&apos;intégration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_timeZoneSidKey__c.field-meta.xml
<CustomField>
    <fullName>fsl_timeZoneSidKey__c</fullName>
    <label>Time Zone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_title__c.field-meta.xml
<CustomField>
    <fullName>fsl_title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_typePlanification__c.field-meta.xml
<CustomField>
    <fullName>fsl_typePlanification__c</fullName>
    <label>Type de planification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/fsl_tech_generateurRessource__c/fields/fsl_username__c.field-meta.xml
<CustomField>
    <fullName>fsl_username__c</fullName>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TR001_fsl_GenerateurRessource.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR001_fsl_GenerateurRessource
//-- Modifié par : CGI - FSL
//-- Modifié le  : 09/04/2018
//-- Description : Classe exécutée par le PB - Création auto d'un user ou modification s'il existe déjà
//-- Version     : 1.0
//-- --------------------------------------------------------------------------------- --

public with sharing class TR001_fsl_GenerateurRessource {
 
    
    @InvocableMethod
    public static void createUser(List<fsl_tech_generateurRessource__c> userRessourceList){
        system.debug('################## Start - TR001_fsl_GenerateurRessource ');

        // Variables globales
        List<User> userToUpsertList = new List<User>();
		Map<String, fsl_tech_generateurRessource__c> generatorMap = new Map <String,fsl_tech_generateurRessource__c>();
        Map<ID, fsl_tech_generateurRessource__c> generatorRoleMap = new Map <ID,fsl_tech_generateurRessource__c>();
		Map<String, ID> userMap = new Map <String,ID>();
        FieldServiceError generatedError = new FieldServiceError();
        
        // Construction des collections par SOQL
        for (fsl_tech_generateurRessource__c gnr :  userRessourceList) {
				generatorMap.put(gnr.fsl_matriculeGC__c, gnr);  
                generatorRoleMap.put(gnr.fsl_roleID__c, gnr); 
        }
		for (User usr : [Select ID, matriculeGC__c From User where matriculeGC__c IN :generatorMap.KeySet()]) {
				userMap.put(usr.matriculeGC__c, usr.ID);  
        }
        Map<String, ID> profileMap = FieldServiceUtils.loadFslProfileMap();

        //Préparation des User à créer/modifier
        for (fsl_tech_generateurRessource__c generator : userRessourceList) {

            // Etape 0 : Contrôle des données de référence   
            if ((generator.fsl_roleID__c != null) && !generatorRoleMap.containsKey(generator.fsl_roleID__c)){
                system.debug('################## DEBUG - Erreur code 1 : roleID inexistant');
                generator.fsl_statut__c = '1';
                generator.fsl_messageErreur__c = 'Erreur roleID inexistant : '+generator.fsl_roleID__c;
                generatorMap.put(generator.fsl_matriculeGC__c, generator);
                throw new FieldServiceException(generator.fsl_messageErreur__c);
            }
        
            // Etape 1 : Création de la liste des utilisateurs à crééer/modifier 
            User userToUpsert = new User();
			try{  
                userToUpsert.Alias = generator.fsl_alias__c;
                userToUpsert.CommunityNickname = generator.fsl_communityNickname__c;
                userToUpsert.DefaultGroupNotificationFrequency = generator.fsl_defaultGroupNotificationFrequency__c;
                userToUpsert.DigestFrequency = generator.fsl_digestFrequency__c;
                userToUpsert.EmailEncodingKey = generator.fsl_emailEncodingKey__c;                
                userToUpsert.LanguageLocaleKey = generator.fsl_languageLocaleKey__c;                
                userToUpsert.LocaleSidKey = generator.fsl_localeSidKey__c;                
                userToUpsert.Phone = generator.fsl_phone__c;   
                userToUpsert.UserRoleId = generator.fsl_roleID__c; 
                system.debug('**profileMap'+profileMap);
                if(profileMap.containsKey(generator.fsl_typePlanification__c))
                    userToUpsert.ProfileId = profileMap.get(generator.fsl_typePlanification__c);
                userToUpsert.TimeZoneSidKey = generator.fsl_timeZoneSidKey__c;                
                userToUpsert.Title = generator.fsl_title__c;                
                userToUpsert.Username = generator.fsl_username__c;                
                userToUpsert.UserPreferencesContentEmailAsAndWhen = Boolean.valueOf(generator.fsl_contentEmailAsAndWhen__c);                
                userToUpsert.UserPreferencesContentNoEmail = Boolean.valueOf(generator.fsl_contentNoEmail__c);                
                userToUpsert.Phone = generator.fsl_phone__c;                
                userToUpsert.MobilePhone = generator.fsl_mobilePhone__c;               
                userToUpsert.Username = generator.fsl_username__c ;
                userToUpsert.Email = generator.fsl_email__c;
                userToUpsert.typePlanification__c = generator.fsl_typePlanification__c;
                userToUpsert.matriculeGC__c = generator.fsl_matriculeGC__c;
                userToUpsert.metier__c  = generator.fsl_metier__c;
                userToUpsert.SGID__c = generator.fsl_SGID__c;
                userToUpsert.codeDepot__c = generator.fsl_depotCodeGC__c;
                
                // Calcul des champs Nom et Prénom  
                if ((generator.fsl_firstName__c != null &&  generator.fsl_lastName__c != null)){               
                    userToUpsert.FirstName = generator.fsl_firstName__c;
                    userToUpsert.LastName = generator.fsl_lastName__c;
                }
                else if (generator.fsl_name__c != null){               
                    userToUpsert.LastName = generator.fsl_name__c;
                }
                 
                userToUpsert.dateEntree__c  =  Date.parse(generator.fsl_dateEntree__c);
                if (generator.fsl_dateSortie__c != null)
                    userToUpsert.dateSortie__c  =  Date.parse(generator.fsl_dateSortie__c);
                userToUpsert.codeDepot__c = generator.fsl_depotCodeGC__c;
                
                // Calcul de l'activation du user
                if(userToUpsert.dateEntree__c <= System.today() && (userToUpsert.dateSortie__c == null || userToUpsert.dateSortie__c >= System.today() ))
                    userToUpsert.isActive = true;
                
                if (userMap.containsKey(userToUpsert.matriculeGC__c)){
                    userToUpsert.id = userMap.get(userToUpsert.matriculeGC__c);
                }
                userToUpsertList.add(userToUpsert);   

            } catch (Exception e){
                system.debug('################## DEBUG - Erreur Conversion du générateur de ressource en User '+generator);
                String subject = 'Erreur Conversion du générateur de ressource en User';
                generatedError.addExeptionError(e,subject);
        	}     
        }
  
		// Création de l'utilisateur  
        if (!userToUpsertList.isEmpty()){       
			// Etape 2 : Création/Modification des utilisateurs et attribution des permissions
			ID jobID = System.enqueueJob(new TR002_fsl_GenerateurRessource(userToUpsertList,generatorMap,generatedError));    
		}

    }   
}