force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Gestion des factures basée sur la modélisation du module Salesforce Billing</description>
    <label>Facture</label>
    <nameField>
        <displayFormat>FAC/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de la facture</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Order.RecordTypeId</field>
            <operation>equals</operation>
            <value>Commande client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/deliveryDate__c.field-meta.xml
<CustomField>
    <fullName>deliveryDate__c</fullName>
    <label>Date de livraison</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/perceivedAmount__c.field-meta.xml
<CustomField>
    <fullName>perceivedAmount__c</fullName>
    <description>Dans le cas d&apos;un paiement d&apos;acompte ou d&apos;une attribution de paiement avec un reste du paiement</description>
    <label>Montant perçu</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/workOrder__c.field-meta.xml
<CustomField>
    <fullName>workOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de rendez-vous</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>WorkOrder.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>workOrderService</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Facture</label>
</RecordType>

force-app/main/default/objects/InvoiceLine__c/InvoiceLine__c.object-meta.xml
<CustomObject>
    <description>Ligne de facture basée sur la modélisation des factures du module Salesforce Billing</description>
    <label>Ligne de facture</label>
    <nameField>
        <displayFormat>LFAC/{YYYY}/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes de facture</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceLine__c/fields/asset__c.field-meta.xml
<CustomField>
    <fullName>asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Actif</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/autoComputedAmount__c.field-meta.xml
<CustomField>
    <fullName>autoComputedAmount__c</fullName>
    <formula>invoice__r.autoComputedAmount__c</formula>
    <label>[#] Montant auto calculé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <label>Facture</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.isParentLine__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/isBillable__c.field-meta.xml
<CustomField>
    <fullName>isBillable__c</fullName>
    <formula>ISPICKVAL(type__c, &apos;Produit&apos;) &amp;&amp; isParentLine__c</formula>
    <label>[#] Est facturable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/lineNumber__c.field-meta.xml
<CustomField>
    <fullName>lineNumber__c</fullName>
    <label>Numéro de ligne</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/location__c.field-meta.xml
<CustomField>
    <fullName>location__c</fullName>
    <label>Emplacement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/orderItem__c.field-meta.xml
<CustomField>
    <fullName>orderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne de la commande client</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>OrderItem.orderRecordType__c</field>
            <operation>equals</operation>
            <value>CustomerOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceLine__c/fields/parentLine__c.field-meta.xml
<CustomField>
    <fullName>parentLine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ligne de facture parent</label>
    <referenceTo>InvoiceLine__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>ParentInvoiceLines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IV_InsertInvoiceFromServiceAppointment.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : IV_InsertInvoiceFromServiceAppointment
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 10/02/2022
//-- Version     : 1.0
//-- * 1.0 - Init
//-- --------------------------------------------------------------------------------- --
public without sharing class IV_InsertInvoiceFromServiceAppointment {
    private static final String SERVICEAPPOINTMENT_SERVICEAPPOINTMENT_RTID = DAL.getRecordTypeIdByDevName('ServiceAppointment', 'ServiceAppointment');
    private static final String INVOICE_INVOICE_RTID = DAL.getRecordTypeIdByDevName('Invoice__c', Constants.INVOICE_INVOICE_RT);
        
    @InvocableMethod(label='Action facturation depuis un rendez-vous de service')
    public static List<FlowOutputParameters> insertInvoiceFromServiceAppointment(List<FlowInputParameters> inputList) {
        System.debug('### DEBUT IV_InsertInvoiceFromServiceAppointment.insertInvoiceFromServiceAppointment');
        List<FlowOutputParameters> outputList = new List<FlowOutputParameters>();
        List<String> assetIds = new List<String>();
        List<Asset> serviceAppointmentAssets = new List<Asset>();
        List<Asset> assetChildren = new List<Asset>();

        // Sauvegarde
        System.Savepoint sp = Database.setSavepoint();
        
        try {
            String serviceAppointmentId = inputList[0].serviceAppointmentId;
            if(String.isBlank(serviceAppointmentId)) {                
                throw new FlowActionException('Id de RDV inexistante');
            }
            System.debug('## serviceAppointmentId: '+serviceAppointmentId);
            
            // 0 – Initialisation des ressources internes
            ServiceAppointment serviceAppointment = [SELECT Id, customerOrder__c, ParentRecordId, SchedStartTime FROM ServiceAppointment 
                                                        WHERE RecordTypeId =: SERVICEAPPOINTMENT_SERVICEAPPOINTMENT_RTID
                                                        AND Id = :serviceAppointmentId];

            List<WorkOrderLineItem> woliList = [SELECT Id, AssetId FROM WorkOrderLineItem WHERE WorkOrderId = :serviceAppointment.ParentRecordId];
            
            if(!woliList.isEmpty()) {
                for(WorkOrderLineItem woli : woliList) {
                    assetIds.add(woli.AssetId);
                }
            }
            
            if(!assetIds.isEmpty()) {
                serviceAppointmentAssets = [SELECT Id, orderItem__c, locationFormula__c FROM Asset WHERE Id IN:assetIds];
                assetChildren = [SELECT Id, orderItem__c, ParentId, locationFormula__c FROM Asset WHERE ParentId IN:assetIds];
            }

            Invoice__c invoice = new Invoice__c();
            invoice.recordTypeId = INVOICE_INVOICE_RTID;
            invoice.OwnerId = Label.System_id_user_kpark;
            invoice.customerOrder__c = serviceAppointment.customerOrder__c;
            invoice.workOrder__c = serviceAppointment.ParentRecordId;
            invoice.autoComputedAmount__c = true;
            
            // Eléments comptables
            invoice.deliveryDate__c = serviceAppointment.schedStartTime.date();
            invoice.perceivedAmount__c = 0;
            insert invoice;
            
            // 2 – Alimentation des lignes de facture
            
            // 2.1 - Lignes des actifs associés aux WOLI
            List<InvoiceLine__c> invoiceLinesParent = new List<InvoiceLine__c>() ;
            List<InvoiceLine__c> invoiceLinesChild = new List<InvoiceLine__c>() ;
            List<InvoiceLine__c> invoiceLinesAddAfter = new List<InvoiceLine__c>() ;
            
            // Parcours des assets de 1er niveau/parent
            for (Integer i = 0; i < serviceAppointmentAssets.size(); i++) {
                Asset asset = serviceAppointmentAssets.get(i);
                InvoiceLine__c invoiceLine = new InvoiceLine__c();
                
                invoiceLine.invoice__c = invoice.Id;
                invoiceLine.location__c = asset.locationFormula__c;
                invoiceLine.asset__c = asset.Id;
                invoiceLine.orderItem__c = asset.orderItem__c;
                invoiceLine.lineNumber__c = i;
                
                invoiceLinesParent.add(invoiceLine);
            }
            if(!invoiceLinesParent.isEmpty()) {
                insert invoiceLinesParent;
            }
            
            // Parcours des assets de 2nd niveau/fils
            for (Integer j = 0; j < assetChildren.size(); j++) {
                InvoiceLine__c invoiceSubLine = new InvoiceLine__c();
                Asset subAsset = assetChildren.get(j);
                invoiceSubLine.invoice__c = invoice.Id;
                invoiceSubLine.asset__c = subAsset.Id;
                invoiceSubLine.location__c = subAsset.locationFormula__c;
                invoiceSubLine.orderItem__c = subAsset.orderItem__c;
                invoiceSubLine.lineNumber__c = j * 100 + j;
                for(InvoiceLine__c invParent : invoiceLinesParent) {
                    if(invParent.asset__c == subAsset.ParentId) {
                        invoiceSubLine.lineNumber__c = invParent.lineNumber__c * 100 + j;
                        invoiceSubLine.parentLine__c = invParent.Id;
                    }
                }
                
                invoiceLinesChild.add(invoiceSubLine);       
            }
            
            if(!invoiceLinesChild.isEmpty()) {
                insert invoiceLinesChild;
            }
            
            // 2.2 - Lignes de commandes de 1er niveau/parent non convertibles en asset
            List<Asset> orderAssets = [SELECT Id FROM Asset WHERE customerOrder__c =:serviceAppointment.customerOrder__c AND isBillable__c = true];
            for(Integer i = orderAssets.size() - 1; i >= 0; i--) {
                for(Asset toRemove : serviceAppointmentAssets) {
                    if(orderAssets[i].Id == toRemove.Id) {
                        orderAssets.remove(i);
                    }
                }
            }
            
            if (orderAssets.isEmpty()) { // Tous les assets restants à facturer (isBillable__c = true) correspondent aux assets de ce RDV. De ce fait, il reste à facturer les lignes de commande qui ne sont pas convertibles en asset (ex: Echafaudage, grue, etc.)
                List<OrderItem> orderItems = [SELECT Id FROM OrderItem WHERE orderId = :serviceAppointment.customerOrder__c AND parentOrderItem__c = null AND Product2.isConvertibleAsset__c = false]; // Sous-requête à intégrer dans la requête principale
                    
                    for (Integer i = 0; i < orderItems.size(); i++) {
                        OrderItem orderItem = orderItems.get(i);
                        InvoiceLine__c invoiceLine = new InvoiceLine__c();
                        invoiceLine.invoice__c = invoice.Id;
                        invoiceLine.orderItem__c = orderItem.Id;
                        invoiceLine.lineNumber__c = serviceAppointmentAssets.size() + i;
                        
                        invoiceLinesAddAfter.add(invoiceLine);
                    }
            }
            if(!invoiceLinesAddAfter.isEmpty()) {
                insert invoiceLinesAddAfter;
            }

            // Alimentation variable de sortie
            FlowOutputParameters out = new FlowOutputParameters();
            out.invoiceId = invoice.Id;
            out.invoiceName = invoice.Name;
            outputList.add(out);
            
            System.debug('### FIN IV_InsertInvoiceFromServiceAppointment.insertInvoiceFromServiceAppointment');
            return outputList;
        }catch(Exception e){
            Database.rollback(sp);
            System.debug('ERREUR : ' + e.getMessage() + ' ' + e.getTypeName() + ' ' + e.getStackTraceString());
            throw e;
        }
    }
    
    /* Input parameters for the Apex action */
    public class FlowInputParameters{
        @InvocableVariable(label='Id du rendez-vous de service' required = true )
        public String serviceAppointmentId;
    }
    
    /* Output parameters of the Apex action */
    public class FlowOutputParameters{
        @InvocableVariable(label='Id de la facture')
        public String invoiceId;
        @InvocableVariable(label='Nom de la facture')
        public String invoiceName;
    }

    public class FlowActionException extends Exception {}
}