force-app/main/default/objects/Incentive__c/Incentive__c.object-meta.xml
<CustomObject>
    <label>Incentive</label>
    <nameField>
        <label>Nom de Incentive</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incentive__c/fields/CodeIncentive__c.field-meta.xml
<CustomField>
    <fullName>CodeIncentive__c</fullName>
    <externalId>true</externalId>
    <label>Code Incentive</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incentive__c/fields/DebutValidite__c.field-meta.xml
<CustomField>
    <fullName>DebutValidite__c</fullName>
    <label>Début Validité</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Incentive__c/fields/Magasinselligibles__c.field-meta.xml
<CustomField>
    <fullName>Magasinselligibles__c</fullName>
    <label>Magasins elligibles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incentive__c/fields/OriginesElligibles__c.field-meta.xml
<CustomField>
    <fullName>OriginesElligibles__c</fullName>
    <label>Origines Elligibles</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incentive__c/fields/TypePromotion__c.field-meta.xml
<CustomField>
    <fullName>TypePromotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type Promotion</label>
    <referenceTo>TypePromotion__c</referenceTo>
    <relationshipLabel>Incentives</relationshipLabel>
    <relationshipName>Incentives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IncentivePromotion__c/IncentivePromotion__c.object-meta.xml
<CustomObject>
    <label>Incentive Promotion</label>
    <nameField>
        <label>Nom de Incentive Promotion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incentives Promotion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IncentivePromotion__c/fields/Codeincentive__c.field-meta.xml
<CustomField>
    <fullName>Codeincentive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Incentive
GC_ioptions.inc_code</description>
    <label>Code incentive</label>
    <referenceTo>Incentive__c</referenceTo>
    <relationshipLabel>Incentives Promotion</relationshipLabel>
    <relationshipName>Incentives_Promotion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IncentivePromotion__c/fields/CodeOption__c.field-meta.xml
<CustomField>
    <fullName>CodeOption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Option Référentiel
GC_ioptions.opt_code</description>
    <label>Code Option</label>
    <referenceTo>ReferentielOptions__c</referenceTo>
    <relationshipLabel>Incentives Promotion</relationshipLabel>
    <relationshipName>Incentives_Promotion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IncentivePromotion__c/fields/ModeValorisation__c.field-meta.xml
<CustomField>
    <fullName>ModeValorisation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mode de valorisation de la promotion (% ou valeur)
GC_ioptions.oiop_type</description>
    <label>Mode Valorisation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IncentivePromotion__c/fields/ValorisationPromotion__c.field-meta.xml
<CustomField>
    <fullName>ValorisationPromotion__c</fullName>
    <label>Valorisation Promotion</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Option__c/Option__c.object-meta.xml
<CustomObject>
    <description>Option pour les lignes de devis Kube2</description>
    <label>Devis Ligne Option</label>
    <nameField>
        <displayFormat>OP-{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Devis Ligne Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Option__c/fields/Categorie__c.field-meta.xml
<CustomField>
    <fullName>Categorie__c</fullName>
    <label>Catégorie</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Codeoption__c.field-meta.xml
<CustomField>
    <fullName>Codeoption__c</fullName>
    <externalId>true</externalId>
    <label>Code option</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/ligneDevis__c.field-meta.xml
<CustomField>
    <fullName>ligneDevis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Champ reliant l&apos;option à la ligne de devis correspondante. 
Ancien champ Lignedevis_del__c renommé</description>
    <label>Ligne devis</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Devis Ligne Options (Ligne devis)</relationshipLabel>
    <relationshipName>Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Non_Configuree__c.field-meta.xml
<CustomField>
    <fullName>Non_Configuree__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non Configurée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Option</label>
    <referenceTo>ReferentielOptions__c</referenceTo>
    <relationshipName>Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Pack__c.field-meta.xml
<CustomField>
    <fullName>Pack__c</fullName>
    <label>Pack</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/PrixHT__c.field-meta.xml
<CustomField>
    <fullName>PrixHT__c</fullName>
    <description>Alimenté par configurateur</description>
    <formula>PrixunitaireHT__c * Quantite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prix HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/PrixunitaireHT__c.field-meta.xml
<CustomField>
    <fullName>PrixunitaireHT__c</fullName>
    <label>PrixunitaireHT</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Option__c/fields/Valorisation__c.field-meta.xml
<CustomField>
    <fullName>Valorisation__c</fullName>
    <description>Alimenté par configurateur</description>
    <label>Valorisation</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pack__c/Pack__c.object-meta.xml
<CustomObject>
    <label>Pack</label>
    <nameField>
        <label>Nom du pack</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pack__c/fields/ModeValorisation__c.field-meta.xml
<CustomField>
    <fullName>ModeValorisation__c</fullName>
    <label>Mode Valorisation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReferentielOptions__c/ReferentielOptions__c.object-meta.xml
<CustomObject>
    <label>Référenciel Options</label>
    <nameField>
        <label>Nom de Référentiel Options</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référenciel Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReferentielOptions__c/fields/CodeOption__c.field-meta.xml
<CustomField>
    <fullName>CodeOption__c</fullName>
    <externalId>true</externalId>
    <label>Code Option</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReferentielOptions__c/fields/Debutvalidite__c.field-meta.xml
<CustomField>
    <fullName>Debutvalidite__c</fullName>
    <description>Renommer &quot;Date Validité&quot;
Date de début de validité de l&apos;option
GC_options.valide = 0</description>
    <label>Début validité</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ReferentielOptions__c/fields/FinValidite__c.field-meta.xml
<CustomField>
    <fullName>FinValidite__c</fullName>
    <label>Fin Validité</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ReferentielOptions__c/fields/OptionPromotionnelle__c.field-meta.xml
<CustomField>
    <fullName>OptionPromotionnelle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Option Promotionnelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ReferentielOptions__c/fields/PrixReferencePromotion__c.field-meta.xml
<CustomField>
    <fullName>PrixReferencePromotion__c</fullName>
    <label>Prix Référence Promotion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReferentielOptions__c/fields/Typedeloption__c.field-meta.xml
<CustomField>
    <fullName>Typedeloption__c</fullName>
    <label>Type de l&apos;option</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReferentielOptions__c/fields/TypePromotion__c.field-meta.xml
<CustomField>
    <fullName>TypePromotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type Promotion</label>
    <referenceTo>TypePromotion__c</referenceTo>
    <relationshipName>R_f_rentiels_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReferentielOptions__c/fields/UnitedevalorisationPromotion__c.field-meta.xml
<CustomField>
    <fullName>UnitedevalorisationPromotion__c</fullName>
    <label>Unité de valorisation Promotion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReferentielOptions__c/fields/Valorisationmodifiable__c.field-meta.xml
<CustomField>
    <fullName>Valorisationmodifiable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valorisation modifiable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tarif_Option__c/Tarif_Option__c.object-meta.xml
<CustomObject>
    <label>Tarif Option</label>
    <nameField>
        <label>Nom de Tarif Option</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tarifs Option</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif_Option__c/fields/Referentieloptions__c.field-meta.xml
<CustomField>
    <fullName>Referentieloptions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Référentiel options</label>
    <referenceTo>ReferentielOptions__c</referenceTo>
    <relationshipLabel>Tarifs Option</relationshipLabel>
    <relationshipName>Tarifs_Option</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif_Option__c/fields/Valorisationdeloption__c.field-meta.xml
<CustomField>
    <fullName>Valorisationdeloption__c</fullName>
    <description>Valorisation de l&apos;option
GC_optprix.opp_valeur</description>
    <label>Valorisation de l&apos;option</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TypePromotion__c/TypePromotion__c.object-meta.xml
<CustomObject>
    <label>Type Promotion</label>
    <nameField>
        <label>Nom de Type Promotion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types Promotion</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TypePromotion__c/fields/TypePromotion__c.field-meta.xml
<CustomField>
    <fullName>TypePromotion__c</fullName>
    <description>Michael affirme et assure que ce champ sera unique et utilisé comme &quot;Identificateur de champ unique&quot;</description>
    <externalId>true</externalId>
    <label>Type Promotion</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Utils_Configurator.cls
//-- -------------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Utils_Configurator
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 10/12/2020
//-- Version     : 1.4
//-- * 1.4 : Déplacement fonction calcul CEE dans Utils_CEE
//-- * 1.3 : Correction bug de code magasin (caractère * possible)
//-- -------------------------------------------------------------------------------------- --
public without sharing class Utils_Configurator {
    
    public static string getCodeMagasinNum(string codeMag){
        string codeMagNum = codeMag;
        if(codeMag == null || codeMag == '*')
            codeMagNum = '';
        else if(codeMag.startsWith('MAG0'))
            codeMagNum = codeMag.substring(4);
        return codeMagNum;
    }

    public static Boolean isProjetEligible(Quote q, Incentive__c inc){
        if(isContained(inc.OriginesElligibles__c, MappingUtils.getCodeOrigine(q.source__c))) {
            if(inc.DebutValidite__c <= q.referenceDate__c && q.referenceDate__c <= inc.FinValidite__c){
                if (q.opportunity.owner.codeMagasin__c != null && q.opportunity.owner.codeMagasin__c != '*') {
                    if(isContained(inc.Magasinselligibles__c , Integer.valueOf(getCodeMagasinNum(q.opportunity.owner.codeMagasin__c)))){
                        return true;
                    }
                } else
                    return false;
            }
        }
        return false;
    }

    private static boolean isContained(String container, Integer contained){
        if(container == '*')
            return true;
        if(container == null)
            container = '';
        for(string containerStr : container.split('\\|')){
            if(Integer.valueOf(containerStr) == contained)
                return true;
        }
        return false;
    }

    public static void recalculerTarifOptions(Quote q){
        List<Option__c> optList = DAL.getOptionList(q.Id);
        Map<id, ReferentielOptions__c> refOptMap = DAL.getRefOptMap(q, DAL.makeSet(optList, 'option__c'));
        Map<id,IncentivePromotion__c> incentiveMap = initIncentives(q, refOptMap);
        //system.debug('\n\n\n\n\n RECALCULER TARIF '+optList[0]+' \n\n\n\n\n\n');
        for(Option__c opt : optList){
            Decimal oldValorisation = opt.valorisation__c;
            opt.non_configuree__c = true;
            opt.valorisation__c = null;
            ReferentielOptions__c refOpt = refOptMap.get(opt.option__c);
            if(refOpt == null || !afficherOption(q,refOpt,opt.ligneDevis__r))
                    continue;
            Decimal valorisation = (refOpt.Valorisationmodifiable__c) ? oldValorisation : getValorisation(q,refOpt,incentiveMap);
            if(valorisation == null && refOpt.OptionPromotionnelle__c && refOpt.CodeOption__c != Constants.EcoPrime)
                    continue;
            opt.non_configuree__c = false;
            opt.valorisation__c = valorisation;
        }
        update optList;
        changeQuoteLIPrice(optList);
    }

    private static void changeQuoteLIPrice(List<Option__c> optList){
        List<Option__c> optListNew = DAL.getOptionList(optList);
        Map<id,QuoteLineItem> qliMap = new Map<id,QuoteLineItem>();
        for(Option__c o : optListNew){
            o.ligneDevis__r.PrixunitaireHTtarifoptions__c = 0;
            o.ligneDevis__r.Remise_Enseigne__c = 0;
            o.ligneDevis__r.Aconfigurer__c = false;
            o.ligneDevis__r.PrixunitaireHTtarifoptions__c = 0 /* price */;
            o.ligneDevis__r.remise_enseigne__c = 0 /* remiseEnseigne */;
            if(o.ligneDevis__r.unitprice == null)
                    o.ligneDevis__r.unitprice = 0;
            qliMap.put(o.ligneDevis__c, o.ligneDevis__r);
        }

        List<Option__c> optRefPromoList = new List<Option__c>();
        // Pour chaque options, on vérifie si elles sont des promotions, on calcul le prix et on ajoute dans une liste
        for(Option__c o : optListNew) {
            if(isReferencePromotion(o.option__r))
                optRefPromoList.add(o);
            else if((o.PrixHT__c != null) && (Utils_Configurator.isRemiseEnseigne(o)) != true)
                o.ligneDevis__r.PrixunitaireHTtarifoptions__c += o.PrixHT__c;
        }

        // Mise à jour du prix des options si promotion
        for (Option__c o : optRefPromoList)
            o.PrixunitaireHT__c = o.Valorisation__c / 100 * (o.ligneDevis__r.PrixunitaireHTtarifoptions__c + o.ligneDevis__r.unitprice);

        update optRefPromoList;
        update qliMap.values();

        // Calcul de la remise
        qliMap.clear();
        optListNew = DAL.getOptionList(optList);
        ID lastId = null;
        for(Option__c o : optListNew){
            if(isRemiseEnseigne(o) && String.isNotBlank(o.ligneDevis__c)) {
                lastId = o.ligneDevis__c;
                o.ligneDevis__r.remise_enseigne__c = (o.ligneDevis__r.remise_enseigne__c + ((o.PrixHT__c * o.ligneDevis__r.Quantity) * (1 + (o.ligneDevis__r.tvaPourcentage__c / 100)))).setScale(2);
                qliMap.put(o.ligneDevis__c, o.ligneDevis__r);
            }
        }

        // Mise à jour de la ligne de devis
        update qliMap.values();
    }

    public static Map<id,IncentivePromotion__c> initIncentives(Quote q, Map<id, ReferentielOptions__c> refOptMap){
        Map<id,IncentivePromotion__c> incentiveMap = new Map<id,IncentivePromotion__c>();
        List<IncentivePromotion__c> incList = DAL.getIncentivePromoList(q, refOptMap);
        for(IncentivePromotion__c inc : incList)
            incentiveMap.put(inc.CodeOption__c,inc);
        return incentiveMap;
    }

    private static decimal getValorisationSpeciale(Quote q, ReferentielOptions__c refOpt, Map<id,IncentivePromotion__c> incentiveMap){
        IncentivePromotion__c incentivePromo = incentiveMap.get(refOpt.Id);
        if(incentivePromo == null)
            return getTarification(refOpt);
        Decimal valoRef =  getTarification(refOpt), valoIncentive = incentivePromo.ValorisationPromotion__c;
        if(isProjetEligible(q, incentivePromo.Codeincentive__r)){
            if(refOpt.UnitedevalorisationPromotion__c == 1){
                if(incentivePromo.ModeValorisation__c && valoRef != null &&  valoIncentive != null)
                    return (valoRef * valoIncentive) / 100;
                else if(!incentivePromo.ModeValorisation__c && valoIncentive != null)
                    return valoIncentive;
            } else if(refOpt.UnitedevalorisationPromotion__c == 2){
                if(incentivePromo.ModeValorisation__c && valoRef != null &&  valoIncentive != null)
                    return valoRef + ((valoRef * valoIncentive) / 100);
                else if(!incentivePromo.ModeValorisation__c && valoRef != null &&  valoIncentive != null)
                    return valoRef + valoIncentive;
            }
        }
        return null;
    }

    private static decimal getTarification(ReferentielOptions__c refOpt){
        if(refOpt.Tarifs_Option__r.size() > 0 )
            return refOpt.Tarifs_Option__r[0].Valorisationdeloption__c;
        return null;
    }

    public static decimal getValorisation(Quote q, ReferentielOptions__c refOpt, Map<id,IncentivePromotion__c> incentiveMap){
        Decimal result;
        if(valorisationSpeciale(refOpt)){
            result = getValorisationSpeciale(q,refOpt,incentiveMap);
            if(result == 0)
                result = null;
        }
        else
            result = getTarification(refOpt);
        return result;
    }

    private static boolean valorisationSpeciale(ReferentielOptions__c refOpt){
        if(refOpt.OptionPromotionnelle__c && refOpt.CodeOption__c == Constants.EcoPrime)
            return false;
        if(refOpt.OptionPromotionnelle__c)
            return true;
        return false;
    }

    public static boolean afficherOption(Quote q, ReferentielOptions__c refOpt, QuoteLineItem qli){
        if(refOpt.OptionPromotionnelle__c){
            if(refOpt.Debutvalidite__c <= q.referenceDate__c && q.referenceDate__c <= refOpt.FinValidite__c){
                if(refOpt.CodeOption__c == Constants.EcoPrime){
                    return 'Oui'.equalsIgnoreCase(q.C2E__c);
                }
                if(refOpt.TypePromotion__r.TypePromotion__c == Constants.campagneType){
                    if(qli.Code_Promo_Formule__c == null || qli.Code_Promo_Formule__c != refOpt.codeOption__c)
                        return false;
                }
            }
            else
                return false;
        }
        return true;
    }

    // Détermine si l'option est une remise enseigne
    //--------------------------------------------------------
    public static boolean isRemiseEnseigne(Option__c opt){
        return (opt.Option__r.OptionPromotionnelle__c && (opt.Pack__c == Constants.PACKCOMM && opt.Categorie__c != Constants.REMISESLEGALES));
    }

    // Détermine si l'option est référence de promotion
    //--------------------------------------------------------
    public static boolean isReferencePromotion(ReferentielOptions__c refOpt){
        return (refOpt.Typedeloption__c == 2 && refOpt.PrixReferencePromotion__c == 1 && refOpt.OptionPromotionnelle__c);
    }

    // Détermine si l'option est une option de marketing
    //--------------------------------------------------------
    public static boolean isOPMarket(Option__c opt){
        return (opt.Option__r.OptionPromotionnelle__c && opt.Option__r.typePromotion__r.name != Constants.ECOSUBVENT);
    }

    public class MyException extends Exception{}
}