force-app/main/default/objects/OrderNonCompliance__c/OrderNonCompliance__c.object-meta.xml
<CustomObject>
    <description>Objet permettant de définir les non conformités d&apos;une commande client</description>
    <label>Non-conformité commande</label>
    <nameField>
        <label>Motif</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non-conformités commande</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderNonCompliance__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <label>Commande client</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Non-conformités commande</relationshipLabel>
    <relationshipName>OrderNonCompliances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderNonCompliance__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En cours</fullName>
                <default>true</default>
                <label>En cours</label>
            </value>
            <value>
                <fullName>Clôturé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Expiré</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderNonCompliance__c/recordTypes/Impossibility.recordType-meta.xml
<RecordType>
    <fullName>Impossibility</fullName>
    <active>true</active>
    <description>Impossibilité technique, fonctionnelle ou administrative empêchant l&apos;avancement de la commande client (anciennement non-able)</description>
    <label>Impossibilité</label>
</RecordType>

force-app/main/default/objects/OrderStatusHistory__c/OrderStatusHistory__c.object-meta.xml
<CustomObject>
    <description>HISTORIQUE - Objet pour pipeline GC</description>
    <label>Historique des statuts de commande</label>
    <nameField>
        <displayFormat>OSH-{0000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historique des statuts de commande</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderStatusHistory__c/fields/applicationDate__c.field-meta.xml
<CustomField>
    <fullName>applicationDate__c</fullName>
    <label>Date d&apos;application</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderStatusHistory__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Commande</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La commande n&apos;est pas une commande client!</errorMessage>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Historique des statuts de commande</relationshipLabel>
    <relationshipName>OrderStatusHistory</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderStatusHistory__c/fields/oldCompositeStatus__c.field-meta.xml
<CustomField>
    <fullName>oldCompositeStatus__c</fullName>
    <description>Statut GC de la commande</description>
    <label>Ancien statut composite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderStatusHistory__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <description>Statut Kube3 de la commande</description>
    <label>Statut</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencial__c/Referencial__c.object-meta.xml
<CustomObject>
    <description>Objet contenant le référentiel de KparK (Documents, MF, CGV, autre etc...)</description>
    <label>Référentiel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_LWC_GlobalPipelineGeneratePDF.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_LWC_GlobalPipelineGeneratePDF
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 09/08/2022
//-- Version     : 1.0
//-- Description : Classe de tests de LWC_GlobalPipelineGeneratePDF
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
@isTest
public without sharing class Test_LWC_GlobalPipelineGeneratePDF {
    private static final Id ACC_ENTITY_RTID = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_ENTITY_RT);
    private static final Id ACC_PERSO_RTID = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PERSO_RT);
    private static final Id ACC_PROVIDER_RTID = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PROVIDER_RT);
    private static final Id RT_AST_CARPENTRY = DAL.getRecordTypeIdByDevName('Asset',Constants.ASSET_CARPENTRY_RT); 

    @testSetup 
    static void setup() {
        String refEntityRT = DAL.getRecordTypeIdByDevName('Referencial__c',Constants.REFERENCIAL_ENTITY_RT);  

        // Compte
        Account accountTest = Utils_Test.createAccount('name', 'name', 'test@test.fr', ACC_PERSO_RTID, null, 'Email', true);
        // Fournisseur
        Account provider1 = Utils_Test.createAccountPro('PROVIDERONE','0123456789', ACC_PROVIDER_RTID, null , null, true);
        // Création entite     
        Referencial__c refDep = Utils_Test.createReferencial('Depot', 'DEP', Date.today(), null, refEntityRT, true, true, true, true, true);
        Account entite = Utils_Test.createEntity('TEST', 'DEP00X0', Date.today(), '0123456789', refDep.Id, true);
    }
    
    @isTest
    private static void generatePDFToday() {
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        user.ByPassTrigger__c = 'QA_KMDCEinstein';
        update user;

        System.runAs(user){
            Account accountTest = [SELECT Id FROM Account WHERE RecordTypeId = :ACC_PERSO_RTID LIMIT 1];
            Account entite = [SELECT Id FROM Account WHERE RecordTypeId = :ACC_ENTITY_RTID LIMIT 1];
            Account provider1 = [SELECT Id FROM Account WHERE RecordTypeId = :ACC_PROVIDER_RTID LIMIT 1];

            // Produit
            Product2 productTest1 = Utils_Test.createProduct('Test1', 'TEST1' , true);
            // Commande client
            Order newCustomerOrder = Utils_Test.createCustomerOrder(accountTest.Id, null, entite.Id, entite.Id, false);
            newCustomerOrder.oldCompositeStatus__c = 'Non métrable';
            newCustomerOrder.amount__c = 1000;
            insert newCustomerOrder;
            // NCC
            String oncImposRT = DAL.getRecordTypeIdByDevName('OrderNonCompliance__c', 'Impossibility');
            Utils_Test.createOrderNonCompliance('Test', newCustomerOrder.Id, oncImposRT, true);
            // Actif
            Asset newAsset1 = Utils_Test.createAsset(RT_AST_CARPENTRY, 'Test', newCustomerOrder.Id, productTest1.Id, accountTest.Id, true);
            // Commande fournisseur
            Order newProviderOrder1 = Utils_Test.createProviderOrder(accountTest.Id, newCustomerOrder.Id, provider1.Id ,true);
            // Ligne commande fournisseur
            PricebookEntry pbEntry;
            List<PricebookEntry> pbeList = [SELECT Id, Pricebook2Id, Product2Id, UnitPrice, IsActive, UseStandardPrice 
                                      FROM PricebookEntry 
                                      WHERE Product2Id = :productTest1.Id];
            for(PricebookEntry pbeSelected : pbeList) {
                if(pbeSelected.Product2Id == productTest1.Id) pbEntry = pbeSelected;
            }
            OrderItem newOrderItem1 = Utils_Test.createOrderItem(newProviderOrder1.Id, pbEntry.Id, newAsset1.Id, productTest1.Id, true);
            newProviderOrder1.transmissionDate__c=Date.today();
            update newProviderOrder1;
            
            Test.startTest();
            LWC_GlobalPipelineGeneratePDF.renderDocumentPDF(entite.Id, Date.today(), null, 'pdf'); // Premiere génération
            LWC_GlobalPipelineGeneratePDF.renderDocumentPDF(entite.Id, Date.today(), null, 'pdf'); // Pour regénérer un document
            Test.stopTest();
        }
    }
    
    @isTest
    private static void generatePDFYesterday() {
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        user.ByPassTrigger__c = 'QA_KMDCEinstein';
        update user;

        System.runAs(user){
            Account accountTest = [SELECT Id FROM Account WHERE RecordTypeId = :ACC_PERSO_RTID LIMIT 1];
            Account entite = [SELECT Id FROM Account WHERE RecordTypeId = :ACC_ENTITY_RTID LIMIT 1];
            Account provider1 = [SELECT Id FROM Account WHERE RecordTypeId = :ACC_PROVIDER_RTID LIMIT 1];

            // Produit
            Product2 productTest1 = Utils_Test.createProduct('Test1', 'TEST1' , true);
            // Commande client
            Order newCustomerOrder = Utils_Test.createCustomerOrder(accountTest.Id, null, entite.Id, entite.Id, false);
            newCustomerOrder.oldCompositeStatus__c = 'Non métrable';
            newCustomerOrder.amount__c = 1000;
            insert newCustomerOrder;
            // NCC
            String oncImposRT = DAL.getRecordTypeIdByDevName('OrderNonCompliance__c', 'Impossibility');
            Utils_Test.createOrderNonCompliance('Test', newCustomerOrder.Id, oncImposRT, true);
            // Actif
            Asset newAsset1 = Utils_Test.createAsset(RT_AST_CARPENTRY, 'Test', newCustomerOrder.Id, productTest1.Id, accountTest.Id, true);
            // Commande fournisseur
            Order newProviderOrder1 = Utils_Test.createProviderOrder(accountTest.Id, newCustomerOrder.Id, provider1.Id ,true);
            // Ligne commande fournisseur
            PricebookEntry pbEntry;
            List<PricebookEntry> pbeList = [SELECT Id, Pricebook2Id, Product2Id, UnitPrice, IsActive, UseStandardPrice 
                                      FROM PricebookEntry 
                                      WHERE Product2Id = :productTest1.Id];
            for(PricebookEntry pbeSelected : pbeList) {
                if(pbeSelected.Product2Id == productTest1.Id) pbEntry = pbeSelected;
            }
            OrderItem newOrderItem1 = Utils_Test.createOrderItem(newProviderOrder1.Id, pbEntry.Id, newAsset1.Id, productTest1.Id, true);
            newProviderOrder1.transmissionDate__c=Date.today();
            update newProviderOrder1;

            Test.startTest();
      
            OrderStatusHistory__c old = new OrderStatusHistory__c(
                customerOrder__c = newCustomerOrder.Id,
                oldCompositeStatus__c = newCustomerOrder.oldCompositeStatus__c,
                status__c = newCustomerOrder.oldCompositeStatus__c,
                applicationDate__c = Date.today()-1);
            insert old;

            LWC_GlobalPipelineGeneratePDF.renderDocumentPDF(entite.Id, Date.today()-1, null, 'xlsx');
            Test.stopTest();
        }
    }
    
    @isTest
    private static void testUtils() {
        Test.startTest();
        LWC_GlobalPipelineGeneratePDF.generateAuraException('TEST');
        Test.stopTest();
    }
}