force-app/main/default/objects/OrderNonCompliance__c/OrderNonCompliance__c.object-meta.xml
<CustomObject>
    <description>Objet permettant de définir les non conformités d&apos;une commande client</description>
    <label>Non-conformité commande</label>
    <nameField>
        <label>Motif</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non-conformités commande</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderNonCompliance__c/fields/cancellationDate__c.field-meta.xml
<CustomField>
    <fullName>cancellationDate__c</fullName>
    <label>Date d&apos;annulation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderNonCompliance__c/fields/closeDate__c.field-meta.xml
<CustomField>
    <fullName>closeDate__c</fullName>
    <description>Date de clôture de la tâche de non conformité (Date de résolution)</description>
    <label>Date de fermeture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderNonCompliance__c/fields/expirationDate__c.field-meta.xml
<CustomField>
    <fullName>expirationDate__c</fullName>
    <description>Date d&apos;expiration de la tâche entraînant un blocage du contrat si pas respecté</description>
    <inlineHelpText>Date d&apos;expiration de la tâche entraînant l&apos;action d&apos;expiration si pas respectée</inlineHelpText>
    <label>Date d&apos;expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderNonCompliance__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En cours</fullName>
                <default>true</default>
                <label>En cours</label>
            </value>
            <value>
                <fullName>Clôturé</fullName>
            </value>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>Expiré</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TR020_OrderNonCompliance.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR020_OrderNonCompliance
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 16/06/2021
//-- Version     : 1.0
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
public without sharing class TR020_OrderNonCompliance {

    /**
    * @description Méthode exécutant les différentes méthode de MAJ pour les non-conformités de commande
    * @param userContext Objet contexte de l'utilisateur courant
    */
    public static void applyUpdateRules(UserContext userContext) {
        if (!Trigger.isExecuting) {
            return;
        }        
        applyDataUpdateRules(userContext);
        applyStatusUpdateRules(userContext);
    }
    
    /**
    * @description Méthode exécutant les différentes méthode de MAJ pour les non-conformités de commande
    * @param userContext Information de l'utilisateur courant
    */
    public static void applyDataUpdateRules(UserContext userContext) {          
        System.debug('### DEBUT TR020_OrderNonCompliance.applyDataUpdateRules');
        
        System.debug('### FIN TR020_OrderNonCompliance.applyDataUpdateRules');
    }
    
    /**
    * @description Méthode exécutant les règles de mise à jour du statut pour les non-conformités commande
    * @param userContext Objet contexte de l'utilisateur courant
    */
    private static void applyStatusUpdateRules(UserContext userContext) {
        System.debug('### DEBUT TR020_OrderNonCompliance : applyStatusUpdateRules');
		
        List<OrderNonCompliance__c> newOrderNonCompliances = (List<OrderNonCompliance__c>)Trigger.new;  
        
        for (OrderNonCompliance__c newONC : newOrderNonCompliances) {
            // Vérification des valeurs pour le changement de statut
            if (Trigger.isBefore && (Trigger.isInsert || Trigger.isUpdate)) {   
                System.debug('## Change status for OrderNonCompliance__c: ' + newONC.Id);
                
                //Mise à jour statut
                if(newONC.closeDate__c != null) {
                    newONC.status__c = 'Clôturé';
                } else if(newONC.cancellationDate__c != null) {
                    newONC.status__c = 'Annulé';
                } else if(Date.today() > newONC.expirationDate__c) {
                    newONC.status__c = 'Expiré';
                } else {
                    newONC.status__c = 'En cours';
                }
                System.debug('## OrderNonCompliance__c Status: '+newONC.status__c);
            }
        }
        
        System.debug('### FIN TR020_OrderNonCompliance : applyStatusUpdateRules');
    }
}