force-app/main/default/objects/UserStats__c/UserStats__c.object-meta.xml
<CustomObject>
    <label>Statistiques utilisateur</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statistiques utilisateurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStats__c/fields/user__c.field-meta.xml
<CustomField>
    <fullName>user__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utilisateur</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Statistiques_Utilisateurs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TR020_UserStats.cls
public class TR020_UserStats {

    /***** A - Validation rules *****/
    /**
    public static void applyValidationRules(UserContext userContext) {
        if (!Trigger.isExecuting)
            return;

        List<UserStats__c> newUserStats = (List<UserStats__c>)Trigger.new;
    }
    **/

    /***** B - Update rules *****/
    public static void applyUpdateRules(UserContext userContext) {
        if (!Trigger.isExecuting)
            return;
            
        List<UserStats__c> newUserStats = (List<UserStats__c>)Trigger.new;
        for (UserStats__c newUserStat : newUserStats) {
            // Ecrasement du propriétaire avec l'utilisateur afin de pouvoir gérer le scope (mes stats, les stats de mon équipe, etc.) dans les rapports
            newUserStat.ownerId = newUserStat.user__c;
        }
    }
}