force-app/main/default/objects/Import__c/Import__c.object-meta.xml
<CustomObject>
    <description>Fiche contact des vendeurs ou pour l&apos;import depuis des fichiers ou des sites externes</description>
    <label>Fiche contact (interne, externe)</label>
    <nameField>
        <displayFormat>IMP/{YYYY}/{0000000}</displayFormat>
        <label>Numéro d&apos;import</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fiches contact (interne, externe)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Import__c/fields/civiliteCompte__c.field-meta.xml
<CustomField>
    <fullName>civiliteCompte__c</fullName>
    <label>Civilité (Compte)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M.</fullName>
                <default>true</default>
                <label>M.</label>
            </value>
            <value>
                <fullName>Mme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Import__c/fields/codePostalChantier__c.field-meta.xml
<CustomField>
    <fullName>codePostalChantier__c</fullName>
    <label>Code postal (Chantier)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/codePostalCompte__c.field-meta.xml
<CustomField>
    <fullName>codePostalCompte__c</fullName>
    <label>Code postal (Compte)</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/departementChantier__c.field-meta.xml
<CustomField>
    <fullName>departementChantier__c</fullName>
    <label>Département/Région (Chantier)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/departementCompte__c.field-meta.xml
<CustomField>
    <fullName>departementCompte__c</fullName>
    <label>Département/Région (Compte)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/emailCompte__c.field-meta.xml
<CustomField>
    <fullName>emailCompte__c</fullName>
    <label>Email (Compte)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/nomCompte__c.field-meta.xml
<CustomField>
    <fullName>nomCompte__c</fullName>
    <label>Nom (Compte)</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/paysChantier__c.field-meta.xml
<CustomField>
    <fullName>paysChantier__c</fullName>
    <label>Pays (Chantier)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/paysCompte__c.field-meta.xml
<CustomField>
    <fullName>paysCompte__c</fullName>
    <label>Pays (Compte)</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/prenomCompte__c.field-meta.xml
<CustomField>
    <fullName>prenomCompte__c</fullName>
    <label>Prénom (Compte)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/rueCompte__c.field-meta.xml
<CustomField>
    <fullName>rueCompte__c</fullName>
    <label>Rue (Compte)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/telephoneDomicileCompte__c.field-meta.xml
<CustomField>
    <fullName>telephoneDomicileCompte__c</fullName>
    <label>Téléphone domicile (Compte)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Import__c/fields/villeCompte__c.field-meta.xml
<CustomField>
    <fullName>villeCompte__c</fullName>
    <label>Ville (Compte)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Import__c/recordTypes/importExterne.recordType-meta.xml
<RecordType>
    <fullName>importExterne</fullName>
    <active>true</active>
    <description>Fichier acheté ou loué, site WEB, etc...</description>
    <label>Import externe</label>
</RecordType>

force-app/main/default/classes/Test_Schedule_DemandesDevisNonValidees.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_Schedule_DemandesDevisNonValidees
//-- Modifié par : SOPRA - William DE GAËTANO
//-- Modifié le  : 09/12/2015
//-- Version     : 1.0
//-- * Initialisation
//-- --------------------------------------------------------------------------------- --
@isTest
private class Test_Schedule_DemandesDevisNonValidees {

    /* Méthode de configuration des enregistrements pour les tests */
    /* Méthode standard exécutée avant les tests                   */
    /***************************************************************/
    @testSetup static void setup() {
        PropertiesUtils.setIntegerValue('demandededevis.delai.validation', 120);

        // Récupération des Record Type
        List<Import__c> importsToInsert = new List<Import__c>();

        RecordType rtImport = [SELECT id FROM RecordType WHERE developerName = 'importExterne' LIMIT 1];

        Import__c nouveau_compte1 = new Import__c(recordTypeId = rtImport.id, nomCompte__c = 'NOM1', prenomCompte__c = 'PRENOM1', civiliteCompte__c = 'M', rueCompte__c = '2 avenue des Champs Elysées',
                codePostalCompte__c = '75008', codePostalChantier__c = '75008', villeCompte__c = 'Paris', departementCompte__c = 'Île-de-France', departementChantier__c = 'Île-de-France',
                paysCompte__c = 'France', paysChantier__c = 'France', emailCompte__c = 'puser'+system.now().format('hhmmss')+'@testemail.com', telephoneDomicileCompte__c = '0100000001');

        Import__c nouveau_compte2 = new Import__c(recordTypeId = rtImport.id, nomCompte__c = 'NOM2', prenomCompte__c = 'PRENOM2', civiliteCompte__c = 'M', rueCompte__c = '4 avenue des Champs Elysées',
                codePostalCompte__c = '75008', codePostalChantier__c = '75008', villeCompte__c = 'Paris', departementCompte__c = 'Île-de-France', departementChantier__c = 'Île-de-France',
                paysCompte__c = 'France', paysChantier__c = 'France', emailCompte__c = 'puser'+system.now().format('hhmmss')+'@testemail.com', telephoneDomicileCompte__c = '0100000002');

        Import__c nouveau_compte3 = new Import__c(recordTypeId = rtImport.id, nomCompte__c = 'NOM3', prenomCompte__c = 'PRENOM3', civiliteCompte__c = 'M', rueCompte__c = '6 avenue des Champs Elysées',
                codePostalCompte__c = '75008', codePostalChantier__c = '75008', villeCompte__c = 'Paris', departementCompte__c = 'Île-de-France', departementChantier__c = 'Île-de-France',
                paysCompte__c = 'France', paysChantier__c = 'France', emailCompte__c = 'puser'+system.now().format('hhmmss')+'@testemail.com', telephoneDomicileCompte__c = '0100000003');

        Import__c nouveau_compte4 = new Import__c(recordTypeId = rtImport.id, nomCompte__c = 'NOM4', prenomCompte__c = 'PRENOM4', civiliteCompte__c = 'M', rueCompte__c = '8 avenue des Champs Elysées',
                codePostalCompte__c = '75008', codePostalChantier__c = '75008', villeCompte__c = 'Paris', departementCompte__c = 'Île-de-France', departementChantier__c = 'Île-de-France',
                paysCompte__c = 'France', paysChantier__c = 'France', emailCompte__c = 'puser'+system.now().format('hhmmss')+'@testemail.com', telephoneDomicileCompte__c = '0100000004');

        importsToInsert.add(nouveau_compte1);
        importsToInsert.add(nouveau_compte2);
        importsToInsert.add(nouveau_compte3);
        importsToInsert.add(nouveau_compte4);
        insert importsToInsert;
    }

    @isTest static void test_Schedule_DemandesDevisNonValidees() {
        // Exécution du test
        Test.StartTest();

        String jobId = system.schedule('Demandes de devis non validées TEST', '0 0 * * * ?', new Schedule_DemandesDevisNonValidees() );

        Test.stopTest();
    }
}