force-app/main/default/objects/KContrat__c/KContrat__c.object-meta.xml
<CustomObject>
    <label>Contrat (K)</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats (K)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KContrat__c/fields/NPSRecommandation__c.field-meta.xml
<CustomField>
    <fullName>NPSRecommandation__c</fullName>
    <label>NPS Recommandation</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KContrat__c/fields/NPSSatisfaction__c.field-meta.xml
<CustomField>
    <fullName>NPSSatisfaction__c</fullName>
    <label>NPS Satisfaction</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reponse_questionnaire__c/Reponse_questionnaire__c.object-meta.xml
<CustomObject>
    <description>Réponses faites par les clients pour un questionnaire (SATCLI, autre...)</description>
    <label>Réponse questionnaire</label>
    <nameField>
        <displayFormat>RESP/{YYYY}/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réponses questionnaire</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reponse_questionnaire__c/fields/question__c.field-meta.xml
<CustomField>
    <fullName>question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question_questionnaire__c</referenceTo>
    <relationshipLabel>Réponses questionnaire</relationshipLabel>
    <relationshipName>Reponses_questionnaire</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reponse_questionnaire__c/fields/reponseNumero__c.field-meta.xml
<CustomField>
    <fullName>reponseNumero__c</fullName>
    <label>Réponse Numéro</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reponse_questionnaire__c/fields/resume__c.field-meta.xml
<CustomField>
    <fullName>resume__c</fullName>
    <label>Résumé</label>
    <referenceTo>Resume_questionnaire__c</referenceTo>
    <relationshipLabel>Réponses questionnaire</relationshipLabel>
    <relationshipName>Reponses_questionnaire</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resume_questionnaire__c/Resume_questionnaire__c.object-meta.xml
<CustomObject>
    <description>Objet parent lié aux client des réponses pour un questionnaire (SATCLI, autre...)</description>
    <label>Résumé questionnaire</label>
    <nameField>
        <displayFormat>RQ/{YYYY}/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Résumés questionnaire</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resume_questionnaire__c/fields/contrat__c.field-meta.xml
<CustomField>
    <fullName>contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>KContrat__c</referenceTo>
    <relationshipLabel>Résumés questionnaire</relationshipLabel>
    <relationshipName>Resumes_questionnaire</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TR022_ReponseQuestionnaire.cls
//-- -------------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR022_ReponseQuestionnaire
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 25/01/2019
//-- Version     : 1.0
//-- * 1.0 : Init
//-- -------------------------------------------------------------------------------------- --
public without sharing class TR022_ReponseQuestionnaire {

    /**
    * @description Mise à jour des NPS recommendation et satisfaction des contrats associés
    * @param resumeQuestionnaireList Liste des résumés de questionnaires
    */
    public static void setNPSContrat(List<Reponse_questionnaire__c> reponseQuestionnaireList) {
        if (!Trigger.isExecuting)
            return;

        system.debug('### START TR022_ReponseQuestionnaire.setNPSContrat');
        List<Resume_questionnaire__c> resumeList = new List<Resume_questionnaire__c>();
        List<Reponse_questionnaire__c> reponseQuestionnaireListFiltree = new List<Reponse_questionnaire__c>();
        List<KContrat__c> contratList = new List<KContrat__c>();
        List<String> resumeIds = new List<String>();
        List<String> contratIds = new List<String>();
        String idQuestionRecommendation = PropertiesUtils.getStringValue('satcli.nps.question.recommendation',null);
        String idQuestionSatisfaction = PropertiesUtils.getStringValue('satcli.nps.question.satisfaction',null);
        
        // récupération des devis associés et de toutes leur lignes
        if(reponseQuestionnaireList != null){
            for(Reponse_questionnaire__c rq : reponseQuestionnaireList){
                if(rq.question__c == idQuestionRecommendation || rq.question__c == idQuestionSatisfaction){
                    reponseQuestionnaireListFiltree.add(rq);
                    resumeIds.add(rq.resume__c);
                }
            }
            resumeList = [SELECT Id, contrat__c FROM Resume_questionnaire__c WHERE Id IN :resumeIds];
            for(Resume_questionnaire__c res : resumeList){
                contratIds.add(res.contrat__c);
            }
            contratList = [SELECT Id, NPSRecommandation__c, NPSSatisfaction__c FROM KContrat__c WHERE Id IN :contratIds];
            Map<String,KContrat__c> contratMap = new Map<String,KContrat__c>();
            for(KContrat__c con : contratList){
                contratMap.put(con.Id, con);
            }
            Set<String> contratIdToUpdate = new Set<String>();
            if(!resumeList.isEmpty()){
                for(Resume_questionnaire__c res : resumeList){
                    for(Reponse_questionnaire__c rq : reponseQuestionnaireListFiltree){
                        KContrat__c contrat = contratMap.get(res.contrat__c);
                        if(contrat != null && rq.question__c == idQuestionRecommendation && rq.resume__c == res.Id){
                            contrat.NPSRecommandation__c = rq.reponseNumero__c;
                            contratIdToUpdate.add(contrat.Id);
                        }
                        if(contrat != null && rq.question__c == idQuestionSatisfaction && rq.resume__c == res.Id){
                            contrat.NPSSatisfaction__c = rq.reponseNumero__c;
                            contratIdToUpdate.add(contrat.Id);
                        }
                    }
                }

                List<KContrat__c> contratToUpdate = new List<KContrat__c>();
                for(String conId : contratIdToUpdate){
                    contratToUpdate.add(contratMap.get(conId));
                }
                update contratToUpdate;
            }
        }
        system.debug('### END TR022_ReponseQuestionnaire.setNPSContrat');
    }
}