force-app/main/default/objects/AccountingEntry__c/AccountingEntry__c.object-meta.xml
<CustomObject>
    <label>Écriture comptable</label>
    <nameField>
        <displayFormat>ECC/{YYYY}/{0000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Écritures comptables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountingEntry__c/fields/entityBankAccount__c.field-meta.xml
<CustomField>
    <fullName>entityBankAccount__c</fullName>
    <label>Compte bancaire (Entité)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BankAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipName>AccountingEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountingEntry__c/fields/inputEntity__c.field-meta.xml
<CustomField>
    <fullName>inputEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité de saisie</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountingEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingEntry__c/fields/isAccountingEntryLocked__c.field-meta.xml
<CustomField>
    <fullName>isAccountingEntryLocked__c</fullName>
    <description>Interdire toute suppression d&apos;écriture et ceci pendant une période de 4 ans (à partir de la date de création)</description>
    <formula>ADDMONTHS(DATEVALUE(CreatedDate), 48) &gt; TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>[#] Ecriture comptable vérrouillée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/AccountingPiece__c.object-meta.xml
<CustomObject>
    <label>Pièce comptable</label>
    <nameField>
        <displayFormat>PIC/{YYYY}/{0000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pièces comptables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountingPiece__c/fields/accountingEntry__c.field-meta.xml
<CustomField>
    <fullName>accountingEntry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ecriture comptable</label>
    <referenceTo>AccountingEntry__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/entityBankAccount__c.field-meta.xml
<CustomField>
    <fullName>entityBankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte bancaire (Entité)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BankAccount</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces_BankAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/inputEntity__c.field-meta.xml
<CustomField>
    <fullName>inputEntity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entité de saisie</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pièces comptables (Saisie)</relationshipLabel>
    <relationshipName>AccountingPieces_Input</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referencial__c/Referencial__c.object-meta.xml
<CustomObject>
    <description>Objet contenant le référentiel de KparK (Documents, MF, CGV, autre etc...)</description>
    <label>Référentiel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencial__c/fields/singleEntity__c.field-meta.xml
<CustomField>
    <fullName>singleEntity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entité unique</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TR020_AccountingEntry.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR020_AccountingEntry
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 21/01/2022
//-- Version     : 1.0
//-- --------------------------------------------------------------------------------- --
public without sharing class TR020_AccountingEntry {

    /**
    * @description Méthode pour interdire la suppression d'une écriture comptable pour 4 ans. 
    * Exigence légale a ne pas désactiver ni bypasser !
    * @param userContext contexte utilisateur
    */
    public static void cannotDeleteAccountingEntry(UserContext userContext) {
        System.debug('### DEBUT TR020_AccountingEntry.cannotDeleteAccountingEntry');
        
        List<AccountingEntry__c> oldAccountingEntries = (List<AccountingEntry__c>)Trigger.old;
        for(AccountingEntry__c oldAccountingEntry : oldAccountingEntries){
            if(Trigger.isDelete && Trigger.isBefore && oldAccountingEntry.isAccountingEntryLocked__c) {
                oldAccountingEntry.addError(Label.accEntries_msg_cantDelete);
            }  
        }
        
        System.debug('### FIN TR020_AccountingEntry.cannotDeleteAccountingEntry');
    }

    /**
    * @description Méthode pour vérifier si quand le champ entité unique du compte bancaire est a 
    * vrais toutes les entitées de saisies des pièces comptables associés sont les mêmes !
    * @param userContext contexte utilisateur
    */
    public static void checkUniqueEntity(UserContext userContext) {
        System.debug('### DEBUT TR020_AccountingEntry.checkUniqueEntity');
        
        List<String> apIds = new List<String>();
        Map<String,List<AccountingPiece__c>> accEntryIdToAccPiece = new Map<String,List<AccountingPiece__c>>();
        List<AccountingEntry__c> newAccountingEntries = (List<AccountingEntry__c>)Trigger.new;

        for (AccountingEntry__c newAccountingEntry : newAccountingEntries){
            if(newAccountingEntry.Id != null && !apIds.contains(newAccountingEntry.Id)){
                apIds.add(newAccountingEntry.Id);
            }
        }
        
        System.debug('## apIds: ' + apIds);
        
        if(!apIds.isEmpty()){

            List<AccountingPiece__c> allAccPiece = [SELECT Id, inputEntity__c, accountingEntry__c FROM AccountingPiece__c WHERE accountingEntry__c IN :apIds];
            
            Map<Id,AccountingEntry__c> accEntriesInfo = new Map<Id,AccountingEntry__c>([SELECT Id, entityBankAccount__r.singleEntity__c FROM AccountingEntry__c WHERE Id IN :apIds]);
            
    
            for(AccountingPiece__c accPiece : allAccPiece){
                List<AccountingPiece__c> accPieces = new List<AccountingPiece__c>();
                
                if(accEntryIdToAccPiece.get(accPiece.accountingEntry__c) != null){
                    accPieces = accEntryIdToAccPiece.get(accPiece.accountingEntry__c);
                }
    
                accPieces.add(accPiece);
                accEntryIdToAccPiece.put(accPiece.accountingEntry__c, accPieces);
            }
    
            for (AccountingEntry__c newAccEntry : newAccountingEntries){
                if(!accEntriesInfo.isEmpty() && accEntriesInfo.get(newAccEntry.Id) != null && !accEntryIdToAccPiece.isEmpty() && accEntryIdToAccPiece.get(newAccEntry.Id) != null){
                    for (AccountingPiece__c accPiece : accEntryIdToAccPiece.get(newAccEntry.Id)){
                        if(accEntriesInfo.get(newAccEntry.Id).entityBankAccount__r.singleEntity__c && newAccEntry.inputEntity__c != accPiece.inputEntity__c){
                            newAccEntry.addError(Label.accEntries_msg_SingleEntity);
                        }
                    }
                }
            } 
        }
        
        System.debug('### FIN TR020_AccountingEntry.checkUniqueEntity');
    }
}