force-app/main/default/objects/AccountingEntry__c/AccountingEntry__c.object-meta.xml
<CustomObject>
    <label>Écriture comptable</label>
    <nameField>
        <displayFormat>ECC/{YYYY}/{0000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Écritures comptables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountingEntry__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AccountingEntry__c/fields/entityBankAccount__c.field-meta.xml
<CustomField>
    <fullName>entityBankAccount__c</fullName>
    <label>Compte bancaire (Entité)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BankAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipName>AccountingEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountingEntry__c/fields/entryDate__c.field-meta.xml
<CustomField>
    <fullName>entryDate__c</fullName>
    <label>Date d’écriture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AccountingEntry__c/fields/KparKReference__c.field-meta.xml
<CustomField>
    <fullName>KparKReference__c</fullName>
    <externalId>true</externalId>
    <label>Référence</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountingEntry__c/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <label>Libellé</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountingEntry__c/fields/legacyReference__c.field-meta.xml
<CustomField>
    <fullName>legacyReference__c</fullName>
    <externalId>true</externalId>
    <label>[#] Reprise d&apos;historique (Référence)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/AccountingPiece__c.object-meta.xml
<CustomObject>
    <label>Pièce comptable</label>
    <nameField>
        <displayFormat>PIC/{YYYY}/{0000000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pièces comptables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountingPiece__c/fields/accountingEntry__c.field-meta.xml
<CustomField>
    <fullName>accountingEntry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ecriture comptable</label>
    <referenceTo>AccountingEntry__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/creditMemo__c.field-meta.xml
<CustomField>
    <fullName>creditMemo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Avoir</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CreditMemo__c.creditMemoReference__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>CreditMemo__c.customerOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.order__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CreditMemo__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/entityBankAccount__c.field-meta.xml
<CustomField>
    <fullName>entityBankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte bancaire (Entité)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BankAccount</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces_BankAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountingPiece__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.invoiceReference__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Invoice__c.customerOrder__c</field>
            <operation>equals</operation>
            <valueField>$Source.order__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Pièces comptables</relationshipLabel>
    <relationshipName>AccountingPieces</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BankAccountVisibility__c/BankAccountVisibility__c.object-meta.xml
<CustomObject>
    <description>Objet de liaison entre les comptes bancaires et les entités</description>
    <label>Visibilité compte bancaire</label>
    <nameField>
        <displayFormat>BAV/{0000000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visibilités compte bancaire</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BankAccountVisibility__c/fields/bankAccount__c.field-meta.xml
<CustomField>
    <fullName>bankAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Compte bancaire</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Referencial__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BankAccount</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Referencial__c</referenceTo>
    <relationshipLabel>Visibilités compte bancaire</relationshipLabel>
    <relationshipName>BankAccountVisibilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BankAccountVisibility__c/fields/entity__c.field-meta.xml
<CustomField>
    <fullName>entity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Entité</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Visibilités compte bancaire</relationshipLabel>
    <relationshipName>BankAccountVisibilities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BankAccountVisibility__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>Début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Chantier__c/Chantier__c.object-meta.xml
<CustomObject>
    <description>Le/les chantier(s) d&apos;un compte (client)</description>
    <label>Chantier</label>
    <nameField>
        <label>Nom du chantier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chantiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chantier__c/fields/legacyReference__c.field-meta.xml
<CustomField>
    <fullName>legacyReference__c</fullName>
    <description>REPRISE HISTO : Champ stockant le numéro issu de la GC</description>
    <externalId>true</externalId>
    <label>[#] Reprise d&apos;historique (Référence)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Chantier__c/fields/serviceEntity__c.field-meta.xml
<CustomField>
    <fullName>serviceEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dépôt (Entité service)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entités service (Chantier)</relationshipLabel>
    <relationshipName>ChantierServiceEntities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chantier__c/recordTypes/Chantier.recordType-meta.xml
<RecordType>
    <fullName>Chantier</fullName>
    <active>true</active>
    <label>Chantier</label>
</RecordType>

force-app/main/default/objects/CreditMemo__c/CreditMemo__c.object-meta.xml
<CustomObject>
    <description>Gestion des avoirs basée sur la modélisation des avoirs du modules Salesforce Billing</description>
    <label>Avoir</label>
    <nameField>
        <displayFormat>AVR/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de l’avoir</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avoirs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditMemo__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/autoComputedAmount__c.field-meta.xml
<CustomField>
    <fullName>autoComputedAmount__c</fullName>
    <defaultValue>true</defaultValue>
    <label>[#] Montant auto calculé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Order.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CustomerOrder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>CreditMemos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/invoice__c.field-meta.xml
<CustomField>
    <fullName>invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facture</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>Avoirs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditMemo__c/fields/pretaxAmount__c.field-meta.xml
<CustomField>
    <fullName>pretaxAmount__c</fullName>
    <label>Montant (HT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Gestion des factures basée sur la modélisation du module Salesforce Billing</description>
    <label>Facture</label>
    <nameField>
        <displayFormat>FAC/{YYYY}/{0000000}</displayFormat>
        <label>Numéro de la facture</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>Montant (TTC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/customerOrder__c.field-meta.xml
<CustomField>
    <fullName>customerOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commande client</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La valeur n&apos;existe pas ou ne correspond pas aux critères de filtre!</errorMessage>
        <filterItems>
            <field>Order.RecordTypeId</field>
            <operation>equals</operation>
            <value>Commande client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/pretaxAmount__c.field-meta.xml
<CustomField>
    <fullName>pretaxAmount__c</fullName>
    <label>Montant (HT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Facture</label>
</RecordType>

force-app/main/default/objects/Referencial__c/Referencial__c.object-meta.xml
<CustomObject>
    <description>Objet contenant le référentiel de KparK (Documents, MF, CGV, autre etc...)</description>
    <label>Référentiel</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Référentiels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencial__c/fields/bank__c.field-meta.xml
<CustomField>
    <fullName>bank__c</fullName>
    <label>Banque</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/bic__c.field-meta.xml
<CustomField>
    <fullName>bic__c</fullName>
    <label>BIC</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/iban__c.field-meta.xml
<CustomField>
    <fullName>iban__c</fullName>
    <label>IBAN</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/KparKReference__c.field-meta.xml
<CustomField>
    <fullName>KparKReference__c</fullName>
    <description>Référence interne unique à K par K</description>
    <externalId>true</externalId>
    <label>Référence</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Referencial__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date de début de validité</description>
    <label>Début de validité</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Referencial__c/recordTypes/BankAccount.recordType-meta.xml
<RecordType>
    <fullName>BankAccount</fullName>
    <active>true</active>
    <description>Informations pour les comptes bancaire des entités KparK</description>
    <label>Compte bancaire</label>
</RecordType>

force-app/main/default/objects/Referencial__c/recordTypes/PaymentMethod.recordType-meta.xml
<RecordType>
    <fullName>PaymentMethod</fullName>
    <active>true</active>
    <label>Mode de règlement</label>
</RecordType>

force-app/main/default/classes/Test_LWC_ExportAccountingReportPDF.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : Test_LWC_ExportAccountingReportPDF
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 04/08/2023
//-- Version     : 1.0
//-- Description : Classe de tests de LWC_ExportAccountingReportPDF
//-- * 1.0 : Init
//-- --------------------------------------------------------------------------------- --
@isTest
public without sharing class Test_LWC_ExportAccountingReportPDF {
    private static final Id ACC_ENTITY_RTID = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_ENTITY_RT);
    private static final Id ACC_PERSO_RTID = DAL.getRecordTypeIdByDevName('Account', Constants.ACCOUNT_PERSO_RT);
    private static final String ACCOUNTINGPIECE_DOUBTFULDEBT_RTID = DAL.getRecordTypeIdByDevName('AccountingPiece__c', Constants.ACCOUNTINGPIECE_DOUBTFULDEBT_RT);
    private static final String ACCOUNTINGENTRY_BANKREMITTANCE_RTID = DAL.getRecordTypeIdByDevName('AccountingEntry__c', Constants.ACCOUNTINGENTRY_BANKREMITTANCE_RT);
    private static final String ACCOUNTINGENTRY_UNPAID_RTID = DAL.getRecordTypeIdByDevName('AccountingEntry__c', Constants.ACCOUNTINGENTRY_UNPAID_RT);
    private static final String ACCOUNTINGENTRY_BANKFEES_RTID = DAL.getRecordTypeIdByDevName('AccountingEntry__c', Constants.ACCOUNTINGENTRY_BANKFEES_RT);
    private static final Id REFERENCIAL_BANKACCOUNT_RTID = DAL.getRecordTypeIdByDevName('Referencial__c', 'BankAccount');
    private static final Id REFERENCIAL_PAYMENTMETHOD_RTID = DAL.getRecordTypeIdByDevName('Referencial__c', 'PaymentMethod');
    private static final String ACCOUNTINGPIECE_UNPAID_RTID = DAL.getRecordTypeIdByDevName('AccountingPiece__c', Constants.ACCOUNTINGPIECE_UNPAID_RT);
    private static final String ACCOUNTINGPIECE_RECEIPT_RTID = DAL.getRecordTypeIdByDevName('AccountingPiece__c', Constants.ACCOUNTINGPIECE_RECEIPT_RT);
    private static final String ACCOUNTINGPIECE_RECEIPTCANCELLATION_RTID = DAL.getRecordTypeIdByDevName('AccountingPiece__c', Constants.ACCOUNTINGPIECE_RECEIPTCANCELLATION_RT);
    


    @testSetup 
    static void setup() {
        PropertiesUtils.setDateValue('export.nonCollecte.dateProfondeur', Date.newInstance(2007,01,01));
        PropertiesUtils.setBooleanValue('merkure.api.debug', true);
        String refEntityRT = DAL.getRecordTypeIdByDevName('Referencial__c',Constants.REFERENCIAL_ENTITY_RT);  
        
        Account account = Utils_Test.createAccount('name', 'name', 'test@test.fr', ACC_PERSO_RTID, null, 'Email', true);

        // Création dépôt     
        Referencial__c refDep = Utils_Test.createReferencial('Depot', 'DEP', Date.today(), null, refEntityRT, true, true, true, true, true);
        Account entity = Utils_Test.createEntity('TEST', 'DEP00X0', Date.today(), '0123456789', refDep.Id, false);
        entity.migratedToK3__c = true;
        insert entity;

        //Création chantier
        Chantier__c chantier = Utils_Test.createChantier('test',entity.Id,true);
    }
    
    @isTest
    private static void notCollectedReport() {
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        
        System.runAs(user){
            String exportType = 'Non collecté';

            Date startDate = Date.today();

            Account account = [SELECT Id,Name FROM Account WHERE Name = 'Name name' LIMIT 1];
            Account entity = [SELECT Id,Name FROM Account WHERE Name = 'TEST' LIMIT 1];
            Chantier__c chantier = [SELECT Id,Name FROM Chantier__c LIMIT 1];

            Test.startTest();

            //Création Commande
            Order customerOrder = Utils_Test.createCustomerOrder(account.Id, chantier.Id, null, entity.Id, false);
            customerOrder.effectiveDate = Date.today();
            customerOrder.Type = 'Commande client';
            customerOrder.oldCompositeStatus__c = 'Non confirmé';
            
            insert customerOrder;
            customerOrder.pretaxAmount__c = 1000;
            customerOrder.legacyReference__c = customerOrder.Id;
            customerOrder.serviceEntity__c = entity.Id;
            customerOrder.firstInvoiceDate__c = Date.Today();
            update customerOrder;
            
            //Création factures
            List<Invoice__c> invoices = new List<Invoice__c>();
            Invoice__c invoice = Utils_Test.createInvoice('Facture Test', account.Id, entity.Id, Date.today(), entity.Id, chantier.Id, false);
            Invoice__c invoice2 = Utils_Test.createInvoice('Facture Test2', account.Id, entity.Id, Date.today().addDays(-31), entity.Id, chantier.Id, false);
            invoice.customerOrder__c = customerOrder.Id;
            invoice.amount__c = 100;
            invoice.autoComputedAmount__c = false;
            invoices.Add(invoice);
            invoice2.customerOrder__c = customerOrder.Id;
            invoice2.amount__c = 100;
            invoice2.autoComputedAmount__c = false;
            invoices.Add(invoice2);
            insert invoices;

            //Création avoirs
            List<CreditMemo__c> creditMemos = new List<CreditMemo__c>();
            CreditMemo__c creditMemo = Utils_Test.createCreditMemo(account.Id, entity.Id, invoice.Id, chantier.Id, Date.today(), false);
            CreditMemo__c creditMemo2 = Utils_Test.createCreditMemo(account.Id, entity.Id, invoice.Id, chantier.Id, Date.today(), false);
            creditMemo.customerOrder__c = customerOrder.Id;
            creditMemo.amount__c = 100;
            creditMemos.Add(creditMemo);
            creditMemo2.customerOrder__c = customerOrder.Id;
            creditMemo2.amount__c = 100;
            creditMemos.Add(creditMemo2);

            insert creditMemos;

            //Création pièces comptables
            List<AccountingPiece__c> accountingPieces = new List<AccountingPiece__c>();
            AccountingPiece__c accountingPiece = Utils_Test.createAccountingPiece(ACCOUNTINGPIECE_DOUBTFULDEBT_RTID, customerOrder.Id, entity.Id, entity.Id, null, null, 
            null, null, 100, Date.today(), Date.today(), Date.today(), true);

            Map<String, String> availableEntities = LWC_ExportAccountingReportPDF.getEntityAccounts();
            Assert.areEqual(1,availableEntities.size());

            String entityid = availableEntities.get('TEST').split('/')[0];
            String entityName = availableEntities.get('TEST').split('/')[1];
            Assert.areEqual('TEST',entityName);

            String[] bankAccounts = new String[]{};

            String jsonString = LWC_ExportAccountingReportPDF.generateJsonObject(exportType, entityid, entityName, startDate, null, bankAccounts);

            //Vérif Json généré (Montant total factures : avoir / pièces comtpables)
            LWC_ExportAccountingReportPDF.NotCollectedReportObject jsonObject = new LWC_ExportAccountingReportPDF.NotCollectedReportObject();
            jsonObject = (LWC_ExportAccountingReportPDF.NotCollectedReportObject)JSON.deserialize(jsonString, LWC_ExportAccountingReportPDF.NotCollectedReportObject.class);
            Assert.areEqual(200,jsonObject.Orders[0].invoicesAmount);
            Assert.areEqual(200,jsonObject.Orders[0].creditMemosAmount);
            Assert.areEqual(100,jsonObject.Orders[0].doubtfulAccountingPieceAmount);

            String result = LWC_ExportAccountingReportPDF.renderDocumentPDF(exportType, entityid, entityName, startDate, null, jsonString);

            //vérif création lien vers document sur entité
            List<ContentDocumentLink> ctLinkList = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :entityid];
            Assert.areEqual(1,ctLinkList.size());

            Test.stopTest();
        }
    }

    @isTest
    private static void bankReport(){
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        System.runAs(user){
            Account account = [SELECT Id,Name FROM Account WHERE Name = 'Name name' LIMIT 1];
            Account entity = [SELECT Id,Name FROM Account WHERE Name = 'TEST' LIMIT 1];
            Chantier__c chantier = [SELECT Id,Name FROM Chantier__c LIMIT 1];

            Test.startTest();

            //Création comtpes bancaires visibles depuis le dépôt

            List<Referencial__c> refList = new List<Referencial__c>();
            Referencial__c refBank = Utils_Test.createReferencial('BANK TEST', 'refBank', Date.today(), null, REFERENCIAL_BANKACCOUNT_RTID, true, true, true, true, false);
            refBank.bank__c = 'BANQUE DE TEST';
            refBank.bic__c = 'INGBFRPP';
            refBank.iban__c = 'FR1420041010050500013M02606';
            refList.Add(refBank);
            Referencial__c refBank2 = Utils_Test.createReferencial('BANK TEST2', 'refBank2', Date.today(), null, REFERENCIAL_BANKACCOUNT_RTID, true, true, true, true, false);
            refBank2.bank__c = 'BANQUE DE TEST 2';
            refBank2.bic__c = 'INGBFRPP';
            refBank2.iban__c = 'FR1420041010050500013M02606';
            refList.Add(refBank2);

            Referencial__c refPaymentMethod = Utils_Test.createReferencial('PAYMENT METHOD TEST', 'refPaymentMethod', Date.today(), null, REFERENCIAL_PAYMENTMETHOD_RTID, true, true, true, true, false);
            refList.Add(refPaymentMethod);
            
            insert refList;

            List<BankAccountVisibility__c> bankAccountVisibilityList = new List<BankAccountVisibility__c>();
            BankAccountVisibility__c bankAccountVisibility = new BankAccountVisibility__c(bankAccount__c = refBank.Id, entity__c = entity.Id, startDate__c = Date.today());
            BankAccountVisibility__c bankAccountVisibility2 = new BankAccountVisibility__c(bankAccount__c = refBank2.Id, entity__c = entity.Id, startDate__c = Date.today());
            bankAccountVisibilityList.Add(bankAccountVisibility);
            bankAccountVisibilityList.Add(bankAccountVisibility2);
            insert bankAccountVisibilityList;


            //Type de journal et date de début et de fin d'observation de l'export
            String exportType = 'Journal des banques';
            Date startDate = Date.today();
            Date endDate = Date.today();

            //Création Commande
            Order customerOrder = Utils_Test.createCustomerOrder(account.Id, chantier.Id, null, entity.Id, false);
            customerOrder.effectiveDate = Date.today();
            customerOrder.Type = 'Commande client';
            customerOrder.oldCompositeStatus__c = 'Non confirmé';
            insert customerOrder;
            customerOrder.pretaxAmount__c = 1000;
            customerOrder.serviceEntity__c = entity.Id;
            update customerOrder;

            //Création pièces comptable
            AccountingPiece__c accountingPiece = Utils_Test.createAccountingPiece(ACCOUNTINGPIECE_RECEIPT_RTID, customerOrder.Id, entity.Id, entity.Id, refBank.Id, refPaymentMethod.Id, 
            null, null, 100, Date.today(), Date.today(), Date.today(), true);
           
            //Création écriture comptable
            List<AccountingEntry__c> accountingEntries = new List<AccountingEntry__c>();
            AccountingEntry__c accountingEntry = new AccountingEntry__c(RecordTypeId = ACCOUNTINGENTRY_BANKFEES_RTID, 
                                                                            amount__c = 1000,
                                                                            KparKReference__c = 'REF-TEST',
                                                                            label__c = 'Frais bancaire',
                                                                            entryDate__c = Date.today(),
                                                                            entityBankAccount__c = refBank.Id,
                                                                            inputEntity__c = entity.Id);
            AccountingEntry__c accountingEntry2 = new AccountingEntry__c(RecordTypeId = ACCOUNTINGENTRY_UNPAID_RTID, 
                                                                            amount__c = -200,
                                                                            KparKReference__c = 'REF-TEST2',
                                                                            label__c = 'Impayés',
                                                                            entryDate__c = Date.today(),
                                                                            entityBankAccount__c = refBank2.Id,
                                                                            inputEntity__c = entity.Id);
            accountingEntries.Add(accountingEntry);
            accountingEntries.Add(accountingEntry2);
            insert accountingEntries;

            //Sélection des comtpes bancaires à récupérer dans l'export
            Map<String, String> bankAccounts = LWC_ExportAccountingReportPDF.getBankAccounts(entity.Id, startDate, endDate);
            //Vérif Comptes bancaires disponibles 
            Assert.areEqual(2,bankAccounts.size());

            String[] bankAccountsSelected = new String[]{ bankAccounts.get('BANK TEST'), bankAccounts.get('BANK TEST2')};

            String jsonString = LWC_ExportAccountingReportPDF.generateJsonObject(exportType, entity.Id, entity.Name, startDate, endDate, bankAccountsSelected);
            //Vérif Json généré
            LWC_ExportAccountingReportPDF.BankReportObject jsonObject = new LWC_ExportAccountingReportPDF.BankReportObject();
            jsonObject = (LWC_ExportAccountingReportPDF.BankReportObject)JSON.deserialize(jsonString, LWC_ExportAccountingReportPDF.BankReportObject.class);
            //Filtré sur banques sélectionnées
            Assert.areEqual(2,jsonObject.bankAccountLines.size());
            //2 écritures associé à la 1ère banque
            Assert.areEqual(2,jsonObject.bankAccountLines[0].details.size());
            //pièce comptable ajoutée dans distribution
            Assert.areEqual(100,jsonObject.bankAccountLines[0].distribution[0].amount);

            String result = LWC_ExportAccountingReportPDF.renderDocumentPDF(exportType, entity.Id, entity.Name, startDate, endDate, jsonString);

            //vérif création lien vers document sur entité
            List<ContentDocumentLink> ctLinkList = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :entity.Id];
            Assert.areEqual(1,ctLinkList.size());

            Test.stopTest();
        }
    }

    @isTest
    private static void accountingPiecesReport(){
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        System.runAs(user){
            Account account = [SELECT Id,Name FROM Account WHERE Name = 'Name name' LIMIT 1];
            Account entity = [SELECT Id,Name FROM Account WHERE Name = 'TEST' LIMIT 1];
            Chantier__c chantier = [SELECT Id,Name FROM Chantier__c LIMIT 1];


            Test.startTest();
            Referencial__c refBank = Utils_Test.createReferencial('BANK TEST', 'REFERENCIAL_BANKACCOUNT_RTID', Date.today(), null, REFERENCIAL_BANKACCOUNT_RTID, true, true, true, true, false);
            refBank.bank__c = 'BANQUE DE TEST';
            refBank.bic__c = 'INGBFRPP';
            refBank.iban__c = 'FR1420041010050500013M02606';
            insert refBank;

            //Création Commande
            Order customerOrder = Utils_Test.createCustomerOrder(account.Id, chantier.Id, null, entity.Id, false);
            customerOrder.effectiveDate = Date.today();
            customerOrder.Type = 'Commande client';
            customerOrder.oldCompositeStatus__c = 'Non confirmé';
            
            insert customerOrder;
            customerOrder.pretaxAmount__c = 1000;
            //ustomerOrder.legacyReference__c = customerOrder.Id;
            customerOrder.serviceEntity__c = entity.Id;
            update customerOrder;

            String exportType = 'Journal des OD';
            Date startDate = Date.today().addDays(-30);
            Date endDate = Date.today();
            String[] bankAccounts = new String[]{};

            //Création piece comptable
            AccountingPiece__c accountingPiece = Utils_Test.createAccountingPiece(ACCOUNTINGPIECE_DOUBTFULDEBT_RTID, customerOrder.Id, entity.Id, entity.Id, refBank.Id, null, 
            null, null, 100, Date.today(), Date.today(), Date.today().addDays(-20), true);

            String jsonString = LWC_ExportAccountingReportPDF.generateJsonObject(exportType, entity.Id, entity.Name, startDate, endDate, bankAccounts);

            //Vérif Json généré
            LWC_ExportAccountingReportPDF.OtherTypeReportObject jsonObject = new LWC_ExportAccountingReportPDF.OtherTypeReportObject();
            jsonObject = (LWC_ExportAccountingReportPDF.OtherTypeReportObject)JSON.deserialize(jsonString, LWC_ExportAccountingReportPDF.OtherTypeReportObject.class);
            //1 pièce récupérée
            Assert.areEqual(1,jsonObject.accountingObjects.size());
            //Montant de la pièce récupéré
            Assert.areEqual(100,jsonObject.accountingObjects[0].amount);
            
            String result = LWC_ExportAccountingReportPDF.renderDocumentPDF(exportType, entity.Id, entity.Name, startDate, endDate, jsonString);

            //vérif création lien vers document sur entité
            List<ContentDocumentLink> ctLinkList = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :entity.Id];
            Assert.areEqual(1,ctLinkList.size());

            Test.stopTest();
        }
    }

    @isTest
    private static void sellReport(){
        User user = Utils_Test.createUser(false,'testmlg2', 'MyTestUserName2@test.sfd.test', 'MyTestLastName2','MyTestFirstName2', null, null);
        System.runAs(user){
            Account account = [SELECT Id,Name FROM Account WHERE Name = 'Name name' LIMIT 1];
            Account entity = [SELECT Id,Name FROM Account WHERE Name = 'TEST' LIMIT 1];
            Chantier__c chantier = [SELECT Id,Name FROM Chantier__c LIMIT 1];


            Test.startTest();
            Referencial__c refBank = Utils_Test.createReferencial('BANK TEST', 'REFERENCIAL_BANKACCOUNT_RTID', Date.today(), null, REFERENCIAL_BANKACCOUNT_RTID, true, true, true, true, false);
            refBank.bank__c = 'BANQUE DE TEST';
            refBank.bic__c = 'INGBFRPP';
            refBank.iban__c = 'FR1420041010050500013M02606';
            insert refBank;

            //Création Commande
            Order customerOrder = Utils_Test.createCustomerOrder(account.Id, chantier.Id, null, entity.Id, false);
            customerOrder.effectiveDate = Date.today();
            customerOrder.Type = 'Commande client';
            customerOrder.oldCompositeStatus__c = 'Non confirmé';
            
            insert customerOrder;
            customerOrder.pretaxAmount__c = 1000;
            //ustomerOrder.legacyReference__c = customerOrder.Id;
            customerOrder.serviceEntity__c = entity.Id;
            update customerOrder;

            String exportType = 'Journal des ventes';
            Date startDate = Date.today().addDays(-30);
            Date endDate = Date.today();
            String[] bankAccounts = new String[]{};

            //Création factures
            List<Invoice__c> invoices = new List<Invoice__c>();
            Invoice__c invoice = Utils_Test.createInvoice('Facture Test', account.Id, entity.Id, Date.today().addDays(-5), entity.Id, chantier.Id, false);
            Invoice__c invoice2 = Utils_Test.createInvoice('Facture Test2', account.Id, entity.Id, Date.today().addDays(-20), entity.Id, chantier.Id, false);
            invoice.customerOrder__c = customerOrder.Id;
            invoice.amount__c = 100;
            invoice.invoiceReference__c = 'TEST';
            invoices.Add(invoice);
            invoice2.customerOrder__c = customerOrder.Id;
            invoice2.amount__c = 100;
            invoice2.invoiceReference__c = 'TEST2';
            invoices.Add(invoice2);
            insert invoices;

            //Création avoirs
            List<CreditMemo__c> creditMemos = new List<CreditMemo__c>();
            CreditMemo__c creditMemo = Utils_Test.createCreditMemo(account.Id, entity.Id, invoice.Id, chantier.Id, Date.today().addDays(-5), false);
            CreditMemo__c creditMemo2 = Utils_Test.createCreditMemo(account.Id, entity.Id, invoice.Id, chantier.Id, Date.today().addDays(-20), false);
            creditMemo.customerOrder__c = customerOrder.Id;
            creditMemo.amount__c = 100;
            creditMemo.creditMemoReference__c = 'TEST';
            creditMemos.Add(creditMemo);
            creditMemo2.customerOrder__c = customerOrder.Id;
            creditMemo2.amount__c = 100;
            creditMemo2.creditMemoReference__c = 'TEST2';
            creditMemos.Add(creditMemo2);

            insert creditMemos;
            
            String jsonString = LWC_ExportAccountingReportPDF.generateJsonObject(exportType, entity.Id, entity.Name, startDate, endDate, bankAccounts);

            //Vérif Json généré
            LWC_ExportAccountingReportPDF.OtherTypeReportObject jsonObject = new LWC_ExportAccountingReportPDF.OtherTypeReportObject();
            jsonObject = (LWC_ExportAccountingReportPDF.OtherTypeReportObject)JSON.deserialize(jsonString, LWC_ExportAccountingReportPDF.OtherTypeReportObject.class);
            //2 factures + 2 avoirs récupérés
            Assert.areEqual(4,jsonObject.accountingObjects.size());

            String result = LWC_ExportAccountingReportPDF.renderDocumentPDF(exportType, entity.Id, entity.Name, startDate, endDate, jsonString);

            //vérif création lien vers document sur entité
            List<ContentDocumentLink> ctLinkList = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :entity.Id];
            Assert.areEqual(1,ctLinkList.size());

            Test.stopTest();
        }
    }

    @isTest
    private static void testUtils() {
        Test.startTest();
        AuraHandledException error = LWC_ExportAccountingReportPDF.generateAuraException('TEST');
        Assert.areEqual('TEST',error.getMessage());
        Test.stopTest();
    }
}