force-app/main/default/objects/FinancialCharge__c/FinancialCharge__c.object-meta.xml
<CustomObject>
    <label>Charge financière</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charges financières</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FinancialCharge__c/fields/isLocked__c.field-meta.xml
<CustomField>
    <fullName>isLocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Une charge verrouillée a été alimentée par un système externe et ne peut donc pas être modifiée/supprimée manuellement</description>
    <label>Verrouillée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TR020_FinancialCharge.cls
//-- --------------------------------------------------------------------------------- --
//-- *
//-- Fichier     : TR020_FinancialCharge
//-- Modifié par : SOPRA STERIA
//-- Modifié le  : 24/11/2020
//-- Version     : 1.0
//-- --------------------------------------------------------------------------------- --
public without sharing class TR020_FinancialCharge {

	/**
    * @description Méthode exécutant les différentes règles de validation pour les charges financière
    * @param userContext Objet contexte de l'utilisateur courant
    */
    public static void applyValidationRules(UserContext userContext) {
        System.debug('### DEBUT TR020_FinancialCharge.applyValidationRules');
        
        List<FinancialCharge__c> oldFinancialCharges = (List<FinancialCharge__c>)Trigger.old;
        for(FinancialCharge__c oldFinancialCharge : oldFinancialCharges){
            // Ne pas supprimer si la charge est verrouillée
            if(oldFinancialCharge.isLocked__c && Trigger.isDelete && Trigger.isBefore){
                oldFinancialCharge.addError(Label.financialCharge_msg_cantDelete);
            }
        }
        
        System.debug('### FIN TR020_FinancialCharge.applyValidationRules');
    }
}